#ifndef _CML_tentusscher_model_2006_M_pe_lut_
#define _CML_tentusscher_model_2006_M_pe_lut_

//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: tentusscher_model_2006_M
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translate: 1844, pycml: 1844)
//! on Tue Jul 19 22:25:56 2011
//! 
//! <autogenerated>



class CML_tentusscher_model_2006_M_pe_lut_LookupTables
{
public:
    static CML_tentusscher_model_2006_M_pe_lut_LookupTables* Instance()
    {
        if (mpInstance == NULL)
        {
            mpInstance = new CML_tentusscher_model_2006_M_pe_lut_LookupTables;
        }
        return mpInstance;
    }
    
    // Methods to look up values from lookup tables
    // using linear interpolation
    inline double _lookup_0(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][0];
        double y2 = _lookup_table_0[i+1][0];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_1(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][1];
        double y2 = _lookup_table_0[i+1][1];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_2(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][2];
        double y2 = _lookup_table_0[i+1][2];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_3(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][3];
        double y2 = _lookup_table_0[i+1][3];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_4(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][4];
        double y2 = _lookup_table_0[i+1][4];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_5(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][5];
        double y2 = _lookup_table_0[i+1][5];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_6(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][6];
        double y2 = _lookup_table_0[i+1][6];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_7(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][7];
        double y2 = _lookup_table_0[i+1][7];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_8(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][8];
        double y2 = _lookup_table_0[i+1][8];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_9(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][9];
        double y2 = _lookup_table_0[i+1][9];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_10(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][10];
        double y2 = _lookup_table_0[i+1][10];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_11(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][11];
        double y2 = _lookup_table_0[i+1][11];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_12(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][12];
        double y2 = _lookup_table_0[i+1][12];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_13(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][13];
        double y2 = _lookup_table_0[i+1][13];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_14(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][14];
        double y2 = _lookup_table_0[i+1][14];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_15(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][15];
        double y2 = _lookup_table_0[i+1][15];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_16(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][16];
        double y2 = _lookup_table_0[i+1][16];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_17(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][17];
        double y2 = _lookup_table_0[i+1][17];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_18(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][18];
        double y2 = _lookup_table_0[i+1][18];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_19(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][19];
        double y2 = _lookup_table_0[i+1][19];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_20(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][20];
        double y2 = _lookup_table_0[i+1][20];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_21(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][21];
        double y2 = _lookup_table_0[i+1][21];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_22(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][22];
        double y2 = _lookup_table_0[i+1][22];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_23(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][23];
        double y2 = _lookup_table_0[i+1][23];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_24(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][24];
        double y2 = _lookup_table_0[i+1][24];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_25(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][25];
        double y2 = _lookup_table_0[i+1][25];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_26(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][26];
        double y2 = _lookup_table_0[i+1][26];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_27(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][27];
        double y2 = _lookup_table_0[i+1][27];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_28(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][28];
        double y2 = _lookup_table_0[i+1][28];
        return y1 + (y2-y1)*factor;
    }
    
    
protected:
    CML_tentusscher_model_2006_M_pe_lut_LookupTables(const CML_tentusscher_model_2006_M_pe_lut_LookupTables&);
    CML_tentusscher_model_2006_M_pe_lut_LookupTables& operator= (const CML_tentusscher_model_2006_M_pe_lut_LookupTables&);
    CML_tentusscher_model_2006_M_pe_lut_LookupTables()
    {
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][0] = 1.0 / (1.0 + exp(( -26.0 - var_membrane__V) * 0.142857142857));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][1] = 1.0 * (450.0 / (1.0 + exp(( -45.0 - var_membrane__V) * 0.1))) * (6.0 / (1.0 + exp((var_membrane__V + 30.0) * 0.0869565217391)));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][2] = 1.0 / (1.0 + exp((var_membrane__V + 88.0) * 0.0416666666667));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][3] = 1.0 * (3.0 / (1.0 + exp(( -60.0 - var_membrane__V) * 0.05))) * (1.12 / (1.0 + exp((var_membrane__V - 60.0) * 0.05)));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][4] = 1.0 / (1.0 + exp(( -5.0 - var_membrane__V) * 0.0714285714286));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][5] = (1.0 * (1400.0 / sqrt(1.0 + exp((5.0 - var_membrane__V) * 0.166666666667))) * (1.0 / (1.0 + exp((var_membrane__V - 35.0) * 0.0666666666667)))) + 80.0;
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][6] = 1.0 / pow(1.0 + exp(( -56.86 - var_membrane__V) * 0.110741971207), 2.0);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][7] = 1.0 * (1.0 / (1.0 + exp(( -60.0 - var_membrane__V) * 0.2))) * ((0.1 / (1.0 + exp((var_membrane__V + 35.0) * 0.2))) + (0.1 / (1.0 + exp((var_membrane__V - 50.0) * 0.005))));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][8] = 1.0 / pow(1.0 + exp((var_membrane__V + 71.55) * 0.134589502019), 2.0);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][9] = 1.0 / (((var_membrane__V <  -40.0) ? (0.057 * exp((-(var_membrane__V + 80.0)) * 0.147058823529)) : 0.0) + ((var_membrane__V <  -40.0) ? ((2.7 * exp(0.079 * var_membrane__V)) + (310000.0 * exp(0.3485 * var_membrane__V))) : (0.77 / (0.13 * (1.0 + exp((var_membrane__V + 10.66) *  -0.0900900900901))))));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][10] = 1.0 / pow(1.0 + exp((var_membrane__V + 71.55) * 0.134589502019), 2.0);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][11] = 1.0 / (((var_membrane__V <  -40.0) ? ((((( -25428.0 * exp(0.2444 * var_membrane__V)) - (6.948e-06 * exp( -0.04391 * var_membrane__V))) * (var_membrane__V + 37.78)) * 1.0) / (1.0 + exp(0.311 * (var_membrane__V + 79.23)))) : 0.0) + ((var_membrane__V <  -40.0) ? ((0.02424 * exp( -0.01052 * var_membrane__V)) / (1.0 + exp( -0.1378 * (var_membrane__V + 40.14)))) : ((0.6 * exp(0.057 * var_membrane__V)) / (1.0 + exp( -0.1 * (var_membrane__V + 32.0))))));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][12] = exp((2.0 * (var_membrane__V - 15.0) * 96485.3415) * 3.87974901066e-07);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][13] = exp((2.0 * (var_membrane__V - 15.0) * 96485.3415) * 3.87974901066e-07) - 1.0;
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][14] = 1.0 / (1.0 + exp(( -8.0 - var_membrane__V) * 0.133333333333));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][15] = (1.0 * ((1.4 / (1.0 + exp(( -35.0 - var_membrane__V) * 0.0769230769231))) + 0.25) * (1.4 / (1.0 + exp((var_membrane__V + 5.0) * 0.2)))) + (1.0 / (1.0 + exp((50.0 - var_membrane__V) * 0.05)));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][16] = 1.0 / (1.0 + exp((var_membrane__V + 20.0) * 0.142857142857));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][17] = (1102.5 * exp((-pow(var_membrane__V + 27.0, 2.0)) * 0.00444444444444)) + (200.0 / (1.0 + exp((13.0 - var_membrane__V) * 0.1))) + (180.0 / (1.0 + exp((var_membrane__V + 30.0) * 0.1))) + 20.0;
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][18] = (0.67 / (1.0 + exp((var_membrane__V + 35.0) * 0.142857142857))) + 0.33;
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][19] = (562.0 * exp((-pow(var_membrane__V + 27.0, 2.0)) * 0.00416666666667)) + (31.0 / (1.0 + exp((25.0 - var_membrane__V) * 0.1))) + (80.0 / (1.0 + exp((var_membrane__V + 30.0) * 0.1)));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][20] = 1.0 / (1.0 + exp((var_membrane__V + 20.0) * 0.2));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][21] = (85.0 * exp((-pow(var_membrane__V + 45.0, 2.0)) * 0.003125)) + (5.0 / (1.0 + exp((var_membrane__V - 20.0) * 0.2))) + 3.0;
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][22] = 1.0 / (1.0 + exp((20.0 - var_membrane__V) * 0.166666666667));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][23] = (9.5 * exp((-pow(var_membrane__V + 40.0, 2.0)) * 0.000555555555556)) + 0.8;
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][24] = 1.0 + (0.1245 * exp(( -0.1 * var_membrane__V * 96485.3415) * 3.87974901066e-07)) + (0.0353 * exp(((-var_membrane__V) * 96485.3415) * 3.87974901066e-07));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][25] = exp((0.35 * var_membrane__V * 96485.3415) * 3.87974901066e-07);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][26] = exp(( -0.65 * var_membrane__V * 96485.3415) * 3.87974901066e-07);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][27] = 3413921.875 * 3.38 * (1.0 + (0.1 * exp(( -0.65 * var_membrane__V * 96485.3415) * 3.87974901066e-07)));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_membrane__V = -100.0001 + i*0.01;
            _lookup_table_0[i][28] = 1.0 + exp((25.0 - var_membrane__V) * 0.167224080268);
        }
        
    }
    
private:
    /** The single instance of the class */
    static CML_tentusscher_model_2006_M_pe_lut_LookupTables *mpInstance;

    // Lookup tables
    double _lookup_table_0[16001][29];
    
};

CML_tentusscher_model_2006_M_pe_lut_LookupTables* CML_tentusscher_model_2006_M_pe_lut_LookupTables::mpInstance = NULL;

// 
// Settable parameters and readable variables
// 
void __equation__pe_lut_(Solveode *classe)
{
    // Inputs:
    // Time units: millisecond
    double var_environment__time= classe->time_new;
    double var_membrane__i_K1;
    double var_membrane__i_to;
    double var_membrane__i_Kr;
    double var_membrane__i_Ks;
    double var_membrane__i_CaL;
    double var_membrane__i_NaK;
    double var_membrane__i_Na;
    double var_membrane__i_b_Na;
    double var_membrane__i_NaCa;
    double var_membrane__i_b_Ca;
    double var_membrane__i_p_K;
    double var_membrane__i_p_Ca;
    double var_membrane__i_Stim;
    double var_membrane__V = classe->V_old_; //var_membrane
    // Units: millivolt; Initial value: -85.423
    double var_rapid_time_dependent_potassium_current_Xr1_gate__Xr1 = classe->Xr1_old_; //var_rapid_time_dependent_potassium_current_Xr1_gate
    // Units: dimensionless; Initial value: 0.0165
    double var_rapid_time_dependent_potassium_current_Xr2_gate__Xr2 = classe->Xr2_old_; //var_rapid_time_dependent_potassium_current_Xr2_gate
    // Units: dimensionless; Initial value: 0.473
    double var_slow_time_dependent_potassium_current_Xs_gate__Xs = classe->Xs_old_; //var_slow_time_dependent_potassium_current_Xs_gate
    // Units: dimensionless; Initial value: 0.0174
    double var_fast_sodium_current_m_gate__m = classe->m_old_; //var_fast_sodium_current_m_gate
    // Units: dimensionless; Initial value: 0.00165
    double var_fast_sodium_current_h_gate__h = classe->h_old_; //var_fast_sodium_current_h_gate
    // Units: dimensionless; Initial value: 0.749
    double var_fast_sodium_current_j_gate__j = classe->j_old_; //var_fast_sodium_current_j_gate
    // Units: dimensionless; Initial value: 0.6788
    double var_L_type_Ca_current_d_gate__d = classe->d_old_; //var_L_type_Ca_current_d_gate
    // Units: dimensionless; Initial value: 3.288e-5
    double var_L_type_Ca_current_f_gate__f = classe->f_old_; //var_L_type_Ca_current_f_gate
    // Units: dimensionless; Initial value: 0.7026
    double var_L_type_Ca_current_f2_gate__f2 = classe->f2_old_; //var_L_type_Ca_current_f2_gate
    // Units: dimensionless; Initial value: 0.9526
    double var_L_type_Ca_current_fCass_gate__fCass = classe->fCass_old_; //var_L_type_Ca_current_fCass_gate
    // Units: dimensionless; Initial value: 0.9942
    double var_transient_outward_current_s_gate__s = classe->s_old_; //var_transient_outward_current_s_gate
    // Units: dimensionless; Initial value: 0.999998
    double var_transient_outward_current_r_gate__r = classe->r_old_; //var_transient_outward_current_r_gate
    // Units: dimensionless; Initial value: 2.347e-8
    double var_calcium_dynamics__Ca_i = classe->Ca_i_old_; //var_calcium_dynamics
    // Units: millimolar; Initial value: 0.000153
    double var_calcium_dynamics__Ca_SR = classe->Ca_SR_old_; //var_calcium_dynamics
    // Units: millimolar; Initial value: 4.272
    double var_calcium_dynamics__Ca_ss = classe->Ca_ss_old_; //var_calcium_dynamics
    // Units: millimolar; Initial value: 0.00042
    double var_calcium_dynamics__R_prime = classe->R_prime_old_; //var_calcium_dynamics
    // Units: dimensionless; Initial value: 0.8978
    double var_sodium_dynamics__Na_i = classe->Na_i_old_; //var_sodium_dynamics
    // Units: millimolar; Initial value: 10.132
    double var_potassium_dynamics__K_i = classe->K_i_old_; //var_potassium_dynamics
    // Units: millimolar; Initial value: 138.52
    
    
    // Lookup table indexing
    if (var_membrane__V>59.9999 || var_membrane__V<-100.0001)
    {
#define COVERAGE_IGNORE
        printf("V outside lookup table range");
#undef COVERAGE_IGNORE
    }
    
    double _offset_0 = var_membrane__V - -100.0001;
    double _offset_0_over_table_step = _offset_0 * 100.0;
    unsigned _table_index_0 = (unsigned)(_offset_0_over_table_step);
    double _factor_0 = _offset_0_over_table_step - _table_index_0;
    
    // Mathematics
    const double var_reversal_potentials__E_K = 26.7137606597 * log(5.4 / var_potassium_dynamics__K_i);
    const double var_inward_rectifier_potassium_current__alpha_K1 = 0.1 / (1.0 + exp(0.06 * ((var_membrane__V - var_reversal_potentials__E_K) - 200.0)));
    const double var_inward_rectifier_potassium_current__i_K1 = 5.405 * (var_inward_rectifier_potassium_current__alpha_K1 / (var_inward_rectifier_potassium_current__alpha_K1 + (((3.0 * exp(0.0002 * ((var_membrane__V - var_reversal_potentials__E_K) + 100.0))) + exp(0.1 * ((var_membrane__V - var_reversal_potentials__E_K) - 10.0))) / (1.0 + exp( -0.5 * (var_membrane__V - var_reversal_potentials__E_K)))))) * (var_membrane__V - var_reversal_potentials__E_K);
    var_membrane__i_K1 = var_inward_rectifier_potassium_current__i_K1;
    const double var_transient_outward_current__i_to = 0.294 * var_transient_outward_current_r_gate__r * var_transient_outward_current_s_gate__s * (var_membrane__V - var_reversal_potentials__E_K);
    var_membrane__i_to = var_transient_outward_current__i_to;
    const double var_rapid_time_dependent_potassium_current__i_Kr = 0.153 * var_rapid_time_dependent_potassium_current_Xr1_gate__Xr1 * var_rapid_time_dependent_potassium_current_Xr2_gate__Xr2 * (var_membrane__V - var_reversal_potentials__E_K) * 1.0;
    var_membrane__i_Kr = var_rapid_time_dependent_potassium_current__i_Kr;
    const double var_slow_time_dependent_potassium_current__i_Ks = 0.098 * pow(var_slow_time_dependent_potassium_current_Xs_gate__Xs, 2.0) * (var_membrane__V - (26.7137606597 * log(9.6 / (var_potassium_dynamics__K_i + (0.03 * var_sodium_dynamics__Na_i)))));
    var_membrane__i_Ks = var_slow_time_dependent_potassium_current__i_Ks;
    const double var_L_type_Ca_current__i_CaL = (((3.98e-05 * var_L_type_Ca_current_d_gate__d * var_L_type_Ca_current_f_gate__f * var_L_type_Ca_current_f2_gate__f2 * var_L_type_Ca_current_fCass_gate__fCass * 4.0 * (var_membrane__V - 15.0) * 9309421124.37) * 3.87974901066e-07) * ((0.25 * var_calcium_dynamics__Ca_ss * CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_12(_table_index_0, _factor_0)) - 2.0)) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_13(_table_index_0, _factor_0);
    var_membrane__i_CaL = var_L_type_Ca_current__i_CaL;
    const double var_sodium_potassium_pump_current__i_NaK = ((2.298375 * var_sodium_dynamics__Na_i) / (var_sodium_dynamics__Na_i + 40.0)) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_24(_table_index_0, _factor_0);
    var_membrane__i_NaK = var_sodium_potassium_pump_current__i_NaK;
    const double var_reversal_potentials__E_Na = 26.7137606597 * log(140.0 / var_sodium_dynamics__Na_i);
    const double var_fast_sodium_current__i_Na = 14.838 * pow(var_fast_sodium_current_m_gate__m, 3.0) * var_fast_sodium_current_h_gate__h * var_fast_sodium_current_j_gate__j * (var_membrane__V - var_reversal_potentials__E_Na);
    var_membrane__i_Na = var_fast_sodium_current__i_Na;
    const double var_sodium_background_current__i_b_Na = 0.00029 * (var_membrane__V - var_reversal_potentials__E_Na);
    var_membrane__i_b_Na = var_sodium_background_current__i_b_Na;
    const double var_sodium_calcium_exchanger_current__i_NaCa = (1000.0 * ((CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_25(_table_index_0, _factor_0) * pow(var_sodium_dynamics__Na_i, 3.0) * 2.0) - (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_26(_table_index_0, _factor_0) * 2744000.0 * var_calcium_dynamics__Ca_i * 2.5))) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_27(_table_index_0, _factor_0);
    var_membrane__i_NaCa = var_sodium_calcium_exchanger_current__i_NaCa;
    const double var_calcium_background_current__i_b_Ca = 0.000592 * (var_membrane__V - (13.3568803298 * log(2.0 / var_calcium_dynamics__Ca_i)));
    var_membrane__i_b_Ca = var_calcium_background_current__i_b_Ca;
    const double var_potassium_pump_current__i_p_K = (0.0146 * (var_membrane__V - var_reversal_potentials__E_K)) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_28(_table_index_0, _factor_0);
    var_membrane__i_p_K = var_potassium_pump_current__i_p_K;
    const double var_calcium_pump_current__i_p_Ca = (0.1238 * var_calcium_dynamics__Ca_i) / (var_calcium_dynamics__Ca_i + 0.0005);
    var_membrane__i_p_Ca = var_calcium_pump_current__i_p_Ca;
    var_membrane__i_Stim = ((var_environment__time >= 100.0) && (var_environment__time <= 100000.0) && (((var_environment__time - 100.0) - (floor((var_environment__time - 100.0) * 0.002) * 500.0)) <= 1.5)) ?  -52.0 : 0.0;
    const double var_calcium_dynamics__kcasr = 2.5 - (1.5 / (1.0 + pow(1.5 / var_calcium_dynamics__Ca_SR, 2.0)));
    const double var_calcium_dynamics__k1 = 0.15 / var_calcium_dynamics__kcasr;
    const double var_calcium_dynamics__i_rel = 0.102 * ((var_calcium_dynamics__k1 * pow(var_calcium_dynamics__Ca_ss, 2.0) * var_calcium_dynamics__R_prime) / (0.06 + (var_calcium_dynamics__k1 * pow(var_calcium_dynamics__Ca_ss, 2.0)))) * (var_calcium_dynamics__Ca_SR - var_calcium_dynamics__Ca_ss);
    const double var_calcium_dynamics__i_up = 0.006375 / (1.0 + (6.25e-08 / pow(var_calcium_dynamics__Ca_i, 2.0)));
    const double var_calcium_dynamics__i_leak = 0.00036 * (var_calcium_dynamics__Ca_SR - var_calcium_dynamics__Ca_i);
    const double var_calcium_dynamics__i_xfer = 0.0038 * (var_calcium_dynamics__Ca_ss - var_calcium_dynamics__Ca_i);
    
    const double d_dt_membrane__V = -(var_membrane__i_K1 + var_membrane__i_to + var_membrane__i_Kr + var_membrane__i_Ks + var_membrane__i_CaL + var_membrane__i_NaK + var_membrane__i_Na + var_membrane__i_b_Na + var_membrane__i_NaCa + var_membrane__i_b_Ca + var_membrane__i_p_K + var_membrane__i_p_Ca + var_membrane__i_Stim);
    const double d_dt_rapid_time_dependent_potassium_current_Xr1_gate__Xr1 = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_0(_table_index_0, _factor_0) - var_rapid_time_dependent_potassium_current_Xr1_gate__Xr1) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_1(_table_index_0, _factor_0);
    const double d_dt_rapid_time_dependent_potassium_current_Xr2_gate__Xr2 = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_2(_table_index_0, _factor_0) - var_rapid_time_dependent_potassium_current_Xr2_gate__Xr2) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_3(_table_index_0, _factor_0);
    const double d_dt_slow_time_dependent_potassium_current_Xs_gate__Xs = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_4(_table_index_0, _factor_0) - var_slow_time_dependent_potassium_current_Xs_gate__Xs) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_5(_table_index_0, _factor_0);
    const double d_dt_fast_sodium_current_m_gate__m = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_6(_table_index_0, _factor_0) - var_fast_sodium_current_m_gate__m) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_7(_table_index_0, _factor_0);
    const double d_dt_fast_sodium_current_h_gate__h = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_8(_table_index_0, _factor_0) - var_fast_sodium_current_h_gate__h) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_9(_table_index_0, _factor_0);
    const double d_dt_fast_sodium_current_j_gate__j = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_10(_table_index_0, _factor_0) - var_fast_sodium_current_j_gate__j) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_11(_table_index_0, _factor_0);
    const double d_dt_L_type_Ca_current_d_gate__d = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_14(_table_index_0, _factor_0) - var_L_type_Ca_current_d_gate__d) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_15(_table_index_0, _factor_0);
    const double d_dt_L_type_Ca_current_f_gate__f = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_16(_table_index_0, _factor_0) - var_L_type_Ca_current_f_gate__f) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_17(_table_index_0, _factor_0);
    const double d_dt_L_type_Ca_current_f2_gate__f2 = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_18(_table_index_0, _factor_0) - var_L_type_Ca_current_f2_gate__f2) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_19(_table_index_0, _factor_0);
    const double d_dt_L_type_Ca_current_fCass_gate__fCass = (((0.6 / (1.0 + pow(var_calcium_dynamics__Ca_ss * 20.0, 2.0))) + 0.4) - var_L_type_Ca_current_fCass_gate__fCass) / ((80.0 / (1.0 + pow(var_calcium_dynamics__Ca_ss * 20.0, 2.0))) + 2.0);
    const double d_dt_transient_outward_current_s_gate__s = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_20(_table_index_0, _factor_0) - var_transient_outward_current_s_gate__s) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_21(_table_index_0, _factor_0);
    const double d_dt_transient_outward_current_r_gate__r = (CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_22(_table_index_0, _factor_0) - var_transient_outward_current_r_gate__r) / CML_tentusscher_model_2006_M_pe_lut_LookupTables::Instance()->_lookup_23(_table_index_0, _factor_0);
    const double d_dt_calcium_dynamics__R_prime = ((-(0.045 * var_calcium_dynamics__kcasr)) * var_calcium_dynamics__Ca_ss * var_calcium_dynamics__R_prime) + (0.005 * (1.0 - var_calcium_dynamics__R_prime));
    const double d_dt_calcium_dynamics__Ca_i = (1.0 / (1.0 + (0.0002 / pow(var_calcium_dynamics__Ca_i + 0.001, 2.0)))) * (((((var_calcium_dynamics__i_leak - var_calcium_dynamics__i_up) * 0.001094) * 60.9607412826) + var_calcium_dynamics__i_xfer) - ((((var_calcium_background_current__i_b_Ca + var_calcium_pump_current__i_p_Ca) - (2.0 * var_sodium_calcium_exchanger_current__i_NaCa)) * 0.185) * 0.000315906749849));
    const double d_dt_calcium_dynamics__Ca_SR = (1.0 / (1.0 + (3.0 / pow(var_calcium_dynamics__Ca_SR + 0.3, 2.0)))) * (var_calcium_dynamics__i_up - (var_calcium_dynamics__i_rel + var_calcium_dynamics__i_leak));
    const double d_dt_calcium_dynamics__Ca_ss = (1.0 / (1.0 + (0.0001 / pow(var_calcium_dynamics__Ca_ss + 0.00025, 2.0)))) * (((((-var_L_type_Ca_current__i_CaL) * 0.185) * 0.0947720249546) + ((var_calcium_dynamics__i_rel * 0.001094) * 18288.2223848)) - ((var_calcium_dynamics__i_xfer * 0.016404) * 18288.2223848));
    const double d_dt_sodium_dynamics__Na_i = ((-(var_fast_sodium_current__i_Na + var_sodium_background_current__i_b_Na + (3.0 * var_sodium_potassium_pump_current__i_NaK) + (3.0 * var_sodium_calcium_exchanger_current__i_NaCa))) * 0.000631813499697) * 0.185;
    const double d_dt_potassium_dynamics__K_i = ((-((var_inward_rectifier_potassium_current__i_K1 + var_transient_outward_current__i_to + var_rapid_time_dependent_potassium_current__i_Kr + var_slow_time_dependent_potassium_current__i_Ks + var_potassium_pump_current__i_p_K + var_membrane__i_Stim) - (2.0 * var_sodium_potassium_pump_current__i_NaK))) * 0.000631813499697) * 0.185;
    
    classe->V_lado_direito_ = d_dt_membrane__V;
    classe->Xr1_lado_direito_ = d_dt_rapid_time_dependent_potassium_current_Xr1_gate__Xr1;
    classe->Xr2_lado_direito_ = d_dt_rapid_time_dependent_potassium_current_Xr2_gate__Xr2;
    classe->Xs_lado_direito_ = d_dt_slow_time_dependent_potassium_current_Xs_gate__Xs;
    classe->m_lado_direito_ = d_dt_fast_sodium_current_m_gate__m;
    classe->h_lado_direito_ = d_dt_fast_sodium_current_h_gate__h;
    classe->j_lado_direito_ = d_dt_fast_sodium_current_j_gate__j;
    classe->d_lado_direito_ = d_dt_L_type_Ca_current_d_gate__d;
    classe->f_lado_direito_ = d_dt_L_type_Ca_current_f_gate__f;
    classe->f2_lado_direito_ = d_dt_L_type_Ca_current_f2_gate__f2;
    classe->fCass_lado_direito_ = d_dt_L_type_Ca_current_fCass_gate__fCass;
    classe->s_lado_direito_ = d_dt_transient_outward_current_s_gate__s;
    classe->r_lado_direito_ = d_dt_transient_outward_current_r_gate__r;
    classe->Ca_i_lado_direito_ = d_dt_calcium_dynamics__Ca_i;
    classe->Ca_SR_lado_direito_ = d_dt_calcium_dynamics__Ca_SR;
    classe->Ca_ss_lado_direito_ = d_dt_calcium_dynamics__Ca_ss;
    classe->R_prime_lado_direito_ = d_dt_calcium_dynamics__R_prime;
    classe->Na_i_lado_direito_ = d_dt_sodium_dynamics__Na_i;
    classe->K_i_lado_direito_ = d_dt_potassium_dynamics__K_i;
};


#endif
