#ifndef _CML_noble_varghese_kohl_noble_1998_basic_lut_
#define _CML_noble_varghese_kohl_noble_1998_basic_lut_

//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: noble_varghese_kohl_noble_1998_basic
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translate: 1844, pycml: 1844)
//! on Sat Jul 30 00:33:44 2011
//! 
//! <autogenerated>



class CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables
{
public:
    static CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables* Instance()
    {
        if (mpInstance == NULL)
        {
            mpInstance = new CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables;
        }
        return mpInstance;
    }
    
    // Methods to look up values from lookup tables
    // using linear interpolation
    inline double _lookup_0(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][0];
        double y2 = _lookup_table_0[i+1][0];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_1(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][1];
        double y2 = _lookup_table_0[i+1][1];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_2(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][2];
        double y2 = _lookup_table_0[i+1][2];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_3(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][3];
        double y2 = _lookup_table_0[i+1][3];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_4(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][4];
        double y2 = _lookup_table_0[i+1][4];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_5(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][5];
        double y2 = _lookup_table_0[i+1][5];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_6(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][6];
        double y2 = _lookup_table_0[i+1][6];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_7(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][7];
        double y2 = _lookup_table_0[i+1][7];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_8(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][8];
        double y2 = _lookup_table_0[i+1][8];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_9(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][9];
        double y2 = _lookup_table_0[i+1][9];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_10(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][10];
        double y2 = _lookup_table_0[i+1][10];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_11(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][11];
        double y2 = _lookup_table_0[i+1][11];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_12(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][12];
        double y2 = _lookup_table_0[i+1][12];
        return y1 + (y2-y1)*factor;
    }
    
    inline double _lookup_13(unsigned i, double factor)
    {
        double y1 = _lookup_table_0[i][13];
        double y2 = _lookup_table_0[i+1][13];
        return y1 + (y2-y1)*factor;
    }
    
    
protected:
    CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables(const CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables&);
    CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables& operator= (const CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables&);
    CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables()
    {
        for (int i=0 ; i<16001; i++)
        {
            double var_rapid_delayed_rectifier_potassium_current__V = -100.0001 + i*0.01;
            _lookup_table_0[i][0] = 1.0 + exp((var_rapid_delayed_rectifier_potassium_current__V + 9.0) / 22.4);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_rapid_delayed_rectifier_potassium_current_xr1_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][1] = 50.0 / (1.0 + exp((-(var_rapid_delayed_rectifier_potassium_current_xr1_gate__V - 5.0)) / 9.0));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_rapid_delayed_rectifier_potassium_current_xr1_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][2] = 0.05 * exp((-(var_rapid_delayed_rectifier_potassium_current_xr1_gate__V - 20.0)) / 15.0);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_rapid_delayed_rectifier_potassium_current_xr2_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][3] = 50.0 / (1.0 + exp((-(var_rapid_delayed_rectifier_potassium_current_xr2_gate__V - 5.0)) / 9.0));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_rapid_delayed_rectifier_potassium_current_xr2_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][4] = 0.4 * exp(-pow((var_rapid_delayed_rectifier_potassium_current_xr2_gate__V + 30.0) / 30.0, 3.0));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_slow_delayed_rectifier_potassium_current_xs_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][5] = 14.0 / (1.0 + exp((-(var_slow_delayed_rectifier_potassium_current_xs_gate__V - 40.0)) / 9.0));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_slow_delayed_rectifier_potassium_current_xs_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][6] = 1.0 * exp((-var_slow_delayed_rectifier_potassium_current_xs_gate__V) / 45.0);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_fast_sodium_current_m_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][7] = 8000.0 * exp((-0.056) * (var_fast_sodium_current_m_gate__V + 66.0));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_persistent_sodium_current__V = -100.0001 + i*0.01;
            _lookup_table_0[i][8] = 1.0 + exp((-(var_persistent_sodium_current__V + 52.0)) / 8.0);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_L_type_Ca_channel_f_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][9] = 12.0 / (1.0 + exp(((-1.0) * (var_L_type_Ca_channel_f_gate__V + 34.0)) / 4.0));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_transient_outward_current_s_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][10] = 0.033 * exp((-var_transient_outward_current_s_gate__V) / 17.0);
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_transient_outward_current_s_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][11] = 33.0 / (1.0 + exp((-0.125) * (var_transient_outward_current_s_gate__V + 10.0)));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_transient_outward_current_r_gate__V = -100.0001 + i*0.01;
            _lookup_table_0[i][12] = 1.0 / (1.0 + exp((-(var_transient_outward_current_r_gate__V + 4.0)) / 5.0));
        }
        
        for (int i=0 ; i<16001; i++)
        {
            double var_calcium_release__V = -100.0001 + i*0.01;
            _lookup_table_0[i][13] = exp(0.08 * (var_calcium_release__V - 40.0));
        }
        
    }
    
private:
    /** The single instance of the class */
    static CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables *mpInstance;

    // Lookup tables
    double _lookup_table_0[16001][14];
    
};

CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables* CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::mpInstance = NULL;

void __equation__lut_(Solveode *classe)
{
    // Inputs:
    // Time units: second
    double var_environment__time= classe->time_new;
    double var_membrane__V = classe->V_old_; //var_membrane
    // Units: millivolt; Initial value: -92.849333
    double var_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1 = classe->xr1_old_; //var_rapid_delayed_rectifier_potassium_current_xr1_gate
    // Units: dimensionless; Initial value: 1.03e-5
    double var_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2 = classe->xr2_old_; //var_rapid_delayed_rectifier_potassium_current_xr2_gate
    // Units: dimensionless; Initial value: 2e-7
    double var_slow_delayed_rectifier_potassium_current_xs_gate__xs = classe->xs_old_; //var_slow_delayed_rectifier_potassium_current_xs_gate
    // Units: dimensionless; Initial value: 0.001302
    double var_fast_sodium_current_m_gate__m = classe->m_old_; //var_fast_sodium_current_m_gate
    // Units: dimensionless; Initial value: 0.0016203
    double var_fast_sodium_current_h_gate__h = classe->h_old_; //var_fast_sodium_current_h_gate
    // Units: dimensionless; Initial value: 0.9944036
    double var_L_type_Ca_channel_d_gate__d = classe->d_old_; //var_L_type_Ca_channel_d_gate
    // Units: dimensionless; Initial value: 0
    double var_L_type_Ca_channel_f_gate__f = classe->f_old_; //var_L_type_Ca_channel_f_gate
    // Units: dimensionless; Initial value: 1
    double var_L_type_Ca_channel_f2_gate__f2 = classe->f2_old_; //var_L_type_Ca_channel_f2_gate
    // Units: dimensionless; Initial value: 0.9349197
    double var_L_type_Ca_channel_f2ds_gate__f2ds = classe->f2ds_old_; //var_L_type_Ca_channel_f2ds_gate
    // Units: dimensionless; Initial value: 0.9651958
    double var_transient_outward_current_s_gate__s = classe->s_old_; //var_transient_outward_current_s_gate
    // Units: dimensionless; Initial value: 0.9948645
    double var_transient_outward_current_r_gate__r = classe->r_old_; //var_transient_outward_current_r_gate
    // Units: dimensionless; Initial value: 0
    double var_calcium_release__ActFrac = classe->ActFrac_old_; //var_calcium_release
    // Units: dimensionless; Initial value: 0.0042614
    double var_calcium_release__ProdFrac = classe->ProdFrac_old_; //var_calcium_release
    // Units: dimensionless; Initial value: 0.4068154
    double var_intracellular_sodium_concentration__Na_i = classe->Na_i_old_; //var_intracellular_sodium_concentration
    // Units: millimolar; Initial value: 7.3321223
    double var_intracellular_potassium_concentration__K_i = classe->K_i_old_; //var_intracellular_potassium_concentration
    // Units: millimolar; Initial value: 136.5644281
    double var_intracellular_calcium_concentration__Ca_i = classe->Ca_i_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 1.4e-5
    double var_intracellular_calcium_concentration__Ca_ds = classe->Ca_ds_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 1.88e-5
    double var_intracellular_calcium_concentration__Ca_up = classe->Ca_up_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 0.4531889
    double var_intracellular_calcium_concentration__Ca_rel = classe->Ca_rel_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 0.4481927
    double var_intracellular_calcium_concentration__Ca_Calmod = classe->Ca_Calmod_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 0.0005555
    double var_intracellular_calcium_concentration__Ca_Trop = classe->Ca_Trop_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 0.0003542
    
    
    // Lookup table indexing
    if (var_membrane__V>59.9999 || var_membrane__V<-100.0001)
    {
#define COVERAGE_IGNORE
        printf("V outside lookup table range");
#undef COVERAGE_IGNORE
    }
    
    double _offset_0 = var_membrane__V - -100.0001;
    double _offset_0_over_table_step = _offset_0 * 100.0;
    unsigned _table_index_0 = (unsigned)(_offset_0_over_table_step);
    double _factor_0 = _offset_0_over_table_step - _table_index_0;
    
    // Mathematics
    const double var_membrane__R = 8314.472;
    const double var_membrane__T = 310.0;
    const double var_membrane__F = 96485.3415;
    const double var_membrane__Cm = 9.5e-05;
    const double var_membrane__time = var_environment__time;
    const double var_reversal_potentials__K_i = var_intracellular_potassium_concentration__K_i;
    const double var_reversal_potentials__R = var_membrane__R;
    const double var_reversal_potentials__T = var_membrane__T;
    const double var_reversal_potentials__F = var_membrane__F;
    const double var_extracellular_potassium_concentration__K_o = 4.0;
    const double var_reversal_potentials__K_o = var_extracellular_potassium_concentration__K_o;
    const double var_reversal_potentials__E_K = ((var_reversal_potentials__R * var_reversal_potentials__T) / var_reversal_potentials__F) * log(var_reversal_potentials__K_o / var_reversal_potentials__K_i);
    const double var_time_independent_potassium_current__E_K = var_reversal_potentials__E_K;
    const double var_time_independent_potassium_current__K_o = var_extracellular_potassium_concentration__K_o;
    const double var_time_independent_potassium_current__R = var_membrane__R;
    const double var_time_independent_potassium_current__V = var_membrane__V;
    const double var_time_independent_potassium_current__T = var_membrane__T;
    const double var_time_independent_potassium_current__K_mk1 = 10.0;
    const double var_time_independent_potassium_current__g_K1 = 0.5;
    const double var_time_independent_potassium_current__F = var_membrane__F;
    const double var_time_independent_potassium_current__i_K1 = (((var_time_independent_potassium_current__g_K1 * var_time_independent_potassium_current__K_o) / (var_time_independent_potassium_current__K_o + var_time_independent_potassium_current__K_mk1)) * (var_time_independent_potassium_current__V - var_time_independent_potassium_current__E_K)) / (1.0 + exp((((var_time_independent_potassium_current__V - var_time_independent_potassium_current__E_K) - 10.0) * var_time_independent_potassium_current__F * 1.25) / (var_time_independent_potassium_current__R * var_time_independent_potassium_current__T)));
    const double var_membrane__i_K1 = var_time_independent_potassium_current__i_K1;
    const double var_transient_outward_current__s = var_transient_outward_current_s_gate__s;
    const double var_transient_outward_current__r = var_transient_outward_current_r_gate__r;
    const double var_transient_outward_current__g_to = 0.005;
    const double var_transient_outward_current__V = var_membrane__V;
    const double var_transient_outward_current__E_K = var_reversal_potentials__E_K;
    const double var_transient_outward_current__g_tos = 0.0;
    const double var_transient_outward_current__i_to = var_transient_outward_current__g_to * (var_transient_outward_current__g_tos + (var_transient_outward_current__s * (1.0 - var_transient_outward_current__g_tos))) * var_transient_outward_current__r * (var_transient_outward_current__V - var_transient_outward_current__E_K);
    const double var_membrane__i_to = var_transient_outward_current__i_to;
    const double var_rapid_delayed_rectifier_potassium_current__g_Kr2 = 0.0013;
    const double var_rapid_delayed_rectifier_potassium_current__g_Kr1 = 0.0021;
    const double var_rapid_delayed_rectifier_potassium_current__xr1 = var_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1;
    const double var_rapid_delayed_rectifier_potassium_current__xr2 = var_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2;
    const double var_rapid_delayed_rectifier_potassium_current__V = var_membrane__V;
    const double var_rapid_delayed_rectifier_potassium_current__E_K = var_reversal_potentials__E_K;
    const double var_rapid_delayed_rectifier_potassium_current__i_Kr = ((((var_rapid_delayed_rectifier_potassium_current__g_Kr1 * var_rapid_delayed_rectifier_potassium_current__xr1) + (var_rapid_delayed_rectifier_potassium_current__g_Kr2 * var_rapid_delayed_rectifier_potassium_current__xr2)) * 1.0) / CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_0(_table_index_0, _factor_0)) * (var_rapid_delayed_rectifier_potassium_current__V - var_rapid_delayed_rectifier_potassium_current__E_K);
    const double var_membrane__i_Kr = var_rapid_delayed_rectifier_potassium_current__i_Kr;
    const double var_slow_delayed_rectifier_potassium_current__xs = var_slow_delayed_rectifier_potassium_current_xs_gate__xs;
    const double var_extracellular_sodium_concentration__Na_o = 140.0;
    const double var_reversal_potentials__Na_o = var_extracellular_sodium_concentration__Na_o;
    const double var_reversal_potentials__Na_i = var_intracellular_sodium_concentration__Na_i;
    const double var_reversal_potentials__P_kna = 0.03;
    const double var_reversal_potentials__E_Ks = ((var_reversal_potentials__R * var_reversal_potentials__T) / var_reversal_potentials__F) * log((var_reversal_potentials__K_o + (var_reversal_potentials__P_kna * var_reversal_potentials__Na_o)) / (var_reversal_potentials__K_i + (var_reversal_potentials__P_kna * var_reversal_potentials__Na_i)));
    const double var_slow_delayed_rectifier_potassium_current__E_Ks = var_reversal_potentials__E_Ks;
    const double var_slow_delayed_rectifier_potassium_current__g_Ks = 0.0026;
    const double var_slow_delayed_rectifier_potassium_current__V = var_membrane__V;
    const double var_slow_delayed_rectifier_potassium_current__i_Ks = var_slow_delayed_rectifier_potassium_current__g_Ks * pow(var_slow_delayed_rectifier_potassium_current__xs, 2.0) * (var_slow_delayed_rectifier_potassium_current__V - var_slow_delayed_rectifier_potassium_current__E_Ks);
    const double var_membrane__i_Ks = var_slow_delayed_rectifier_potassium_current__i_Ks;
    const double var_L_type_Ca_channel__d = var_L_type_Ca_channel_d_gate__d;
    const double var_L_type_Ca_channel__FrICa = 1.0;
    const double var_L_type_Ca_channel__f = var_L_type_Ca_channel_f_gate__f;
    const double var_L_type_Ca_channel__K_o = var_extracellular_potassium_concentration__K_o;
    const double var_L_type_Ca_channel__K_i = var_intracellular_potassium_concentration__K_i;
    const double var_L_type_Ca_channel__F = var_membrane__F;
    const double var_L_type_Ca_channel__P_Ca_L = 0.1;
    const double var_L_type_Ca_channel__T = var_membrane__T;
    const double var_L_type_Ca_channel__P_CaK = 0.002;
    const double var_L_type_Ca_channel__V = var_membrane__V;
    const double var_L_type_Ca_channel__f2 = var_L_type_Ca_channel_f2_gate__f2;
    const double var_L_type_Ca_channel__R = var_membrane__R;
    const double var_L_type_Ca_channel__i_Ca_L_K_cyt = ((((1.0 - var_L_type_Ca_channel__FrICa) * var_L_type_Ca_channel__P_CaK * var_L_type_Ca_channel__P_Ca_L * var_L_type_Ca_channel__d * var_L_type_Ca_channel__f * var_L_type_Ca_channel__f2 * (var_L_type_Ca_channel__V - 50.0) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)) / (1.0 - exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)))) * ((var_L_type_Ca_channel__K_i * exp((50.0 * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))) - (var_L_type_Ca_channel__K_o * exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))));
    const double var_membrane__i_Ca_L_K_cyt = var_L_type_Ca_channel__i_Ca_L_K_cyt;
    const double var_L_type_Ca_channel__f2ds = var_L_type_Ca_channel_f2ds_gate__f2ds;
    const double var_L_type_Ca_channel__i_Ca_L_K_ds = (((var_L_type_Ca_channel__FrICa * var_L_type_Ca_channel__P_CaK * var_L_type_Ca_channel__P_Ca_L * var_L_type_Ca_channel__d * var_L_type_Ca_channel__f * var_L_type_Ca_channel__f2ds * (var_L_type_Ca_channel__V - 50.0) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)) / (1.0 - exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)))) * ((var_L_type_Ca_channel__K_i * exp((50.0 * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))) - (var_L_type_Ca_channel__K_o * exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))));
    const double var_membrane__i_Ca_L_K_ds = var_L_type_Ca_channel__i_Ca_L_K_ds;
    const double var_sodium_potassium_pump__i_NaK_max = 0.7;
    const double var_sodium_potassium_pump__Na_i = var_intracellular_sodium_concentration__Na_i;
    const double var_sodium_potassium_pump__K_o = var_extracellular_potassium_concentration__K_o;
    const double var_sodium_potassium_pump__K_mNa = 40.0;
    const double var_sodium_potassium_pump__K_mK = 1.0;
    const double var_sodium_potassium_pump__i_NaK = (((var_sodium_potassium_pump__i_NaK_max * var_sodium_potassium_pump__K_o) / (var_sodium_potassium_pump__K_mK + var_sodium_potassium_pump__K_o)) * var_sodium_potassium_pump__Na_i) / (var_sodium_potassium_pump__K_mNa + var_sodium_potassium_pump__Na_i);
    const double var_membrane__i_NaK = var_sodium_potassium_pump__i_NaK;
    const double var_fast_sodium_current__g_Na = 2.5;
    const double var_fast_sodium_current__h = var_fast_sodium_current_h_gate__h;
    const double var_fast_sodium_current__V = var_membrane__V;
    const double var_reversal_potentials__E_mh = ((var_reversal_potentials__R * var_reversal_potentials__T) / var_reversal_potentials__F) * log((var_reversal_potentials__Na_o + (0.12 * var_reversal_potentials__K_o)) / (var_reversal_potentials__Na_i + (0.12 * var_reversal_potentials__K_i)));
    const double var_fast_sodium_current__E_mh = var_reversal_potentials__E_mh;
    const double var_fast_sodium_current__m = var_fast_sodium_current_m_gate__m;
    const double var_fast_sodium_current__i_Na = var_fast_sodium_current__g_Na * pow(var_fast_sodium_current__m, 3.0) * var_fast_sodium_current__h * (var_fast_sodium_current__V - var_fast_sodium_current__E_mh);
    const double var_membrane__i_Na = var_fast_sodium_current__i_Na;
    const double var_sodium_background_current__V = var_membrane__V;
    const double var_reversal_potentials__E_Na = ((var_reversal_potentials__R * var_reversal_potentials__T) / var_reversal_potentials__F) * log(var_reversal_potentials__Na_o / var_reversal_potentials__Na_i);
    const double var_sodium_background_current__E_Na = var_reversal_potentials__E_Na;
    const double var_sodium_background_current__g_bna = 0.0006;
    const double var_sodium_background_current__i_b_Na = var_sodium_background_current__g_bna * (var_sodium_background_current__V - var_sodium_background_current__E_Na);
    const double var_membrane__i_b_Na = var_sodium_background_current__i_b_Na;
    const double var_persistent_sodium_current__g_pna = 0.004;
    const double var_persistent_sodium_current__V = var_membrane__V;
    const double var_persistent_sodium_current__E_Na = var_reversal_potentials__E_Na;
    const double var_persistent_sodium_current__i_p_Na = ((var_persistent_sodium_current__g_pna * 1.0) / CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_8(_table_index_0, _factor_0)) * (var_persistent_sodium_current__V - var_persistent_sodium_current__E_Na);
    const double var_membrane__i_p_Na = var_persistent_sodium_current__i_p_Na;
    const double var_L_type_Ca_channel__P_CaNa = 0.01;
    const double var_L_type_Ca_channel__Na_o = var_extracellular_sodium_concentration__Na_o;
    const double var_L_type_Ca_channel__Na_i = var_intracellular_sodium_concentration__Na_i;
    const double var_L_type_Ca_channel__i_Ca_L_Na_cyt = ((((1.0 - var_L_type_Ca_channel__FrICa) * var_L_type_Ca_channel__P_CaNa * var_L_type_Ca_channel__P_Ca_L * var_L_type_Ca_channel__d * var_L_type_Ca_channel__f * var_L_type_Ca_channel__f2 * (var_L_type_Ca_channel__V - 50.0) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)) / (1.0 - exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)))) * ((var_L_type_Ca_channel__Na_i * exp((50.0 * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))) - (var_L_type_Ca_channel__Na_o * exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))));
    const double var_membrane__i_Ca_L_Na_cyt = var_L_type_Ca_channel__i_Ca_L_Na_cyt;
    const double var_L_type_Ca_channel__i_Ca_L_Na_ds = (((var_L_type_Ca_channel__FrICa * var_L_type_Ca_channel__P_CaNa * var_L_type_Ca_channel__P_Ca_L * var_L_type_Ca_channel__d * var_L_type_Ca_channel__f * var_L_type_Ca_channel__f2ds * (var_L_type_Ca_channel__V - 50.0) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)) / (1.0 - exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)))) * ((var_L_type_Ca_channel__Na_i * exp((50.0 * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))) - (var_L_type_Ca_channel__Na_o * exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))));
    const double var_membrane__i_Ca_L_Na_ds = var_L_type_Ca_channel__i_Ca_L_Na_ds;
    const double var_sodium_calcium_exchanger__Na_i = var_intracellular_sodium_concentration__Na_i;
    const double var_sodium_calcium_exchanger__n_NaCa = 3.0;
    const double var_sodium_calcium_exchanger__gamma = 0.5;
    const double var_sodium_calcium_exchanger__F = var_membrane__F;
    const double var_sodium_calcium_exchanger__Na_o = var_extracellular_sodium_concentration__Na_o;
    const double var_sodium_calcium_exchanger__FRiNaCa = 0.001;
    const double var_sodium_calcium_exchanger__R = var_membrane__R;
    const double var_sodium_calcium_exchanger__Ca_i = var_intracellular_calcium_concentration__Ca_i;
    const double var_sodium_calcium_exchanger__T = var_membrane__T;
    const double var_sodium_calcium_exchanger__V = var_membrane__V;
    const double var_sodium_calcium_exchanger__d_NaCa = 0.0;
    const double var_extracellular_calcium_concentration__Ca_o = 2.0;
    const double var_sodium_calcium_exchanger__Ca_o = var_extracellular_calcium_concentration__Ca_o;
    const double var_sodium_calcium_exchanger__k_NaCa = 0.0005;
    const double var_sodium_calcium_exchanger__i_NaCa_cyt = ((1.0 - var_sodium_calcium_exchanger__FRiNaCa) * var_sodium_calcium_exchanger__k_NaCa * ((exp((var_sodium_calcium_exchanger__gamma * (var_sodium_calcium_exchanger__n_NaCa - 2.0) * var_sodium_calcium_exchanger__V * var_sodium_calcium_exchanger__F) / (var_sodium_calcium_exchanger__R * var_sodium_calcium_exchanger__T)) * pow(var_sodium_calcium_exchanger__Na_i, var_sodium_calcium_exchanger__n_NaCa) * var_sodium_calcium_exchanger__Ca_o) - (exp(((var_sodium_calcium_exchanger__gamma - 1.0) * (var_sodium_calcium_exchanger__n_NaCa - 2.0) * var_sodium_calcium_exchanger__V * var_sodium_calcium_exchanger__F) / (var_sodium_calcium_exchanger__R * var_sodium_calcium_exchanger__T)) * pow(var_sodium_calcium_exchanger__Na_o, var_sodium_calcium_exchanger__n_NaCa) * var_sodium_calcium_exchanger__Ca_i))) / ((1.0 + (var_sodium_calcium_exchanger__d_NaCa * ((var_sodium_calcium_exchanger__Ca_i * pow(var_sodium_calcium_exchanger__Na_o, var_sodium_calcium_exchanger__n_NaCa)) + (var_sodium_calcium_exchanger__Ca_o * pow(var_sodium_calcium_exchanger__Na_i, var_sodium_calcium_exchanger__n_NaCa))))) * (1.0 + (var_sodium_calcium_exchanger__Ca_i / 0.0069)));
    const double var_membrane__i_NaCa_cyt = var_sodium_calcium_exchanger__i_NaCa_cyt;
    const double var_sodium_calcium_exchanger__Ca_ds = var_intracellular_calcium_concentration__Ca_ds;
    const double var_sodium_calcium_exchanger__i_NaCa_ds = (var_sodium_calcium_exchanger__FRiNaCa * var_sodium_calcium_exchanger__k_NaCa * ((exp((var_sodium_calcium_exchanger__gamma * (var_sodium_calcium_exchanger__n_NaCa - 2.0) * var_sodium_calcium_exchanger__V * var_sodium_calcium_exchanger__F) / (var_sodium_calcium_exchanger__R * var_sodium_calcium_exchanger__T)) * pow(var_sodium_calcium_exchanger__Na_i, var_sodium_calcium_exchanger__n_NaCa) * var_sodium_calcium_exchanger__Ca_o) - (exp(((var_sodium_calcium_exchanger__gamma - 1.0) * (var_sodium_calcium_exchanger__n_NaCa - 2.0) * var_sodium_calcium_exchanger__V * var_sodium_calcium_exchanger__F) / (var_sodium_calcium_exchanger__R * var_sodium_calcium_exchanger__T)) * pow(var_sodium_calcium_exchanger__Na_o, var_sodium_calcium_exchanger__n_NaCa) * var_sodium_calcium_exchanger__Ca_ds))) / ((1.0 + (var_sodium_calcium_exchanger__d_NaCa * ((var_sodium_calcium_exchanger__Ca_ds * pow(var_sodium_calcium_exchanger__Na_o, var_sodium_calcium_exchanger__n_NaCa)) + (var_sodium_calcium_exchanger__Ca_o * pow(var_sodium_calcium_exchanger__Na_i, var_sodium_calcium_exchanger__n_NaCa))))) * (1.0 + (var_sodium_calcium_exchanger__Ca_ds / 0.0069)));
    const double var_membrane__i_NaCa_ds = var_sodium_calcium_exchanger__i_NaCa_ds;
    const double var_L_type_Ca_channel__Ca_i = var_intracellular_calcium_concentration__Ca_i;
    const double var_L_type_Ca_channel__Ca_o = var_extracellular_calcium_concentration__Ca_o;
    const double var_L_type_Ca_channel__i_Ca_L_Ca_cyt = ((((1.0 - var_L_type_Ca_channel__FrICa) * 4.0 * var_L_type_Ca_channel__P_Ca_L * var_L_type_Ca_channel__d * var_L_type_Ca_channel__f * var_L_type_Ca_channel__f2 * (var_L_type_Ca_channel__V - 50.0) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)) / (1.0 - exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F * 2.0) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)))) * ((var_L_type_Ca_channel__Ca_i * exp((100.0 * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))) - (var_L_type_Ca_channel__Ca_o * exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F * 2.0) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))));
    const double var_membrane__i_Ca_L_Ca_cyt = var_L_type_Ca_channel__i_Ca_L_Ca_cyt;
    const double var_L_type_Ca_channel__i_Ca_L_Ca_ds = (((var_L_type_Ca_channel__FrICa * 4.0 * var_L_type_Ca_channel__P_Ca_L * var_L_type_Ca_channel__d * var_L_type_Ca_channel__f * var_L_type_Ca_channel__f2ds * (var_L_type_Ca_channel__V - 50.0) * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)) / (1.0 - exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F * 2.0) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T)))) * ((var_L_type_Ca_channel__Ca_i * exp((100.0 * var_L_type_Ca_channel__F) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))) - (var_L_type_Ca_channel__Ca_o * exp(((-(var_L_type_Ca_channel__V - 50.0)) * var_L_type_Ca_channel__F * 2.0) / (var_L_type_Ca_channel__R * var_L_type_Ca_channel__T))));
    const double var_membrane__i_Ca_L_Ca_ds = var_L_type_Ca_channel__i_Ca_L_Ca_ds;
    const double var_reversal_potentials__Ca_o = var_extracellular_calcium_concentration__Ca_o;
    const double var_reversal_potentials__Ca_i = var_intracellular_calcium_concentration__Ca_i;
    const double var_reversal_potentials__E_Ca = ((0.5 * var_reversal_potentials__R * var_reversal_potentials__T) / var_reversal_potentials__F) * log(var_reversal_potentials__Ca_o / var_reversal_potentials__Ca_i);
    const double var_calcium_background_current__E_Ca = var_reversal_potentials__E_Ca;
    const double var_calcium_background_current__g_bca = 0.00025;
    const double var_calcium_background_current__V = var_membrane__V;
    const double var_calcium_background_current__i_b_Ca = var_calcium_background_current__g_bca * (var_calcium_background_current__V - var_calcium_background_current__E_Ca);
    const double var_membrane__i_b_Ca = var_calcium_background_current__i_b_Ca;
    const double var_membrane__stim_end = 100000.0;
    const double var_membrane__stim_amplitude =  -6.0;
    const double var_membrane__stim_duration = 0.0015;
    const double var_membrane__stim_period = 1.0;
    const double var_membrane__stim_start = 0.1;
    const double var_membrane__i_Stim = ((var_membrane__time >= var_membrane__stim_start) && (var_membrane__time <= var_membrane__stim_end) && (((var_membrane__time - var_membrane__stim_start) - (floor((var_membrane__time - var_membrane__stim_start) / var_membrane__stim_period) * var_membrane__stim_period)) <= var_membrane__stim_duration)) ? var_membrane__stim_amplitude : 0.0;
    const double var_rapid_delayed_rectifier_potassium_current_xr1_gate__V = var_rapid_delayed_rectifier_potassium_current__V;
    const double var_rapid_delayed_rectifier_potassium_current_xr1_gate__alpha_xr1 = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_1(_table_index_0, _factor_0);
    const double var_rapid_delayed_rectifier_potassium_current_xr1_gate__beta_xr1 = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_2(_table_index_0, _factor_0);
    const double var_rapid_delayed_rectifier_potassium_current_xr2_gate__V = var_rapid_delayed_rectifier_potassium_current__V;
    const double var_rapid_delayed_rectifier_potassium_current_xr2_gate__alpha_xr2 = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_3(_table_index_0, _factor_0);
    const double var_rapid_delayed_rectifier_potassium_current_xr2_gate__beta_xr2 = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_4(_table_index_0, _factor_0);
    const double var_slow_delayed_rectifier_potassium_current_xs_gate__V = var_slow_delayed_rectifier_potassium_current__V;
    const double var_slow_delayed_rectifier_potassium_current_xs_gate__alpha_xs = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_5(_table_index_0, _factor_0);
    const double var_slow_delayed_rectifier_potassium_current_xs_gate__beta_xs = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_6(_table_index_0, _factor_0);
    const double var_fast_sodium_current_m_gate__V = var_fast_sodium_current__V;
    const double var_fast_sodium_current_m_gate__E0_m = var_fast_sodium_current_m_gate__V + 41.0;
    const double var_fast_sodium_current_m_gate__delta_m = 1e-05;
    const double var_fast_sodium_current_m_gate__alpha_m = (fabs(var_fast_sodium_current_m_gate__E0_m) < var_fast_sodium_current_m_gate__delta_m) ? 2000.0 : ((200.0 * var_fast_sodium_current_m_gate__E0_m) / (1.0 - exp((-0.1) * var_fast_sodium_current_m_gate__E0_m)));
    const double var_fast_sodium_current_m_gate__beta_m = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_7(_table_index_0, _factor_0);
    const double var_fast_sodium_current_h_gate__V = var_fast_sodium_current__V;
    const double var_fast_sodium_current_h_gate__shift_h = 0.0;
    const double var_fast_sodium_current_h_gate__alpha_h = 20.0 * exp((-0.125) * ((var_fast_sodium_current_h_gate__V + 75.0) - var_fast_sodium_current_h_gate__shift_h));
    const double var_fast_sodium_current_h_gate__beta_h = 2000.0 / (1.0 + (320.0 * exp((-0.1) * ((var_fast_sodium_current_h_gate__V + 75.0) - var_fast_sodium_current_h_gate__shift_h))));
    const double var_L_type_Ca_channel__Ca_ds = var_intracellular_calcium_concentration__Ca_ds;
    const double var_L_type_Ca_channel__Km_f2 = 100000.0;
    const double var_L_type_Ca_channel__Km_f2ds = 0.001;
    const double var_L_type_Ca_channel__R_decay = 20.0;
    const double var_L_type_Ca_channel_d_gate__V = var_L_type_Ca_channel__V;
    const double var_L_type_Ca_channel_d_gate__E0_d = (var_L_type_Ca_channel_d_gate__V + 24.0) - 5.0;
    const double var_L_type_Ca_channel_d_gate__alpha_d = (fabs(var_L_type_Ca_channel_d_gate__E0_d) < 0.0001) ? 120.0 : ((30.0 * var_L_type_Ca_channel_d_gate__E0_d) / (1.0 - exp((-var_L_type_Ca_channel_d_gate__E0_d) / 4.0)));
    const double var_L_type_Ca_channel_d_gate__beta_d = (fabs(var_L_type_Ca_channel_d_gate__E0_d) < 0.0001) ? 120.0 : ((12.0 * var_L_type_Ca_channel_d_gate__E0_d) / (exp(var_L_type_Ca_channel_d_gate__E0_d / 10.0) - 1.0));
    const double var_L_type_Ca_channel_d_gate__speed_d = 3.0;
    const double var_L_type_Ca_channel_f_gate__V = var_L_type_Ca_channel__V;
    const double var_L_type_Ca_channel_f_gate__E0_f = var_L_type_Ca_channel_f_gate__V + 34.0;
    const double var_L_type_Ca_channel_f_gate__delta_f = 0.0001;
    const double var_L_type_Ca_channel_f_gate__alpha_f = (fabs(var_L_type_Ca_channel_f_gate__E0_f) < var_L_type_Ca_channel_f_gate__delta_f) ? 25.0 : ((6.25 * var_L_type_Ca_channel_f_gate__E0_f) / (exp(var_L_type_Ca_channel_f_gate__E0_f / 4.0) - 1.0));
    const double var_L_type_Ca_channel_f_gate__beta_f = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_9(_table_index_0, _factor_0);
    const double var_L_type_Ca_channel_f_gate__speed_f = 0.3;
    const double var_L_type_Ca_channel_f2_gate__Km_f2 = var_L_type_Ca_channel__Km_f2;
    const double var_L_type_Ca_channel_f2_gate__Ca_i = var_L_type_Ca_channel__Ca_i;
    const double var_L_type_Ca_channel_f2ds_gate__Km_f2ds = var_L_type_Ca_channel__Km_f2ds;
    const double var_L_type_Ca_channel_f2ds_gate__R_decay = var_L_type_Ca_channel__R_decay;
    const double var_L_type_Ca_channel_f2ds_gate__Ca_ds = var_L_type_Ca_channel__Ca_ds;
    const double var_transient_outward_current_s_gate__V = var_transient_outward_current__V;
    const double var_transient_outward_current_s_gate__alpha_s = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_10(_table_index_0, _factor_0);
    const double var_transient_outward_current_s_gate__beta_s = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_11(_table_index_0, _factor_0);
    const double var_transient_outward_current_r_gate__V = var_transient_outward_current__V;
    const double var_sarcoplasmic_reticulum_calcium_pump__Ca_i = var_intracellular_calcium_concentration__Ca_i;
    const double var_sarcoplasmic_reticulum_calcium_pump__Ca_up = var_intracellular_calcium_concentration__Ca_up;
    const double var_sarcoplasmic_reticulum_calcium_pump__alpha_up = 0.4;
    const double var_sarcoplasmic_reticulum_calcium_pump__beta_up = 0.03;
    const double var_sarcoplasmic_reticulum_calcium_pump__K_srca = 0.5;
    const double var_sarcoplasmic_reticulum_calcium_pump__K_xcs = 0.4;
    const double var_sarcoplasmic_reticulum_calcium_pump__K_cyca = 0.0003;
    const double var_sarcoplasmic_reticulum_calcium_pump__K_1 = (var_sarcoplasmic_reticulum_calcium_pump__K_cyca * var_sarcoplasmic_reticulum_calcium_pump__K_xcs) / var_sarcoplasmic_reticulum_calcium_pump__K_srca;
    const double var_sarcoplasmic_reticulum_calcium_pump__K_2 = var_sarcoplasmic_reticulum_calcium_pump__Ca_i + (var_sarcoplasmic_reticulum_calcium_pump__Ca_up * var_sarcoplasmic_reticulum_calcium_pump__K_1) + (var_sarcoplasmic_reticulum_calcium_pump__K_cyca * var_sarcoplasmic_reticulum_calcium_pump__K_xcs) + var_sarcoplasmic_reticulum_calcium_pump__K_cyca;
    const double var_sarcoplasmic_reticulum_calcium_pump__i_up = ((var_sarcoplasmic_reticulum_calcium_pump__Ca_i / var_sarcoplasmic_reticulum_calcium_pump__K_2) * var_sarcoplasmic_reticulum_calcium_pump__alpha_up) - (((var_sarcoplasmic_reticulum_calcium_pump__Ca_up * var_sarcoplasmic_reticulum_calcium_pump__K_1) / var_sarcoplasmic_reticulum_calcium_pump__K_2) * var_sarcoplasmic_reticulum_calcium_pump__beta_up);
    const double var_calcium_translocation__Ca_rel = var_intracellular_calcium_concentration__Ca_rel;
    const double var_calcium_translocation__Ca_up = var_intracellular_calcium_concentration__Ca_up;
    const double var_calcium_translocation__i_trans = 50.0 * (var_calcium_translocation__Ca_up - var_calcium_translocation__Ca_rel);
    const double var_calcium_release__K_m_rel = 250.0;
    const double var_calcium_release__K_leak_rate = 0.05;
    const double var_calcium_release__Ca_rel = var_intracellular_calcium_concentration__Ca_rel;
    const double var_calcium_release__i_rel = ((pow(var_calcium_release__ActFrac / (var_calcium_release__ActFrac + 0.25), 2.0) * var_calcium_release__K_m_rel) + var_calcium_release__K_leak_rate) * var_calcium_release__Ca_rel;
    const double var_calcium_release__V = var_membrane__V;
    const double var_calcium_release__VoltDep = CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_13(_table_index_0, _factor_0);
    const double var_calcium_release__K_m_Ca_cyt = 0.0005;
    const double var_calcium_release__Ca_i = var_intracellular_calcium_concentration__Ca_i;
    const double var_calcium_release__CaiReg = var_calcium_release__Ca_i / (var_calcium_release__Ca_i + var_calcium_release__K_m_Ca_cyt);
    const double var_calcium_release__Ca_ds = var_intracellular_calcium_concentration__Ca_ds;
    const double var_calcium_release__K_m_Ca_ds = 0.01;
    const double var_calcium_release__CadsReg = var_calcium_release__Ca_ds / (var_calcium_release__Ca_ds + var_calcium_release__K_m_Ca_ds);
    const double var_calcium_release__RegBindSite = var_calcium_release__CaiReg + ((1.0 - var_calcium_release__CaiReg) * var_calcium_release__CadsReg);
    const double var_calcium_release__ActRate = (0.0 * var_calcium_release__VoltDep) + (500.0 * pow(var_calcium_release__RegBindSite, 2.0));
    const double var_calcium_release__InactRate = 60.0 + (500.0 * pow(var_calcium_release__RegBindSite, 2.0));
    const double var_calcium_release__PrecFrac = (1.0 - var_calcium_release__ActFrac) - var_calcium_release__ProdFrac;
    const double var_calcium_release__SpeedRel = (var_calcium_release__V < (-50.0)) ? 5.0 : 1.0;
    const double var_intracellular_calcium_concentration__V_up_ratio = 0.01;
    const double var_intracellular_calcium_concentration__V_rel_ratio = 0.1;
    const double var_intracellular_calcium_concentration__V_e_ratio = 0.4;
    const double var_intracellular_calcium_concentration__V_i_ratio = ((1.0 - var_intracellular_calcium_concentration__V_e_ratio) - var_intracellular_calcium_concentration__V_up_ratio) - var_intracellular_calcium_concentration__V_rel_ratio;
    const double var_intracellular_calcium_concentration__radius = 0.012;
    const double var_intracellular_calcium_concentration__length = 0.074;
    const double var_intracellular_calcium_concentration__V_Cell = 3.141592654 * pow(var_intracellular_calcium_concentration__radius, 2.0) * var_intracellular_calcium_concentration__length;
    const double var_intracellular_calcium_concentration__V_i = var_intracellular_calcium_concentration__V_Cell * var_intracellular_calcium_concentration__V_i_ratio;
    const double var_intracellular_sodium_concentration__V_i = var_intracellular_calcium_concentration__V_i;
    const double var_intracellular_sodium_concentration__F = var_membrane__F;
    const double var_intracellular_sodium_concentration__i_Na = var_fast_sodium_current__i_Na;
    const double var_intracellular_sodium_concentration__i_b_Na = var_sodium_background_current__i_b_Na;
    const double var_intracellular_sodium_concentration__i_p_Na = var_persistent_sodium_current__i_p_Na;
    const double var_intracellular_sodium_concentration__i_Ca_L_Na_cyt = var_L_type_Ca_channel__i_Ca_L_Na_cyt;
    const double var_intracellular_sodium_concentration__i_Ca_L_Na_ds = var_L_type_Ca_channel__i_Ca_L_Na_ds;
    const double var_intracellular_sodium_concentration__i_NaK = var_sodium_potassium_pump__i_NaK;
    const double var_intracellular_sodium_concentration__i_NaCa_cyt = var_sodium_calcium_exchanger__i_NaCa_cyt;
    const double var_intracellular_potassium_concentration__V_i = var_intracellular_calcium_concentration__V_i;
    const double var_intracellular_potassium_concentration__i_K1 = var_time_independent_potassium_current__i_K1;
    const double var_intracellular_potassium_concentration__i_Kr = var_rapid_delayed_rectifier_potassium_current__i_Kr;
    const double var_intracellular_potassium_concentration__i_Ks = var_slow_delayed_rectifier_potassium_current__i_Ks;
    const double var_intracellular_potassium_concentration__i_Ca_L_K_cyt = var_L_type_Ca_channel__i_Ca_L_K_cyt;
    const double var_intracellular_potassium_concentration__i_Ca_L_K_ds = var_L_type_Ca_channel__i_Ca_L_K_ds;
    const double var_intracellular_potassium_concentration__i_to = var_transient_outward_current__i_to;
    const double var_intracellular_potassium_concentration__i_NaK = var_sodium_potassium_pump__i_NaK;
    const double var_intracellular_potassium_concentration__F = var_membrane__F;
    const double var_intracellular_calcium_concentration__Calmod = 0.02;
    const double var_intracellular_calcium_concentration__Trop = 0.05;
    const double var_intracellular_calcium_concentration__alpha_Calmod = 100000.0;
    const double var_intracellular_calcium_concentration__beta_Calmod = 50.0;
    const double var_intracellular_calcium_concentration__alpha_Trop = 100000.0;
    const double var_intracellular_calcium_concentration__beta_Trop = 200.0;
    const double var_intracellular_calcium_concentration__V_ds_ratio = 0.1;
    const double var_intracellular_calcium_concentration__Kdecay = 10.0;
    const double var_intracellular_calcium_concentration__i_up = var_sarcoplasmic_reticulum_calcium_pump__i_up;
    const double var_intracellular_calcium_concentration__i_trans = var_calcium_translocation__i_trans;
    const double var_intracellular_calcium_concentration__i_rel = var_calcium_release__i_rel;
    const double var_intracellular_calcium_concentration__i_NaCa_cyt = var_sodium_calcium_exchanger__i_NaCa_cyt;
    const double var_intracellular_calcium_concentration__i_NaCa_ds = var_sodium_calcium_exchanger__i_NaCa_ds;
    const double var_intracellular_calcium_concentration__i_Ca_L_Ca_cyt = var_L_type_Ca_channel__i_Ca_L_Ca_cyt;
    const double var_intracellular_calcium_concentration__i_Ca_L_Ca_ds = var_L_type_Ca_channel__i_Ca_L_Ca_ds;
    const double var_intracellular_calcium_concentration__i_b_Ca = var_calcium_background_current__i_b_Ca;
    const double var_intracellular_calcium_concentration__F = var_membrane__F;
    
    const double d_dt_membrane__V = ((-1.0) / var_membrane__Cm) * (var_membrane__i_Stim + var_membrane__i_K1 + var_membrane__i_to + var_membrane__i_Kr + var_membrane__i_Ks + var_membrane__i_NaK + var_membrane__i_Na + var_membrane__i_b_Na + var_membrane__i_p_Na + var_membrane__i_Ca_L_Na_cyt + var_membrane__i_Ca_L_Na_ds + var_membrane__i_NaCa_cyt + var_membrane__i_NaCa_ds + var_membrane__i_Ca_L_Ca_cyt + var_membrane__i_Ca_L_Ca_ds + var_membrane__i_Ca_L_K_cyt + var_membrane__i_Ca_L_K_ds + var_membrane__i_b_Ca);
    const double d_dt_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1 = (var_rapid_delayed_rectifier_potassium_current_xr1_gate__alpha_xr1 * (1.0 - var_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1)) - (var_rapid_delayed_rectifier_potassium_current_xr1_gate__beta_xr1 * var_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1);
    const double d_dt_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2 = (var_rapid_delayed_rectifier_potassium_current_xr2_gate__alpha_xr2 * (1.0 - var_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2)) - (var_rapid_delayed_rectifier_potassium_current_xr2_gate__beta_xr2 * var_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2);
    const double d_dt_slow_delayed_rectifier_potassium_current_xs_gate__xs = (var_slow_delayed_rectifier_potassium_current_xs_gate__alpha_xs * (1.0 - var_slow_delayed_rectifier_potassium_current_xs_gate__xs)) - (var_slow_delayed_rectifier_potassium_current_xs_gate__beta_xs * var_slow_delayed_rectifier_potassium_current_xs_gate__xs);
    const double d_dt_fast_sodium_current_m_gate__m = (var_fast_sodium_current_m_gate__alpha_m * (1.0 - var_fast_sodium_current_m_gate__m)) - (var_fast_sodium_current_m_gate__beta_m * var_fast_sodium_current_m_gate__m);
    const double d_dt_fast_sodium_current_h_gate__h = (var_fast_sodium_current_h_gate__alpha_h * (1.0 - var_fast_sodium_current_h_gate__h)) - (var_fast_sodium_current_h_gate__beta_h * var_fast_sodium_current_h_gate__h);
    const double d_dt_L_type_Ca_channel_d_gate__d = var_L_type_Ca_channel_d_gate__speed_d * ((var_L_type_Ca_channel_d_gate__alpha_d * (1.0 - var_L_type_Ca_channel_d_gate__d)) - (var_L_type_Ca_channel_d_gate__beta_d * var_L_type_Ca_channel_d_gate__d));
    const double d_dt_L_type_Ca_channel_f_gate__f = var_L_type_Ca_channel_f_gate__speed_f * ((var_L_type_Ca_channel_f_gate__alpha_f * (1.0 - var_L_type_Ca_channel_f_gate__f)) - (var_L_type_Ca_channel_f_gate__beta_f * var_L_type_Ca_channel_f_gate__f));
    const double d_dt_L_type_Ca_channel_f2_gate__f2 = 1.0 - (1.0 * ((var_L_type_Ca_channel_f2_gate__Ca_i / (var_L_type_Ca_channel_f2_gate__Km_f2 + var_L_type_Ca_channel_f2_gate__Ca_i)) + var_L_type_Ca_channel_f2_gate__f2));
    const double d_dt_L_type_Ca_channel_f2ds_gate__f2ds = var_L_type_Ca_channel_f2ds_gate__R_decay * (1.0 - ((var_L_type_Ca_channel_f2ds_gate__Ca_ds / (var_L_type_Ca_channel_f2ds_gate__Km_f2ds + var_L_type_Ca_channel_f2ds_gate__Ca_ds)) + var_L_type_Ca_channel_f2ds_gate__f2ds));
    const double d_dt_transient_outward_current_s_gate__s = (var_transient_outward_current_s_gate__alpha_s * (1.0 - var_transient_outward_current_s_gate__s)) - (var_transient_outward_current_s_gate__beta_s * var_transient_outward_current_s_gate__s);
    const double d_dt_transient_outward_current_r_gate__r = 333.0 * (CML_noble_varghese_kohl_noble_1998_basic_lut_LookupTables::Instance()->_lookup_12(_table_index_0, _factor_0) - var_transient_outward_current_r_gate__r);
    const double d_dt_calcium_release__ActFrac = (var_calcium_release__PrecFrac * var_calcium_release__SpeedRel * var_calcium_release__ActRate) - (var_calcium_release__ActFrac * var_calcium_release__SpeedRel * var_calcium_release__InactRate);
    const double d_dt_calcium_release__ProdFrac = (var_calcium_release__ActFrac * var_calcium_release__SpeedRel * var_calcium_release__InactRate) - (var_calcium_release__SpeedRel * 1.0 * var_calcium_release__ProdFrac);
    const double d_dt_intracellular_sodium_concentration__Na_i = ((-1.0) / (1.0 * var_intracellular_sodium_concentration__V_i * var_intracellular_sodium_concentration__F)) * (var_intracellular_sodium_concentration__i_Na + var_intracellular_sodium_concentration__i_p_Na + var_intracellular_sodium_concentration__i_b_Na + (3.0 * var_intracellular_sodium_concentration__i_NaK) + (3.0 * var_intracellular_sodium_concentration__i_NaCa_cyt) + var_intracellular_sodium_concentration__i_Ca_L_Na_cyt + var_intracellular_sodium_concentration__i_Ca_L_Na_ds);
    const double d_dt_intracellular_potassium_concentration__K_i = ((-1.0) / (1.0 * var_intracellular_potassium_concentration__V_i * var_intracellular_potassium_concentration__F)) * ((var_intracellular_potassium_concentration__i_K1 + var_intracellular_potassium_concentration__i_Kr + var_intracellular_potassium_concentration__i_Ks + var_intracellular_potassium_concentration__i_Ca_L_K_cyt + var_intracellular_potassium_concentration__i_Ca_L_K_ds + var_intracellular_potassium_concentration__i_to) - (2.0 * var_intracellular_potassium_concentration__i_NaK));
    const double d_dt_intracellular_calcium_concentration__Ca_Trop = (var_intracellular_calcium_concentration__alpha_Trop * var_intracellular_calcium_concentration__Ca_i * (var_intracellular_calcium_concentration__Trop - var_intracellular_calcium_concentration__Ca_Trop)) - (var_intracellular_calcium_concentration__beta_Trop * var_intracellular_calcium_concentration__Ca_Trop);
    const double d_dt_intracellular_calcium_concentration__Ca_Calmod = (var_intracellular_calcium_concentration__alpha_Calmod * var_intracellular_calcium_concentration__Ca_i * (var_intracellular_calcium_concentration__Calmod - var_intracellular_calcium_concentration__Ca_Calmod)) - (var_intracellular_calcium_concentration__beta_Calmod * var_intracellular_calcium_concentration__Ca_Calmod);
    const double d_dt_intracellular_calcium_concentration__Ca_i = ((((((-1.0) / (2.0 * 1.0 * var_intracellular_calcium_concentration__V_i * var_intracellular_calcium_concentration__F)) * (((var_intracellular_calcium_concentration__i_Ca_L_Ca_cyt + var_intracellular_calcium_concentration__i_b_Ca) - (2.0 * var_intracellular_calcium_concentration__i_NaCa_cyt)) - (2.0 * var_intracellular_calcium_concentration__i_NaCa_ds))) + (var_intracellular_calcium_concentration__Ca_ds * var_intracellular_calcium_concentration__V_ds_ratio * var_intracellular_calcium_concentration__Kdecay) + ((var_intracellular_calcium_concentration__i_rel * var_intracellular_calcium_concentration__V_rel_ratio) / var_intracellular_calcium_concentration__V_i_ratio)) - d_dt_intracellular_calcium_concentration__Ca_Calmod) - d_dt_intracellular_calcium_concentration__Ca_Trop) - var_intracellular_calcium_concentration__i_up;
    const double d_dt_intracellular_calcium_concentration__Ca_ds = (((-1.0) * var_intracellular_calcium_concentration__i_Ca_L_Ca_ds) / (2.0 * 1.0 * var_intracellular_calcium_concentration__V_ds_ratio * var_intracellular_calcium_concentration__V_i * var_intracellular_calcium_concentration__F)) - (var_intracellular_calcium_concentration__Ca_ds * var_intracellular_calcium_concentration__Kdecay);
    const double d_dt_intracellular_calcium_concentration__Ca_up = ((var_intracellular_calcium_concentration__V_i_ratio / var_intracellular_calcium_concentration__V_up_ratio) * var_intracellular_calcium_concentration__i_up) - var_intracellular_calcium_concentration__i_trans;
    const double d_dt_intracellular_calcium_concentration__Ca_rel = ((var_intracellular_calcium_concentration__V_up_ratio / var_intracellular_calcium_concentration__V_rel_ratio) * var_intracellular_calcium_concentration__i_trans) - var_intracellular_calcium_concentration__i_rel;
    
    classe->V_lado_direito_ = d_dt_membrane__V;
    classe->xr1_lado_direito_ = d_dt_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1;
    classe->xr2_lado_direito_ = d_dt_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2;
    classe->xs_lado_direito_ = d_dt_slow_delayed_rectifier_potassium_current_xs_gate__xs;
    classe->m_lado_direito_ = d_dt_fast_sodium_current_m_gate__m;
    classe->h_lado_direito_ = d_dt_fast_sodium_current_h_gate__h;
    classe->d_lado_direito_ = d_dt_L_type_Ca_channel_d_gate__d;
    classe->f_lado_direito_ = d_dt_L_type_Ca_channel_f_gate__f;
    classe->f2_lado_direito_ = d_dt_L_type_Ca_channel_f2_gate__f2;
    classe->f2ds_lado_direito_ = d_dt_L_type_Ca_channel_f2ds_gate__f2ds;
    classe->s_lado_direito_ = d_dt_transient_outward_current_s_gate__s;
    classe->r_lado_direito_ = d_dt_transient_outward_current_r_gate__r;
    classe->ActFrac_lado_direito_ = d_dt_calcium_release__ActFrac;
    classe->ProdFrac_lado_direito_ = d_dt_calcium_release__ProdFrac;
    classe->Na_i_lado_direito_ = d_dt_intracellular_sodium_concentration__Na_i;
    classe->K_i_lado_direito_ = d_dt_intracellular_potassium_concentration__K_i;
    classe->Ca_i_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_i;
    classe->Ca_ds_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_ds;
    classe->Ca_up_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_up;
    classe->Ca_rel_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_rel;
    classe->Ca_Calmod_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_Calmod;
    classe->Ca_Trop_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_Trop;
};


#endif
