#ifndef _CML_noble_varghese_kohl_noble_1998_basic_pe_
#define _CML_noble_varghese_kohl_noble_1998_basic_pe_

//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: noble_varghese_kohl_noble_1998_basic
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translate: 1844, pycml: 1844)
//! on Sat Jul 30 00:33:49 2011
//! 
//! <autogenerated>



// 
// Settable parameters and readable variables
// 
void __equation__pe_(Solveode *classe)
{
    // Inputs:
    // Time units: second
    double var_environment__time= classe->time_new;
    double var_membrane__i_K1;
    double var_membrane__i_to;
    double var_membrane__i_Kr;
    double var_membrane__i_Ks;
    double var_membrane__i_Ca_L_K_cyt;
    double var_membrane__i_Ca_L_K_ds;
    double var_membrane__i_NaK;
    double var_membrane__i_Na;
    double var_membrane__i_b_Na;
    double var_membrane__i_p_Na;
    double var_membrane__i_Ca_L_Na_cyt;
    double var_membrane__i_Ca_L_Na_ds;
    double var_membrane__i_NaCa_cyt;
    double var_membrane__i_NaCa_ds;
    double var_membrane__i_Ca_L_Ca_cyt;
    double var_membrane__i_Ca_L_Ca_ds;
    double var_membrane__i_b_Ca;
    double var_membrane__i_Stim;
    double var_membrane__V = classe->V_old_; //var_membrane
    // Units: millivolt; Initial value: -92.849333
    double var_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1 = classe->xr1_old_; //var_rapid_delayed_rectifier_potassium_current_xr1_gate
    // Units: dimensionless; Initial value: 1.03e-5
    double var_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2 = classe->xr2_old_; //var_rapid_delayed_rectifier_potassium_current_xr2_gate
    // Units: dimensionless; Initial value: 2e-7
    double var_slow_delayed_rectifier_potassium_current_xs_gate__xs = classe->xs_old_; //var_slow_delayed_rectifier_potassium_current_xs_gate
    // Units: dimensionless; Initial value: 0.001302
    double var_fast_sodium_current_m_gate__m = classe->m_old_; //var_fast_sodium_current_m_gate
    // Units: dimensionless; Initial value: 0.0016203
    double var_fast_sodium_current_h_gate__h = classe->h_old_; //var_fast_sodium_current_h_gate
    // Units: dimensionless; Initial value: 0.9944036
    double var_L_type_Ca_channel_d_gate__d = classe->d_old_; //var_L_type_Ca_channel_d_gate
    // Units: dimensionless; Initial value: 0
    double var_L_type_Ca_channel_f_gate__f = classe->f_old_; //var_L_type_Ca_channel_f_gate
    // Units: dimensionless; Initial value: 1
    double var_L_type_Ca_channel_f2_gate__f2 = classe->f2_old_; //var_L_type_Ca_channel_f2_gate
    // Units: dimensionless; Initial value: 0.9349197
    double var_L_type_Ca_channel_f2ds_gate__f2ds = classe->f2ds_old_; //var_L_type_Ca_channel_f2ds_gate
    // Units: dimensionless; Initial value: 0.9651958
    double var_transient_outward_current_s_gate__s = classe->s_old_; //var_transient_outward_current_s_gate
    // Units: dimensionless; Initial value: 0.9948645
    double var_transient_outward_current_r_gate__r = classe->r_old_; //var_transient_outward_current_r_gate
    // Units: dimensionless; Initial value: 0
    double var_calcium_release__ActFrac = classe->ActFrac_old_; //var_calcium_release
    // Units: dimensionless; Initial value: 0.0042614
    double var_calcium_release__ProdFrac = classe->ProdFrac_old_; //var_calcium_release
    // Units: dimensionless; Initial value: 0.4068154
    double var_intracellular_sodium_concentration__Na_i = classe->Na_i_old_; //var_intracellular_sodium_concentration
    // Units: millimolar; Initial value: 7.3321223
    double var_intracellular_potassium_concentration__K_i = classe->K_i_old_; //var_intracellular_potassium_concentration
    // Units: millimolar; Initial value: 136.5644281
    double var_intracellular_calcium_concentration__Ca_i = classe->Ca_i_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 1.4e-5
    double var_intracellular_calcium_concentration__Ca_ds = classe->Ca_ds_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 1.88e-5
    double var_intracellular_calcium_concentration__Ca_up = classe->Ca_up_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 0.4531889
    double var_intracellular_calcium_concentration__Ca_rel = classe->Ca_rel_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 0.4481927
    double var_intracellular_calcium_concentration__Ca_Calmod = classe->Ca_Calmod_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 0.0005555
    double var_intracellular_calcium_concentration__Ca_Trop = classe->Ca_Trop_old_; //var_intracellular_calcium_concentration
    // Units: millimolar; Initial value: 0.0003542
    
    
    // Mathematics
    const double var_reversal_potentials__E_K = 26.7137606597 * log(4.0 / var_intracellular_potassium_concentration__K_i);
    const double var_time_independent_potassium_current__i_K1 = (0.142857142857 * (var_membrane__V - var_reversal_potentials__E_K)) / (1.0 + exp((((var_membrane__V - var_reversal_potentials__E_K) - 10.0) * 96485.3415 * 1.25) * 3.87974901066e-07));
    var_membrane__i_K1 = var_time_independent_potassium_current__i_K1;
    const double var_transient_outward_current__i_to = 0.005 * (0.0 + (var_transient_outward_current_s_gate__s * 1.0)) * var_transient_outward_current_r_gate__r * (var_membrane__V - var_reversal_potentials__E_K);
    var_membrane__i_to = var_transient_outward_current__i_to;
    const double var_rapid_delayed_rectifier_potassium_current__i_Kr = ((((0.0021 * var_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1) + (0.0013 * var_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2)) * 1.0) / (1.0 + exp((var_membrane__V + 9.0) * 0.0446428571429))) * (var_membrane__V - var_reversal_potentials__E_K);
    var_membrane__i_Kr = var_rapid_delayed_rectifier_potassium_current__i_Kr;
    const double var_slow_delayed_rectifier_potassium_current__i_Ks = 0.0026 * pow(var_slow_delayed_rectifier_potassium_current_xs_gate__xs, 2.0) * (var_membrane__V - (26.7137606597 * log(8.2 / (var_intracellular_potassium_concentration__K_i + (0.03 * var_intracellular_sodium_concentration__Na_i)))));
    var_membrane__i_Ks = var_slow_delayed_rectifier_potassium_current__i_Ks;
    const double var_L_type_Ca_channel__i_Ca_L_K_cyt = (((0.0 * 0.002 * 0.1 * var_L_type_Ca_channel_d_gate__d * var_L_type_Ca_channel_f_gate__f * var_L_type_Ca_channel_f2_gate__f2 * (var_membrane__V - 50.0) * 96485.3415) * 3.87974901066e-07) / (1.0 - exp(((-(var_membrane__V - 50.0)) * 96485.3415) * 3.87974901066e-07))) * ((var_intracellular_potassium_concentration__K_i * 6.49930040518) - (4.0 * exp(((-(var_membrane__V - 50.0)) * 96485.3415) * 3.87974901066e-07)));
    var_membrane__i_Ca_L_K_cyt = var_L_type_Ca_channel__i_Ca_L_K_cyt;
    const double var_L_type_Ca_channel__i_Ca_L_K_ds = (((1.0 * 0.002 * 0.1 * var_L_type_Ca_channel_d_gate__d * var_L_type_Ca_channel_f_gate__f * var_L_type_Ca_channel_f2ds_gate__f2ds * (var_membrane__V - 50.0) * 96485.3415) * 3.87974901066e-07) / (1.0 - exp(((-(var_membrane__V - 50.0)) * 96485.3415) * 3.87974901066e-07))) * ((var_intracellular_potassium_concentration__K_i * 6.49930040518) - (4.0 * exp(((-(var_membrane__V - 50.0)) * 96485.3415) * 3.87974901066e-07)));
    var_membrane__i_Ca_L_K_ds = var_L_type_Ca_channel__i_Ca_L_K_ds;
    const double var_sodium_potassium_pump__i_NaK = (0.56 * var_intracellular_sodium_concentration__Na_i) / (40.0 + var_intracellular_sodium_concentration__Na_i);
    var_membrane__i_NaK = var_sodium_potassium_pump__i_NaK;
    const double var_fast_sodium_current__i_Na = 2.5 * pow(var_fast_sodium_current_m_gate__m, 3.0) * var_fast_sodium_current_h_gate__h * (var_membrane__V - (26.7137606597 * log(140.48 / (var_intracellular_sodium_concentration__Na_i + (0.12 * var_intracellular_potassium_concentration__K_i)))));
    var_membrane__i_Na = var_fast_sodium_current__i_Na;
    const double var_reversal_potentials__E_Na = 26.7137606597 * log(140.0 / var_intracellular_sodium_concentration__Na_i);
    const double var_sodium_background_current__i_b_Na = 0.0006 * (var_membrane__V - var_reversal_potentials__E_Na);
    var_membrane__i_b_Na = var_sodium_background_current__i_b_Na;
    const double var_persistent_sodium_current__i_p_Na = (0.004 / (1.0 + exp((-(var_membrane__V + 52.0)) * 0.125))) * (var_membrane__V - var_reversal_potentials__E_Na);
    var_membrane__i_p_Na = var_persistent_sodium_current__i_p_Na;
    const double var_L_type_Ca_channel__i_Ca_L_Na_cyt = (((0.0 * 0.01 * 0.1 * var_L_type_Ca_channel_d_gate__d * var_L_type_Ca_channel_f_gate__f * var_L_type_Ca_channel_f2_gate__f2 * (var_membrane__V - 50.0) * 96485.3415) * 3.87974901066e-07) / (1.0 - exp(((-(var_membrane__V - 50.0)) * 96485.3415) * 3.87974901066e-07))) * ((var_intracellular_sodium_concentration__Na_i * 6.49930040518) - (140.0 * exp(((-(var_membrane__V - 50.0)) * 96485.3415) * 3.87974901066e-07)));
    var_membrane__i_Ca_L_Na_cyt = var_L_type_Ca_channel__i_Ca_L_Na_cyt;
    const double var_L_type_Ca_channel__i_Ca_L_Na_ds = (((1.0 * 0.01 * 0.1 * var_L_type_Ca_channel_d_gate__d * var_L_type_Ca_channel_f_gate__f * var_L_type_Ca_channel_f2ds_gate__f2ds * (var_membrane__V - 50.0) * 96485.3415) * 3.87974901066e-07) / (1.0 - exp(((-(var_membrane__V - 50.0)) * 96485.3415) * 3.87974901066e-07))) * ((var_intracellular_sodium_concentration__Na_i * 6.49930040518) - (140.0 * exp(((-(var_membrane__V - 50.0)) * 96485.3415) * 3.87974901066e-07)));
    var_membrane__i_Ca_L_Na_ds = var_L_type_Ca_channel__i_Ca_L_Na_ds;
    const double var_sodium_calcium_exchanger__i_NaCa_cyt = (0.999 * 0.0005 * ((exp((0.5 * 1.0 * var_membrane__V * 96485.3415) * 3.87974901066e-07) * pow(var_intracellular_sodium_concentration__Na_i, 3.0) * 2.0) - (exp(( -0.5 * 1.0 * var_membrane__V * 96485.3415) * 3.87974901066e-07) * 2744000.0 * var_intracellular_calcium_concentration__Ca_i))) / ((1.0 + (0.0 * ((var_intracellular_calcium_concentration__Ca_i * 2744000.0) + (2.0 * pow(var_intracellular_sodium_concentration__Na_i, 3.0))))) * (1.0 + (var_intracellular_calcium_concentration__Ca_i * 144.927536232)));
    var_membrane__i_NaCa_cyt = var_sodium_calcium_exchanger__i_NaCa_cyt;
    const double var_sodium_calcium_exchanger__i_NaCa_ds = (0.001 * 0.0005 * ((exp((0.5 * 1.0 * var_membrane__V * 96485.3415) * 3.87974901066e-07) * pow(var_intracellular_sodium_concentration__Na_i, 3.0) * 2.0) - (exp(( -0.5 * 1.0 * var_membrane__V * 96485.3415) * 3.87974901066e-07) * 2744000.0 * var_intracellular_calcium_concentration__Ca_ds))) / ((1.0 + (0.0 * ((var_intracellular_calcium_concentration__Ca_ds * 2744000.0) + (2.0 * pow(var_intracellular_sodium_concentration__Na_i, 3.0))))) * (1.0 + (var_intracellular_calcium_concentration__Ca_ds * 144.927536232)));
    var_membrane__i_NaCa_ds = var_sodium_calcium_exchanger__i_NaCa_ds;
    const double var_L_type_Ca_channel__i_Ca_L_Ca_cyt = (((0.0 * 4.0 * 0.1 * var_L_type_Ca_channel_d_gate__d * var_L_type_Ca_channel_f_gate__f * var_L_type_Ca_channel_f2_gate__f2 * (var_membrane__V - 50.0) * 96485.3415) * 3.87974901066e-07) / (1.0 - exp(((-(var_membrane__V - 50.0)) * 96485.3415 * 2.0) * 3.87974901066e-07))) * ((var_intracellular_calcium_concentration__Ca_i * 42.2409057568) - (2.0 * exp(((-(var_membrane__V - 50.0)) * 96485.3415 * 2.0) * 3.87974901066e-07)));
    var_membrane__i_Ca_L_Ca_cyt = var_L_type_Ca_channel__i_Ca_L_Ca_cyt;
    const double var_L_type_Ca_channel__i_Ca_L_Ca_ds = (((1.0 * 4.0 * 0.1 * var_L_type_Ca_channel_d_gate__d * var_L_type_Ca_channel_f_gate__f * var_L_type_Ca_channel_f2ds_gate__f2ds * (var_membrane__V - 50.0) * 96485.3415) * 3.87974901066e-07) / (1.0 - exp(((-(var_membrane__V - 50.0)) * 96485.3415 * 2.0) * 3.87974901066e-07))) * ((var_intracellular_calcium_concentration__Ca_i * 42.2409057568) - (2.0 * exp(((-(var_membrane__V - 50.0)) * 96485.3415 * 2.0) * 3.87974901066e-07)));
    var_membrane__i_Ca_L_Ca_ds = var_L_type_Ca_channel__i_Ca_L_Ca_ds;
    const double var_calcium_background_current__i_b_Ca = 0.00025 * (var_membrane__V - (13.3568803298 * log(2.0 / var_intracellular_calcium_concentration__Ca_i)));
    var_membrane__i_b_Ca = var_calcium_background_current__i_b_Ca;
    var_membrane__i_Stim = ((var_environment__time >= 0.1) && (var_environment__time <= 100000.0) && (((var_environment__time - 0.1) - (floor((var_environment__time - 0.1) * 1.0) * 1.0)) <= 0.0015)) ?  -6.0 : 0.0;
    const double var_fast_sodium_current_m_gate__E0_m = var_membrane__V + 41.0;
    const double var_L_type_Ca_channel_d_gate__E0_d = (var_membrane__V + 24.0) - 5.0;
    const double var_L_type_Ca_channel_f_gate__E0_f = var_membrane__V + 34.0;
    const double var_sarcoplasmic_reticulum_calcium_pump__K_2 = var_intracellular_calcium_concentration__Ca_i + (var_intracellular_calcium_concentration__Ca_up * 0.00024) + 0.00012 + 0.0003;
    const double var_sarcoplasmic_reticulum_calcium_pump__i_up = ((var_intracellular_calcium_concentration__Ca_i / var_sarcoplasmic_reticulum_calcium_pump__K_2) * 0.4) - (((var_intracellular_calcium_concentration__Ca_up * 0.00024) / var_sarcoplasmic_reticulum_calcium_pump__K_2) * 0.03);
    const double var_calcium_translocation__i_trans = 50.0 * (var_intracellular_calcium_concentration__Ca_up - var_intracellular_calcium_concentration__Ca_rel);
    const double var_calcium_release__i_rel = ((pow(var_calcium_release__ActFrac / (var_calcium_release__ActFrac + 0.25), 2.0) * 250.0) + 0.05) * var_intracellular_calcium_concentration__Ca_rel;
    const double var_calcium_release__CaiReg = var_intracellular_calcium_concentration__Ca_i / (var_intracellular_calcium_concentration__Ca_i + 0.0005);
    const double var_calcium_release__RegBindSite = var_calcium_release__CaiReg + ((1.0 - var_calcium_release__CaiReg) * (var_intracellular_calcium_concentration__Ca_ds / (var_intracellular_calcium_concentration__Ca_ds + 0.01)));
    const double var_calcium_release__InactRate = 60.0 + (500.0 * pow(var_calcium_release__RegBindSite, 2.0));
    const double var_calcium_release__SpeedRel = (var_membrane__V <  -50.0) ? 5.0 : 1.0;
    
    const double d_dt_membrane__V =  -10526.3157895 * (var_membrane__i_Stim + var_membrane__i_K1 + var_membrane__i_to + var_membrane__i_Kr + var_membrane__i_Ks + var_membrane__i_NaK + var_membrane__i_Na + var_membrane__i_b_Na + var_membrane__i_p_Na + var_membrane__i_Ca_L_Na_cyt + var_membrane__i_Ca_L_Na_ds + var_membrane__i_NaCa_cyt + var_membrane__i_NaCa_ds + var_membrane__i_Ca_L_Ca_cyt + var_membrane__i_Ca_L_Ca_ds + var_membrane__i_Ca_L_K_cyt + var_membrane__i_Ca_L_K_ds + var_membrane__i_b_Ca);
    const double d_dt_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1 = ((50.0 / (1.0 + exp((-(var_membrane__V - 5.0)) * 0.111111111111))) * (1.0 - var_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1)) - ((0.05 * exp((-(var_membrane__V - 20.0)) * 0.0666666666667)) * var_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1);
    const double d_dt_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2 = ((50.0 / (1.0 + exp((-(var_membrane__V - 5.0)) * 0.111111111111))) * (1.0 - var_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2)) - ((0.4 * exp(-pow((var_membrane__V + 30.0) * 0.0333333333333, 3.0))) * var_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2);
    const double d_dt_slow_delayed_rectifier_potassium_current_xs_gate__xs = ((14.0 / (1.0 + exp((-(var_membrane__V - 40.0)) * 0.111111111111))) * (1.0 - var_slow_delayed_rectifier_potassium_current_xs_gate__xs)) - ((1.0 * exp((-var_membrane__V) * 0.0222222222222)) * var_slow_delayed_rectifier_potassium_current_xs_gate__xs);
    const double d_dt_fast_sodium_current_m_gate__m = (((fabs(var_fast_sodium_current_m_gate__E0_m) < 1e-05) ? 2000.0 : ((200.0 * var_fast_sodium_current_m_gate__E0_m) / (1.0 - exp( -0.1 * var_fast_sodium_current_m_gate__E0_m)))) * (1.0 - var_fast_sodium_current_m_gate__m)) - ((8000.0 * exp( -0.056 * (var_membrane__V + 66.0))) * var_fast_sodium_current_m_gate__m);
    const double d_dt_fast_sodium_current_h_gate__h = ((20.0 * exp( -0.125 * ((var_membrane__V + 75.0) - 0.0))) * (1.0 - var_fast_sodium_current_h_gate__h)) - ((2000.0 / (1.0 + (320.0 * exp( -0.1 * ((var_membrane__V + 75.0) - 0.0))))) * var_fast_sodium_current_h_gate__h);
    const double d_dt_L_type_Ca_channel_d_gate__d = 3.0 * ((((fabs(var_L_type_Ca_channel_d_gate__E0_d) < 0.0001) ? 120.0 : ((30.0 * var_L_type_Ca_channel_d_gate__E0_d) / (1.0 - exp((-var_L_type_Ca_channel_d_gate__E0_d) * 0.25)))) * (1.0 - var_L_type_Ca_channel_d_gate__d)) - (((fabs(var_L_type_Ca_channel_d_gate__E0_d) < 0.0001) ? 120.0 : ((12.0 * var_L_type_Ca_channel_d_gate__E0_d) / (exp(var_L_type_Ca_channel_d_gate__E0_d * 0.1) - 1.0))) * var_L_type_Ca_channel_d_gate__d));
    const double d_dt_L_type_Ca_channel_f_gate__f = 0.3 * ((((fabs(var_L_type_Ca_channel_f_gate__E0_f) < 0.0001) ? 25.0 : ((6.25 * var_L_type_Ca_channel_f_gate__E0_f) / (exp(var_L_type_Ca_channel_f_gate__E0_f * 0.25) - 1.0))) * (1.0 - var_L_type_Ca_channel_f_gate__f)) - ((12.0 / (1.0 + exp(( -1.0 * (var_membrane__V + 34.0)) * 0.25))) * var_L_type_Ca_channel_f_gate__f));
    const double d_dt_L_type_Ca_channel_f2_gate__f2 = 1.0 - (1.0 * ((var_intracellular_calcium_concentration__Ca_i / (100000.0 + var_intracellular_calcium_concentration__Ca_i)) + var_L_type_Ca_channel_f2_gate__f2));
    const double d_dt_L_type_Ca_channel_f2ds_gate__f2ds = 20.0 * (1.0 - ((var_intracellular_calcium_concentration__Ca_ds / (0.001 + var_intracellular_calcium_concentration__Ca_ds)) + var_L_type_Ca_channel_f2ds_gate__f2ds));
    const double d_dt_transient_outward_current_s_gate__s = ((0.033 * exp((-var_membrane__V) * 0.0588235294118)) * (1.0 - var_transient_outward_current_s_gate__s)) - ((33.0 / (1.0 + exp( -0.125 * (var_membrane__V + 10.0)))) * var_transient_outward_current_s_gate__s);
    const double d_dt_transient_outward_current_r_gate__r = 333.0 * ((1.0 / (1.0 + exp((-(var_membrane__V + 4.0)) * 0.2))) - var_transient_outward_current_r_gate__r);
    const double d_dt_calcium_release__ActFrac = (((1.0 - var_calcium_release__ActFrac) - var_calcium_release__ProdFrac) * var_calcium_release__SpeedRel * ((0.0 * exp(0.08 * (var_membrane__V - 40.0))) + (500.0 * pow(var_calcium_release__RegBindSite, 2.0)))) - (var_calcium_release__ActFrac * var_calcium_release__SpeedRel * var_calcium_release__InactRate);
    const double d_dt_calcium_release__ProdFrac = (var_calcium_release__ActFrac * var_calcium_release__SpeedRel * var_calcium_release__InactRate) - (var_calcium_release__SpeedRel * 1.0 * var_calcium_release__ProdFrac);
    const double d_dt_intracellular_sodium_concentration__Na_i =  -0.631827460168 * (var_fast_sodium_current__i_Na + var_persistent_sodium_current__i_p_Na + var_sodium_background_current__i_b_Na + (3.0 * var_sodium_potassium_pump__i_NaK) + (3.0 * var_sodium_calcium_exchanger__i_NaCa_cyt) + var_L_type_Ca_channel__i_Ca_L_Na_cyt + var_L_type_Ca_channel__i_Ca_L_Na_ds);
    const double d_dt_intracellular_potassium_concentration__K_i =  -0.631827460168 * ((var_time_independent_potassium_current__i_K1 + var_rapid_delayed_rectifier_potassium_current__i_Kr + var_slow_delayed_rectifier_potassium_current__i_Ks + var_L_type_Ca_channel__i_Ca_L_K_cyt + var_L_type_Ca_channel__i_Ca_L_K_ds + var_transient_outward_current__i_to) - (2.0 * var_sodium_potassium_pump__i_NaK));
    const double d_dt_intracellular_calcium_concentration__Ca_Trop = (100000.0 * var_intracellular_calcium_concentration__Ca_i * (0.05 - var_intracellular_calcium_concentration__Ca_Trop)) - (200.0 * var_intracellular_calcium_concentration__Ca_Trop);
    const double d_dt_intracellular_calcium_concentration__Ca_Calmod = (100000.0 * var_intracellular_calcium_concentration__Ca_i * (0.02 - var_intracellular_calcium_concentration__Ca_Calmod)) - (50.0 * var_intracellular_calcium_concentration__Ca_Calmod);
    const double d_dt_intracellular_calcium_concentration__Ca_i = (((( -0.315913730084 * (((var_L_type_Ca_channel__i_Ca_L_Ca_cyt + var_calcium_background_current__i_b_Ca) - (2.0 * var_sodium_calcium_exchanger__i_NaCa_cyt)) - (2.0 * var_sodium_calcium_exchanger__i_NaCa_ds))) + (var_intracellular_calcium_concentration__Ca_ds * 0.1 * 10.0) + ((var_calcium_release__i_rel * 0.1) * 2.04081632653)) - d_dt_intracellular_calcium_concentration__Ca_Calmod) - d_dt_intracellular_calcium_concentration__Ca_Trop) - var_sarcoplasmic_reticulum_calcium_pump__i_up;
    const double d_dt_intracellular_calcium_concentration__Ca_ds = (( -1.0 * var_L_type_Ca_channel__i_Ca_L_Ca_ds) * 3.15913730084) - (var_intracellular_calcium_concentration__Ca_ds * 10.0);
    const double d_dt_intracellular_calcium_concentration__Ca_up = (49.0 * var_sarcoplasmic_reticulum_calcium_pump__i_up) - var_calcium_translocation__i_trans;
    const double d_dt_intracellular_calcium_concentration__Ca_rel = (0.1 * var_calcium_translocation__i_trans) - var_calcium_release__i_rel;
    
    classe->V_lado_direito_ = d_dt_membrane__V;
    classe->xr1_lado_direito_ = d_dt_rapid_delayed_rectifier_potassium_current_xr1_gate__xr1;
    classe->xr2_lado_direito_ = d_dt_rapid_delayed_rectifier_potassium_current_xr2_gate__xr2;
    classe->xs_lado_direito_ = d_dt_slow_delayed_rectifier_potassium_current_xs_gate__xs;
    classe->m_lado_direito_ = d_dt_fast_sodium_current_m_gate__m;
    classe->h_lado_direito_ = d_dt_fast_sodium_current_h_gate__h;
    classe->d_lado_direito_ = d_dt_L_type_Ca_channel_d_gate__d;
    classe->f_lado_direito_ = d_dt_L_type_Ca_channel_f_gate__f;
    classe->f2_lado_direito_ = d_dt_L_type_Ca_channel_f2_gate__f2;
    classe->f2ds_lado_direito_ = d_dt_L_type_Ca_channel_f2ds_gate__f2ds;
    classe->s_lado_direito_ = d_dt_transient_outward_current_s_gate__s;
    classe->r_lado_direito_ = d_dt_transient_outward_current_r_gate__r;
    classe->ActFrac_lado_direito_ = d_dt_calcium_release__ActFrac;
    classe->ProdFrac_lado_direito_ = d_dt_calcium_release__ProdFrac;
    classe->Na_i_lado_direito_ = d_dt_intracellular_sodium_concentration__Na_i;
    classe->K_i_lado_direito_ = d_dt_intracellular_potassium_concentration__K_i;
    classe->Ca_i_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_i;
    classe->Ca_ds_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_ds;
    classe->Ca_up_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_up;
    classe->Ca_rel_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_rel;
    classe->Ca_Calmod_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_Calmod;
    classe->Ca_Trop_lado_direito_ = d_dt_intracellular_calcium_concentration__Ca_Trop;
};


#endif
