#ifndef _CML_bondarenko_model_2004_apex_
#define _CML_bondarenko_model_2004_apex_

//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: bondarenko_model_2004_apex
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translate: 1844, pycml: 1844)
//! on Wed Jul 20 18:35:28 2011
//! 
//! <autogenerated>



void __equation__(Solveode *classe)
{
    // Inputs:
    // Time units: millisecond
    double var_environment__time= classe->time_new;
    double var_membrane__V = classe->V_old_; //var_membrane
    // Units: millivolt; Initial value: -82.4202
    double var_calcium_concentration__Cai = classe->Cai_old_; //var_calcium_concentration
    // Units: micromolar; Initial value: 0.115001
    double var_calcium_concentration__Cass = classe->Cass_old_; //var_calcium_concentration
    // Units: micromolar; Initial value: 0.115001
    double var_calcium_concentration__CaJSR = classe->CaJSR_old_; //var_calcium_concentration
    // Units: micromolar; Initial value: 1299.5
    double var_calcium_concentration__CaNSR = classe->CaNSR_old_; //var_calcium_concentration
    // Units: micromolar; Initial value: 1299.5
    double var_calcium_fluxes__P_RyR = classe->P_RyR_old_; //var_calcium_fluxes
    // Units: dimensionless; Initial value: 0
    double var_calcium_buffering__LTRPN_Ca = classe->LTRPN_Ca_old_; //var_calcium_buffering
    // Units: micromolar; Initial value: 11.2684
    double var_calcium_buffering__HTRPN_Ca = classe->HTRPN_Ca_old_; //var_calcium_buffering
    // Units: micromolar; Initial value: 125.29
    double var_ryanodine_receptors__P_O1 = classe->P_O1_old_; //var_ryanodine_receptors
    // Units: dimensionless; Initial value: 0.149102e-4
    double var_ryanodine_receptors__P_O2 = classe->P_O2_old_; //var_ryanodine_receptors
    // Units: dimensionless; Initial value: 0.951726e-10
    double var_ryanodine_receptors__P_C2 = classe->P_C2_old_; //var_ryanodine_receptors
    // Units: dimensionless; Initial value: 0.16774e-3
    double var_L_type_calcium_current__O = classe->O_old_; //var_L_type_calcium_current
    // Units: dimensionless; Initial value: 0.930308e-18
    double var_L_type_calcium_current__C2 = classe->C2_old_; //var_L_type_calcium_current
    // Units: dimensionless; Initial value: 0.124216e-3
    double var_L_type_calcium_current__C3 = classe->C3_old_; //var_L_type_calcium_current
    // Units: dimensionless; Initial value: 0.578679e-8
    double var_L_type_calcium_current__C4 = classe->C4_old_; //var_L_type_calcium_current
    // Units: dimensionless; Initial value: 0.119816e-12
    double var_L_type_calcium_current__I1 = classe->I1_old_; //var_L_type_calcium_current
    // Units: dimensionless; Initial value: 0.497923e-18
    double var_L_type_calcium_current__I2 = classe->I2_old_; //var_L_type_calcium_current
    // Units: dimensionless; Initial value: 0.345847e-13
    double var_L_type_calcium_current__I3 = classe->I3_old_; //var_L_type_calcium_current
    // Units: dimensionless; Initial value: 0.185106e-13
    double var_sodium_concentration__Nai = classe->Nai_old_; //var_sodium_concentration
    // Units: micromolar; Initial value: 14237.1
    double var_fast_sodium_current__O_Na = classe->O_Na_old_; //var_fast_sodium_current
    // Units: dimensionless; Initial value: 0.713483e-6
    double var_fast_sodium_current__C_Na1 = classe->C_Na1_old_; //var_fast_sodium_current
    // Units: dimensionless; Initial value: 0.279132e-3
    double var_fast_sodium_current__C_Na2 = classe->C_Na2_old_; //var_fast_sodium_current
    // Units: dimensionless; Initial value: 0.020752
    double var_fast_sodium_current__I1_Na = classe->I1_Na_old_; //var_fast_sodium_current
    // Units: dimensionless; Initial value: 0.673345e-6
    double var_fast_sodium_current__I2_Na = classe->I2_Na_old_; //var_fast_sodium_current
    // Units: dimensionless; Initial value: 0.155787e-8
    double var_fast_sodium_current__IF_Na = classe->IF_Na_old_; //var_fast_sodium_current
    // Units: dimensionless; Initial value: 0.153176e-3
    double var_fast_sodium_current__IC_Na2 = classe->IC_Na2_old_; //var_fast_sodium_current
    // Units: dimensionless; Initial value: 0.0113879
    double var_fast_sodium_current__IC_Na3 = classe->IC_Na3_old_; //var_fast_sodium_current
    // Units: dimensionless; Initial value: 0.34278
    double var_potassium_concentration__Ki = classe->Ki_old_; //var_potassium_concentration
    // Units: micromolar; Initial value: 143720
    double var_fast_transient_outward_potassium_current__ato_f = classe->ato_f_old_; //var_fast_transient_outward_potassium_current
    // Units: dimensionless; Initial value: 0.265563e-2
    double var_fast_transient_outward_potassium_current__ito_f = classe->ito_f_old_; //var_fast_transient_outward_potassium_current
    // Units: dimensionless; Initial value: 0.999977
    double var_slow_transient_outward_potassium_current__ato_s = classe->ato_s_old_; //var_slow_transient_outward_potassium_current
    // Units: dimensionless; Initial value: 0.417069e-3
    double var_slow_transient_outward_potassium_current__ito_s = classe->ito_s_old_; //var_slow_transient_outward_potassium_current
    // Units: dimensionless; Initial value: 0.998543
    double var_slow_delayed_rectifier_potassium_current__nKs = classe->nKs_old_; //var_slow_delayed_rectifier_potassium_current
    // Units: dimensionless; Initial value: 0.262753e-3
    double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__aur = classe->aur_old_; //var_ultra_rapidly_activating_delayed_rectifier_potassium_current
    // Units: dimensionless; Initial value: 0.417069e-3
    double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__iur = classe->iur_old_; //var_ultra_rapidly_activating_delayed_rectifier_potassium_current
    // Units: dimensionless; Initial value: 0.998543
    double var_non_inactivating_steady_state_potassium_current__aKss = classe->aKss_old_; //var_non_inactivating_steady_state_potassium_current
    // Units: dimensionless; Initial value: 0.417069e-3
    double var_non_inactivating_steady_state_potassium_current__iKss = classe->iKss_old_; //var_non_inactivating_steady_state_potassium_current
    // Units: dimensionless; Initial value: 1
    double var_rapid_delayed_rectifier_potassium_current__O_K = classe->O_K_old_; //var_rapid_delayed_rectifier_potassium_current
    // Units: dimensionless; Initial value: 0.175298e-3
    double var_rapid_delayed_rectifier_potassium_current__C_K1 = classe->C_K1_old_; //var_rapid_delayed_rectifier_potassium_current
    // Units: dimensionless; Initial value: 0.992513e-3
    double var_rapid_delayed_rectifier_potassium_current__C_K2 = classe->C_K2_old_; //var_rapid_delayed_rectifier_potassium_current
    // Units: dimensionless; Initial value: 0.641229e-3
    double var_rapid_delayed_rectifier_potassium_current__I_K = classe->I_K_old_; //var_rapid_delayed_rectifier_potassium_current
    // Units: dimensionless; Initial value: 0.319129e-4
    
    
    // Mathematics
    const double var_membrane__Cm = 1.0;
    const double var_membrane__Vmyo = 2.584e-05;
    const double var_membrane__VJSR = 1.2e-07;
    const double var_membrane__VNSR = 2.098e-06;
    const double var_membrane__Vss = 1.485e-09;
    const double var_membrane__Acap = 0.0001534;
    const double var_membrane__Ko = 5400.0;
    const double var_membrane__Nao = 140000.0;
    const double var_membrane__Cao = 1800.0;
    const double var_membrane__R = 8.314;
    const double var_membrane__T = 298.0;
    const double var_membrane__F = 96.5;
    const double var_membrane__stim_end = 100000.0;
    const double var_membrane__stim_amplitude =  -80.0;
    const double var_membrane__time = var_environment__time;
    const double var_membrane__stim_duration = 1.5;
    const double var_membrane__stim_period = 71.43;
    const double var_membrane__stim_start = 20.0;
    const double var_membrane__i_stim = ((var_membrane__time >= var_membrane__stim_start) && (var_membrane__time <= var_membrane__stim_end) && (((var_membrane__time - var_membrane__stim_start) - (floor((var_membrane__time - var_membrane__stim_start) / var_membrane__stim_period) * var_membrane__stim_period)) <= var_membrane__stim_duration)) ? var_membrane__stim_amplitude : 0.0;
    const double var_L_type_calcium_current__E_CaL = 63.0;
    const double var_L_type_calcium_current__g_CaL = 0.1729;
    const double var_L_type_calcium_current__V = var_membrane__V;
    const double var_L_type_calcium_current__i_CaL = var_L_type_calcium_current__g_CaL * var_L_type_calcium_current__O * (var_L_type_calcium_current__V - var_L_type_calcium_current__E_CaL);
    const double var_membrane__i_CaL = var_L_type_calcium_current__i_CaL;
    const double var_calcium_pump_current__i_pCa_max = 1.0;
    const double var_calcium_pump_current__Km_pCa = 0.5;
    const double var_calcium_pump_current__Cai = var_calcium_concentration__Cai;
    const double var_calcium_pump_current__i_pCa = (var_calcium_pump_current__i_pCa_max * pow(var_calcium_pump_current__Cai, 2.0)) / (pow(var_calcium_pump_current__Km_pCa, 2.0) + pow(var_calcium_pump_current__Cai, 2.0));
    const double var_membrane__i_pCa = var_calcium_pump_current__i_pCa;
    const double var_sodium_calcium_exchange_current__k_NaCa = 292.8;
    const double var_sodium_calcium_exchange_current__T = var_membrane__T;
    const double var_sodium_calcium_exchange_current__Cao = var_membrane__Cao;
    const double var_sodium_calcium_exchange_current__V = var_membrane__V;
    const double var_sodium_calcium_exchange_current__K_mCa = 1380.0;
    const double var_sodium_calcium_exchange_current__k_sat = 0.1;
    const double var_sodium_calcium_exchange_current__R = var_membrane__R;
    const double var_sodium_calcium_exchange_current__Cai = var_calcium_concentration__Cai;
    const double var_sodium_calcium_exchange_current__Nao = var_membrane__Nao;
    const double var_sodium_calcium_exchange_current__F = var_membrane__F;
    const double var_sodium_calcium_exchange_current__K_mNa = 87500.0;
    const double var_sodium_calcium_exchange_current__eta = 0.35;
    const double var_sodium_calcium_exchange_current__Nai = var_sodium_concentration__Nai;
    const double var_sodium_calcium_exchange_current__i_NaCa = ((((((var_sodium_calcium_exchange_current__k_NaCa * 1.0) / (pow(var_sodium_calcium_exchange_current__K_mNa, 3.0) + pow(var_sodium_calcium_exchange_current__Nao, 3.0))) * 1.0) / (var_sodium_calcium_exchange_current__K_mCa + var_sodium_calcium_exchange_current__Cao)) * 1.0) / (1.0 + (var_sodium_calcium_exchange_current__k_sat * exp(((var_sodium_calcium_exchange_current__eta - 1.0) * var_sodium_calcium_exchange_current__V * var_sodium_calcium_exchange_current__F) / (var_sodium_calcium_exchange_current__R * var_sodium_calcium_exchange_current__T))))) * ((exp((var_sodium_calcium_exchange_current__eta * var_sodium_calcium_exchange_current__V * var_sodium_calcium_exchange_current__F) / (var_sodium_calcium_exchange_current__R * var_sodium_calcium_exchange_current__T)) * pow(var_sodium_calcium_exchange_current__Nai, 3.0) * var_sodium_calcium_exchange_current__Cao) - (exp(((var_sodium_calcium_exchange_current__eta - 1.0) * var_sodium_calcium_exchange_current__V * var_sodium_calcium_exchange_current__F) / (var_sodium_calcium_exchange_current__R * var_sodium_calcium_exchange_current__T)) * pow(var_sodium_calcium_exchange_current__Nao, 3.0) * var_sodium_calcium_exchange_current__Cai));
    const double var_membrane__i_NaCa = var_sodium_calcium_exchange_current__i_NaCa;
    const double var_calcium_background_current__R = var_membrane__R;
    const double var_calcium_background_current__Cai = var_calcium_concentration__Cai;
    const double var_calcium_background_current__F = var_membrane__F;
    const double var_calcium_background_current__T = var_membrane__T;
    const double var_calcium_background_current__Cao = var_membrane__Cao;
    const double var_calcium_background_current__E_CaN = ((var_calcium_background_current__R * var_calcium_background_current__T) / (2.0 * var_calcium_background_current__F)) * log(var_calcium_background_current__Cao / var_calcium_background_current__Cai);
    const double var_calcium_background_current__g_Cab = 0.000367;
    const double var_calcium_background_current__V = var_membrane__V;
    const double var_calcium_background_current__i_Cab = var_calcium_background_current__g_Cab * (var_calcium_background_current__V - var_calcium_background_current__E_CaN);
    const double var_membrane__i_Cab = var_calcium_background_current__i_Cab;
    const double var_fast_sodium_current__V = var_membrane__V;
    const double var_fast_sodium_current__Nao = var_membrane__Nao;
    const double var_fast_sodium_current__Nai = var_sodium_concentration__Nai;
    const double var_fast_sodium_current__R = var_membrane__R;
    const double var_fast_sodium_current__Ki = var_potassium_concentration__Ki;
    const double var_fast_sodium_current__F = var_membrane__F;
    const double var_fast_sodium_current__Ko = var_membrane__Ko;
    const double var_fast_sodium_current__T = var_membrane__T;
    const double var_fast_sodium_current__E_Na = ((var_fast_sodium_current__R * var_fast_sodium_current__T) / var_fast_sodium_current__F) * log(((0.9 * var_fast_sodium_current__Nao) + (0.1 * var_fast_sodium_current__Ko)) / ((0.9 * var_fast_sodium_current__Nai) + (0.1 * var_fast_sodium_current__Ki)));
    const double var_fast_sodium_current__g_Na = 13.0;
    const double var_fast_sodium_current__i_Na = var_fast_sodium_current__g_Na * var_fast_sodium_current__O_Na * (var_fast_sodium_current__V - var_fast_sodium_current__E_Na);
    const double var_membrane__i_Na = var_fast_sodium_current__i_Na;
    const double var_sodium_background_current__g_Nab = 0.0026;
    const double var_sodium_background_current__V = var_membrane__V;
    const double var_sodium_background_current__E_Na = var_fast_sodium_current__E_Na;
    const double var_sodium_background_current__i_Nab = var_sodium_background_current__g_Nab * (var_sodium_background_current__V - var_sodium_background_current__E_Na);
    const double var_membrane__i_Nab = var_sodium_background_current__i_Nab;
    const double var_sodium_potassium_pump_current__Km_Nai = 21000.0;
    const double var_sodium_potassium_pump_current__Nai = var_sodium_concentration__Nai;
    const double var_sodium_potassium_pump_current__Ko = var_membrane__Ko;
    const double var_sodium_potassium_pump_current__V = var_membrane__V;
    const double var_sodium_potassium_pump_current__R = var_membrane__R;
    const double var_sodium_potassium_pump_current__T = var_membrane__T;
    const double var_sodium_potassium_pump_current__Nao = var_membrane__Nao;
    const double var_sodium_potassium_pump_current__sigma = (1.0 / 7.0) * (exp(var_sodium_potassium_pump_current__Nao / 67300.0) - 1.0);
    const double var_sodium_potassium_pump_current__F = var_membrane__F;
    const double var_sodium_potassium_pump_current__f_NaK = 1.0 / (1.0 + (0.1245 * exp(((-0.1) * var_sodium_potassium_pump_current__V * var_sodium_potassium_pump_current__F) / (var_sodium_potassium_pump_current__R * var_sodium_potassium_pump_current__T))) + (0.0365 * var_sodium_potassium_pump_current__sigma * exp(((-var_sodium_potassium_pump_current__V) * var_sodium_potassium_pump_current__F) / (var_sodium_potassium_pump_current__R * var_sodium_potassium_pump_current__T))));
    const double var_sodium_potassium_pump_current__i_NaK_max = 0.88;
    const double var_sodium_potassium_pump_current__Km_Ko = 1500.0;
    const double var_sodium_potassium_pump_current__i_NaK = (((var_sodium_potassium_pump_current__i_NaK_max * var_sodium_potassium_pump_current__f_NaK * 1.0) / (1.0 + pow(var_sodium_potassium_pump_current__Km_Nai / var_sodium_potassium_pump_current__Nai, 1.5))) * var_sodium_potassium_pump_current__Ko) / (var_sodium_potassium_pump_current__Ko + var_sodium_potassium_pump_current__Km_Ko);
    const double var_membrane__i_NaK = var_sodium_potassium_pump_current__i_NaK;
    const double var_fast_transient_outward_potassium_current__g_Kto_f = 0.4067;
    const double var_fast_transient_outward_potassium_current__R = var_membrane__R;
    const double var_fast_transient_outward_potassium_current__Ko = var_membrane__Ko;
    const double var_fast_transient_outward_potassium_current__Ki = var_potassium_concentration__Ki;
    const double var_fast_transient_outward_potassium_current__F = var_membrane__F;
    const double var_fast_transient_outward_potassium_current__T = var_membrane__T;
    const double var_fast_transient_outward_potassium_current__E_K = ((var_fast_transient_outward_potassium_current__R * var_fast_transient_outward_potassium_current__T) / var_fast_transient_outward_potassium_current__F) * log(var_fast_transient_outward_potassium_current__Ko / var_fast_transient_outward_potassium_current__Ki);
    const double var_fast_transient_outward_potassium_current__V = var_membrane__V;
    const double var_fast_transient_outward_potassium_current__i_Kto_f = var_fast_transient_outward_potassium_current__g_Kto_f * pow(var_fast_transient_outward_potassium_current__ato_f, 3.0) * var_fast_transient_outward_potassium_current__ito_f * (var_fast_transient_outward_potassium_current__V - var_fast_transient_outward_potassium_current__E_K);
    const double var_membrane__i_Kto_f = var_fast_transient_outward_potassium_current__i_Kto_f;
    const double var_slow_transient_outward_potassium_current__g_Kto_s = 0.0;
    const double var_slow_transient_outward_potassium_current__V = var_membrane__V;
    const double var_slow_transient_outward_potassium_current__E_K = var_fast_transient_outward_potassium_current__E_K;
    const double var_slow_transient_outward_potassium_current__i_Kto_s = var_slow_transient_outward_potassium_current__g_Kto_s * var_slow_transient_outward_potassium_current__ato_s * var_slow_transient_outward_potassium_current__ito_s * (var_slow_transient_outward_potassium_current__V - var_slow_transient_outward_potassium_current__E_K);
    const double var_membrane__i_Kto_s = var_slow_transient_outward_potassium_current__i_Kto_s;
    const double var_time_independent_potassium_current__E_K = var_fast_transient_outward_potassium_current__E_K;
    const double var_time_independent_potassium_current__V = var_membrane__V;
    const double var_time_independent_potassium_current__Ko = var_membrane__Ko;
    const double var_time_independent_potassium_current__i_K1 = (((0.2938 * var_time_independent_potassium_current__Ko) / (var_time_independent_potassium_current__Ko + 210.0)) * (var_time_independent_potassium_current__V - var_time_independent_potassium_current__E_K)) / (1.0 + exp(0.0896 * (var_time_independent_potassium_current__V - var_time_independent_potassium_current__E_K)));
    const double var_membrane__i_K1 = var_time_independent_potassium_current__i_K1;
    const double var_slow_delayed_rectifier_potassium_current__E_K = var_fast_transient_outward_potassium_current__E_K;
    const double var_slow_delayed_rectifier_potassium_current__g_Ks = 0.00575;
    const double var_slow_delayed_rectifier_potassium_current__V = var_membrane__V;
    const double var_slow_delayed_rectifier_potassium_current__i_Ks = var_slow_delayed_rectifier_potassium_current__g_Ks * pow(var_slow_delayed_rectifier_potassium_current__nKs, 2.0) * (var_slow_delayed_rectifier_potassium_current__V - var_slow_delayed_rectifier_potassium_current__E_K);
    const double var_membrane__i_Ks = var_slow_delayed_rectifier_potassium_current__i_Ks;
    const double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__E_K = var_fast_transient_outward_potassium_current__E_K;
    const double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__g_Kur = 0.16;
    const double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__V = var_membrane__V;
    const double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__i_Kur = var_ultra_rapidly_activating_delayed_rectifier_potassium_current__g_Kur * var_ultra_rapidly_activating_delayed_rectifier_potassium_current__aur * var_ultra_rapidly_activating_delayed_rectifier_potassium_current__iur * (var_ultra_rapidly_activating_delayed_rectifier_potassium_current__V - var_ultra_rapidly_activating_delayed_rectifier_potassium_current__E_K);
    const double var_membrane__i_Kur = var_ultra_rapidly_activating_delayed_rectifier_potassium_current__i_Kur;
    const double var_non_inactivating_steady_state_potassium_current__V = var_membrane__V;
    const double var_non_inactivating_steady_state_potassium_current__E_K = var_fast_transient_outward_potassium_current__E_K;
    const double var_non_inactivating_steady_state_potassium_current__g_Kss = 0.05;
    const double var_non_inactivating_steady_state_potassium_current__i_Kss = var_non_inactivating_steady_state_potassium_current__g_Kss * var_non_inactivating_steady_state_potassium_current__aKss * var_non_inactivating_steady_state_potassium_current__iKss * (var_non_inactivating_steady_state_potassium_current__V - var_non_inactivating_steady_state_potassium_current__E_K);
    const double var_membrane__i_Kss = var_non_inactivating_steady_state_potassium_current__i_Kss;
    const double var_calcium_activated_chloride_current__E_Cl =  -40.0;
    const double var_calcium_activated_chloride_current__Km_Cl = 10.0;
    const double var_calcium_activated_chloride_current__Cai = var_calcium_concentration__Cai;
    const double var_calcium_activated_chloride_current__V = var_membrane__V;
    const double var_calcium_activated_chloride_current__O_ClCa = 0.2 / (1.0 + exp((-(var_calcium_activated_chloride_current__V - 46.7)) / 7.8));
    const double var_calcium_activated_chloride_current__g_ClCa = 10.0;
    const double var_calcium_activated_chloride_current__i_ClCa = ((var_calcium_activated_chloride_current__g_ClCa * var_calcium_activated_chloride_current__O_ClCa * var_calcium_activated_chloride_current__Cai) / (var_calcium_activated_chloride_current__Cai + var_calcium_activated_chloride_current__Km_Cl)) * (var_calcium_activated_chloride_current__V - var_calcium_activated_chloride_current__E_Cl);
    const double var_membrane__i_ClCa = var_calcium_activated_chloride_current__i_ClCa;
    const double var_rapid_delayed_rectifier_potassium_current__g_Kr = 0.078;
    const double var_rapid_delayed_rectifier_potassium_current__V = var_membrane__V;
    const double var_rapid_delayed_rectifier_potassium_current__Ko = var_membrane__Ko;
    const double var_rapid_delayed_rectifier_potassium_current__R = var_membrane__R;
    const double var_rapid_delayed_rectifier_potassium_current__Nai = var_sodium_concentration__Nai;
    const double var_rapid_delayed_rectifier_potassium_current__Nao = var_membrane__Nao;
    const double var_rapid_delayed_rectifier_potassium_current__T = var_membrane__T;
    const double var_rapid_delayed_rectifier_potassium_current__F = var_membrane__F;
    const double var_rapid_delayed_rectifier_potassium_current__Ki = var_potassium_concentration__Ki;
    const double var_rapid_delayed_rectifier_potassium_current__i_Kr = var_rapid_delayed_rectifier_potassium_current__g_Kr * var_rapid_delayed_rectifier_potassium_current__O_K * (var_rapid_delayed_rectifier_potassium_current__V - (((var_rapid_delayed_rectifier_potassium_current__R * var_rapid_delayed_rectifier_potassium_current__T) / var_rapid_delayed_rectifier_potassium_current__F) * log(((0.98 * var_rapid_delayed_rectifier_potassium_current__Ko) + (0.02 * var_rapid_delayed_rectifier_potassium_current__Nao)) / ((0.98 * var_rapid_delayed_rectifier_potassium_current__Ki) + (0.02 * var_rapid_delayed_rectifier_potassium_current__Nai)))));
    const double var_membrane__i_Kr = var_rapid_delayed_rectifier_potassium_current__i_Kr;
    const double var_calcium_concentration__CMDN_tot = 50.0;
    const double var_calcium_concentration__Km_CMDN = 0.238;
    const double var_calcium_concentration__Bi = pow(1.0 + ((var_calcium_concentration__CMDN_tot * var_calcium_concentration__Km_CMDN) / pow(var_calcium_concentration__Km_CMDN + var_calcium_concentration__Cai, 2.0)), -1.0);
    const double var_calcium_concentration__Bss = pow(1.0 + ((var_calcium_concentration__CMDN_tot * var_calcium_concentration__Km_CMDN) / pow(var_calcium_concentration__Km_CMDN + var_calcium_concentration__Cass, 2.0)), -1.0);
    const double var_calcium_concentration__CSQN_tot = 15000.0;
    const double var_calcium_concentration__Km_CSQN = 800.0;
    const double var_calcium_concentration__BJSR = pow(1.0 + ((var_calcium_concentration__CSQN_tot * var_calcium_concentration__Km_CSQN) / pow(var_calcium_concentration__Km_CSQN + var_calcium_concentration__CaJSR, 2.0)), -1.0);
    const double var_calcium_concentration__Acap = var_membrane__Acap;
    const double var_calcium_concentration__Vmyo = var_membrane__Vmyo;
    const double var_calcium_concentration__VJSR = var_membrane__VJSR;
    const double var_calcium_concentration__Vss = var_membrane__Vss;
    const double var_calcium_concentration__VNSR = var_membrane__VNSR;
    const double var_calcium_concentration__Cm = var_membrane__Cm;
    const double var_calcium_concentration__F = var_membrane__F;
    const double var_calcium_concentration__i_Cab = var_calcium_background_current__i_Cab;
    const double var_calcium_concentration__i_CaL = var_L_type_calcium_current__i_CaL;
    const double var_calcium_concentration__i_NaCa = var_sodium_calcium_exchange_current__i_NaCa;
    const double var_calcium_concentration__i_pCa = var_calcium_pump_current__i_pCa;
    const double var_calcium_fluxes__v2 = 1.74e-05;
    const double var_calcium_fluxes__Cai = var_calcium_concentration__Cai;
    const double var_calcium_fluxes__CaNSR = var_calcium_concentration__CaNSR;
    const double var_calcium_fluxes__J_leak = var_calcium_fluxes__v2 * (var_calcium_fluxes__CaNSR - var_calcium_fluxes__Cai);
    const double var_calcium_concentration__J_leak = var_calcium_fluxes__J_leak;
    const double var_calcium_fluxes__Cass = var_calcium_concentration__Cass;
    const double var_calcium_fluxes__P_O1 = var_ryanodine_receptors__P_O1;
    const double var_calcium_fluxes__P_O2 = var_ryanodine_receptors__P_O2;
    const double var_calcium_fluxes__v1 = 4.5;
    const double var_calcium_fluxes__CaJSR = var_calcium_concentration__CaJSR;
    const double var_calcium_fluxes__J_rel = var_calcium_fluxes__v1 * (var_calcium_fluxes__P_O1 + var_calcium_fluxes__P_O2) * (var_calcium_fluxes__CaJSR - var_calcium_fluxes__Cass) * var_calcium_fluxes__P_RyR;
    const double var_calcium_concentration__J_rel = var_calcium_fluxes__J_rel;
    const double var_calcium_fluxes__Km_up = 0.5;
    const double var_calcium_fluxes__v3 = 0.45;
    const double var_calcium_fluxes__J_up = (var_calcium_fluxes__v3 * pow(var_calcium_fluxes__Cai, 2.0)) / (pow(var_calcium_fluxes__Km_up, 2.0) + pow(var_calcium_fluxes__Cai, 2.0));
    const double var_calcium_concentration__J_up = var_calcium_fluxes__J_up;
    const double var_calcium_fluxes__tau_tr = 20.0;
    const double var_calcium_fluxes__J_tr = (var_calcium_fluxes__CaNSR - var_calcium_fluxes__CaJSR) / var_calcium_fluxes__tau_tr;
    const double var_calcium_concentration__J_tr = var_calcium_fluxes__J_tr;
    const double var_calcium_fluxes__k_plus_ltrpn = 0.0327;
    const double var_calcium_buffering__LTRPN_tot = 70.0;
    const double var_calcium_fluxes__LTRPN_tot = var_calcium_buffering__LTRPN_tot;
    const double var_calcium_fluxes__k_minus_ltrpn = 0.0196;
    const double var_calcium_fluxes__LTRPN_Ca = var_calcium_buffering__LTRPN_Ca;
    const double var_calcium_buffering__HTRPN_tot = 140.0;
    const double var_calcium_fluxes__HTRPN_tot = var_calcium_buffering__HTRPN_tot;
    const double var_calcium_fluxes__k_plus_htrpn = 0.00237;
    const double var_calcium_fluxes__HTRPN_Ca = var_calcium_buffering__HTRPN_Ca;
    const double var_calcium_fluxes__k_minus_htrpn = 3.2e-05;
    const double var_calcium_fluxes__J_trpn = ((var_calcium_fluxes__k_plus_htrpn * var_calcium_fluxes__Cai * (var_calcium_fluxes__HTRPN_tot - var_calcium_fluxes__HTRPN_Ca)) + (var_calcium_fluxes__k_plus_ltrpn * var_calcium_fluxes__Cai * (var_calcium_fluxes__LTRPN_tot - var_calcium_fluxes__LTRPN_Ca))) - ((var_calcium_fluxes__k_minus_htrpn * var_calcium_fluxes__HTRPN_Ca) + (var_calcium_fluxes__k_minus_ltrpn * var_calcium_fluxes__LTRPN_Ca));
    const double var_calcium_concentration__J_trpn = var_calcium_fluxes__J_trpn;
    const double var_calcium_fluxes__tau_xfer = 8.0;
    const double var_calcium_fluxes__J_xfer = (var_calcium_fluxes__Cass - var_calcium_fluxes__Cai) / var_calcium_fluxes__tau_xfer;
    const double var_calcium_concentration__J_xfer = var_calcium_fluxes__J_xfer;
    const double var_calcium_fluxes__V = var_membrane__V;
    const double var_L_type_calcium_current__i_CaL_max = 7.0;
    const double var_calcium_fluxes__i_CaL_max = var_L_type_calcium_current__i_CaL_max;
    const double var_calcium_fluxes__i_CaL = var_L_type_calcium_current__i_CaL;
    const double var_calcium_buffering__Cai = var_calcium_concentration__Cai;
    const double var_calcium_buffering__k_plus_htrpn = var_calcium_fluxes__k_plus_htrpn;
    const double var_calcium_buffering__k_minus_htrpn = var_calcium_fluxes__k_minus_htrpn;
    const double var_calcium_buffering__k_plus_ltrpn = var_calcium_fluxes__k_plus_ltrpn;
    const double var_calcium_buffering__k_minus_ltrpn = var_calcium_fluxes__k_minus_ltrpn;
    const double var_ryanodine_receptors__P_C1 = 1.0 - (var_ryanodine_receptors__P_C2 + var_ryanodine_receptors__P_O1 + var_ryanodine_receptors__P_O2);
    const double var_ryanodine_receptors__k_plus_a = 0.006075;
    const double var_ryanodine_receptors__k_minus_a = 0.07125;
    const double var_ryanodine_receptors__k_plus_b = 0.00405;
    const double var_ryanodine_receptors__k_minus_b = 0.965;
    const double var_ryanodine_receptors__k_plus_c = 0.009;
    const double var_ryanodine_receptors__k_minus_c = 0.0008;
    const double var_ryanodine_receptors__m = 3.0;
    const double var_ryanodine_receptors__n = 4.0;
    const double var_ryanodine_receptors__Cass = var_calcium_concentration__Cass;
    const double var_L_type_calcium_current__C1 = 1.0 - (var_L_type_calcium_current__O + var_L_type_calcium_current__C2 + var_L_type_calcium_current__C2 + var_L_type_calcium_current__C3 + var_L_type_calcium_current__C4 + var_L_type_calcium_current__I1 + var_L_type_calcium_current__I2 + var_L_type_calcium_current__I3);
    const double var_L_type_calcium_current__alpha = (0.4 * exp((var_L_type_calcium_current__V + 12.0) / 10.0) * ((1.0 + (0.7 * exp((-pow(var_L_type_calcium_current__V + 40.0, 2.0)) / 10.0))) - (0.75 * exp((-pow(var_L_type_calcium_current__V + 20.0, 2.0)) / 400.0)))) / (1.0 + (0.12 * exp((var_L_type_calcium_current__V + 12.0) / 10.0)));
    const double var_L_type_calcium_current__beta = 0.05 * exp((-(var_L_type_calcium_current__V + 12.0)) / 13.0);
    const double var_L_type_calcium_current__Kpc_max = 0.23324;
    const double var_L_type_calcium_current__Kpc_half = 20.0;
    const double var_L_type_calcium_current__Cass = var_calcium_concentration__Cass;
    const double var_L_type_calcium_current__gamma = (var_L_type_calcium_current__Kpc_max * var_L_type_calcium_current__Cass) / (var_L_type_calcium_current__Kpc_half + var_L_type_calcium_current__Cass);
    const double var_L_type_calcium_current__Kpcf = 13.0 * (1.0 - exp((-pow(var_L_type_calcium_current__V + 14.5, 2.0)) / 100.0));
    const double var_L_type_calcium_current__Kpcb = 0.0005;
    const double var_sodium_concentration__F = var_membrane__F;
    const double var_sodium_concentration__Vmyo = var_membrane__Vmyo;
    const double var_sodium_concentration__Cm = var_membrane__Cm;
    const double var_sodium_concentration__Acap = var_membrane__Acap;
    const double var_sodium_concentration__i_Na = var_fast_sodium_current__i_Na;
    const double var_sodium_concentration__i_NaCa = var_sodium_calcium_exchange_current__i_NaCa;
    const double var_sodium_concentration__i_NaK = var_sodium_potassium_pump_current__i_NaK;
    const double var_sodium_concentration__i_Nab = var_sodium_background_current__i_Nab;
    const double var_fast_sodium_current__C_Na3 = 1.0 - (var_fast_sodium_current__O_Na + var_fast_sodium_current__C_Na1 + var_fast_sodium_current__C_Na2 + var_fast_sodium_current__IF_Na + var_fast_sodium_current__I1_Na + var_fast_sodium_current__I2_Na + var_fast_sodium_current__IC_Na2 + var_fast_sodium_current__IC_Na3);
    const double var_fast_sodium_current__alpha_Na11 = 3.802 / ((0.1027 * exp((-(var_fast_sodium_current__V + 2.5)) / 17.0)) + (0.2 * exp((-(var_fast_sodium_current__V + 2.5)) / 150.0)));
    const double var_fast_sodium_current__beta_Na11 = 0.1917 * exp((-(var_fast_sodium_current__V + 2.5)) / 20.3);
    const double var_fast_sodium_current__alpha_Na12 = 3.802 / ((0.1027 * exp((-(var_fast_sodium_current__V + 2.5)) / 15.0)) + (0.23 * exp((-(var_fast_sodium_current__V + 2.5)) / 150.0)));
    const double var_fast_sodium_current__beta_Na12 = 0.2 * exp((-(var_fast_sodium_current__V - 2.5)) / 20.3);
    const double var_fast_sodium_current__alpha_Na13 = 3.802 / ((0.1027 * exp((-(var_fast_sodium_current__V + 2.5)) / 12.0)) + (0.25 * exp((-(var_fast_sodium_current__V + 2.5)) / 150.0)));
    const double var_fast_sodium_current__beta_Na13 = 0.22 * exp((-(var_fast_sodium_current__V - 7.5)) / 20.3);
    const double var_fast_sodium_current__alpha_Na3 = 7e-07 * exp((-(var_fast_sodium_current__V + 7.0)) / 7.7);
    const double var_fast_sodium_current__beta_Na3 = 0.0084 + (2e-05 * (var_fast_sodium_current__V + 7.0));
    const double var_fast_sodium_current__alpha_Na2 = 1.0 / ((0.188495 * exp((-(var_fast_sodium_current__V + 7.0)) / 16.6)) + 0.393956);
    const double var_fast_sodium_current__beta_Na2 = (var_fast_sodium_current__alpha_Na13 * var_fast_sodium_current__alpha_Na2 * var_fast_sodium_current__alpha_Na3) / (var_fast_sodium_current__beta_Na13 * var_fast_sodium_current__beta_Na3);
    const double var_fast_sodium_current__alpha_Na4 = var_fast_sodium_current__alpha_Na2 / 1000.0;
    const double var_fast_sodium_current__beta_Na4 = var_fast_sodium_current__alpha_Na3;
    const double var_fast_sodium_current__alpha_Na5 = var_fast_sodium_current__alpha_Na2 / 95000.0;
    const double var_fast_sodium_current__beta_Na5 = var_fast_sodium_current__alpha_Na3 / 50.0;
    const double var_potassium_concentration__F = var_membrane__F;
    const double var_potassium_concentration__Vmyo = var_membrane__Vmyo;
    const double var_potassium_concentration__Cm = var_membrane__Cm;
    const double var_potassium_concentration__Acap = var_membrane__Acap;
    const double var_potassium_concentration__i_Kto_f = var_fast_transient_outward_potassium_current__i_Kto_f;
    const double var_potassium_concentration__i_Kto_s = var_slow_transient_outward_potassium_current__i_Kto_s;
    const double var_potassium_concentration__i_K1 = var_time_independent_potassium_current__i_K1;
    const double var_potassium_concentration__i_Ks = var_slow_delayed_rectifier_potassium_current__i_Ks;
    const double var_potassium_concentration__i_Kss = var_non_inactivating_steady_state_potassium_current__i_Kss;
    const double var_potassium_concentration__i_Kur = var_ultra_rapidly_activating_delayed_rectifier_potassium_current__i_Kur;
    const double var_potassium_concentration__i_Kr = var_rapid_delayed_rectifier_potassium_current__i_Kr;
    const double var_potassium_concentration__i_NaK = var_sodium_potassium_pump_current__i_NaK;
    const double var_fast_transient_outward_potassium_current__alpha_a = 0.18064 * exp(0.03577 * (var_fast_transient_outward_potassium_current__V + 30.0));
    const double var_fast_transient_outward_potassium_current__beta_a = 0.3956 * exp((-0.06237) * (var_fast_transient_outward_potassium_current__V + 30.0));
    const double var_fast_transient_outward_potassium_current__alpha_i = (0.000152 * exp((-(var_fast_transient_outward_potassium_current__V + 13.5)) / 7.0)) / ((0.0067083 * exp((-(var_fast_transient_outward_potassium_current__V + 33.5)) / 7.0)) + 1.0);
    const double var_fast_transient_outward_potassium_current__beta_i = (0.00095 * exp((var_fast_transient_outward_potassium_current__V + 33.5) / 7.0)) / ((0.051335 * exp((var_fast_transient_outward_potassium_current__V + 33.5) / 7.0)) + 1.0);
    const double var_slow_transient_outward_potassium_current__ass = 1.0 / (1.0 + exp((-(var_slow_transient_outward_potassium_current__V + 22.5)) / 7.7));
    const double var_slow_transient_outward_potassium_current__iss = 1.0 / (1.0 + exp((var_slow_transient_outward_potassium_current__V + 45.2) / 5.7));
    const double var_slow_transient_outward_potassium_current__tau_ta_s = (0.493 * exp((-0.0629) * var_slow_transient_outward_potassium_current__V)) + 2.058;
    const double var_slow_transient_outward_potassium_current__tau_ti_s = 270.0 + (1050.0 / (1.0 + exp((var_slow_transient_outward_potassium_current__V + 45.2) / 5.7)));
    const double var_slow_delayed_rectifier_potassium_current__alpha_n = (4.81333e-06 * (var_slow_delayed_rectifier_potassium_current__V + 26.5)) / (1.0 - exp((-0.128) * (var_slow_delayed_rectifier_potassium_current__V + 26.5)));
    const double var_slow_delayed_rectifier_potassium_current__beta_n = 9.53333e-05 * exp((-0.038) * (var_slow_delayed_rectifier_potassium_current__V + 26.5));
    const double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__tau_aur = (0.493 * exp((-0.0629) * var_ultra_rapidly_activating_delayed_rectifier_potassium_current__V)) + 2.058;
    const double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__tau_iur = 1200.0 - (170.0 / (1.0 + exp((var_ultra_rapidly_activating_delayed_rectifier_potassium_current__V + 45.2) / 5.7)));
    const double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__ass = var_slow_transient_outward_potassium_current__ass;
    const double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__iss = var_slow_transient_outward_potassium_current__iss;
    const double var_non_inactivating_steady_state_potassium_current__tau_Kss = (39.3 * exp((-0.0862) * var_non_inactivating_steady_state_potassium_current__V)) + 13.17;
    const double var_non_inactivating_steady_state_potassium_current__ass = var_slow_transient_outward_potassium_current__ass;
    const double var_rapid_delayed_rectifier_potassium_current__C_K0 = 1.0 - (var_rapid_delayed_rectifier_potassium_current__C_K1 + var_rapid_delayed_rectifier_potassium_current__C_K2 + var_rapid_delayed_rectifier_potassium_current__O_K + var_rapid_delayed_rectifier_potassium_current__I_K);
    const double var_rapid_delayed_rectifier_potassium_current__alpha_a0 = 0.022348 * exp(0.01176 * var_rapid_delayed_rectifier_potassium_current__V);
    const double var_rapid_delayed_rectifier_potassium_current__beta_a0 = 0.047002 * exp((-0.0631) * var_rapid_delayed_rectifier_potassium_current__V);
    const double var_rapid_delayed_rectifier_potassium_current__kb = 0.036778;
    const double var_rapid_delayed_rectifier_potassium_current__kf = 0.023761;
    const double var_rapid_delayed_rectifier_potassium_current__alpha_a1 = 0.013733 * exp(0.038198 * var_rapid_delayed_rectifier_potassium_current__V);
    const double var_rapid_delayed_rectifier_potassium_current__beta_a1 = 6.89e-05 * exp((-0.04178) * var_rapid_delayed_rectifier_potassium_current__V);
    const double var_rapid_delayed_rectifier_potassium_current__alpha_i = 0.090821 * exp(0.023391 * (var_rapid_delayed_rectifier_potassium_current__V + 5.0));
    const double var_rapid_delayed_rectifier_potassium_current__beta_i = 0.006497 * exp((-0.03268) * (var_rapid_delayed_rectifier_potassium_current__V + 5.0));
    
    const double d_dt_membrane__V = -(var_membrane__i_CaL + var_membrane__i_pCa + var_membrane__i_NaCa + var_membrane__i_Cab + var_membrane__i_Na + var_membrane__i_Nab + var_membrane__i_NaK + var_membrane__i_Kto_f + var_membrane__i_Kto_s + var_membrane__i_K1 + var_membrane__i_Ks + var_membrane__i_Kur + var_membrane__i_Kss + var_membrane__i_Kr + var_membrane__i_ClCa + var_membrane__i_stim);
    const double d_dt_calcium_concentration__Cai = var_calcium_concentration__Bi * ((var_calcium_concentration__J_leak + var_calcium_concentration__J_xfer) - (var_calcium_concentration__J_up + var_calcium_concentration__J_trpn + ((((var_calcium_concentration__i_Cab + var_calcium_concentration__i_pCa) - (2.0 * var_calcium_concentration__i_NaCa)) * var_calcium_concentration__Acap * var_calcium_concentration__Cm) / (2.0 * var_calcium_concentration__Vmyo * var_calcium_concentration__F))));
    const double d_dt_calcium_concentration__Cass = var_calcium_concentration__Bss * (((var_calcium_concentration__J_rel * var_calcium_concentration__VJSR) / var_calcium_concentration__Vss) - (((var_calcium_concentration__J_xfer * var_calcium_concentration__Vmyo) / var_calcium_concentration__Vss) + ((var_calcium_concentration__i_CaL * var_calcium_concentration__Acap * var_calcium_concentration__Cm) / (2.0 * var_calcium_concentration__Vss * var_calcium_concentration__F))));
    const double d_dt_calcium_concentration__CaJSR = var_calcium_concentration__BJSR * (var_calcium_concentration__J_tr - var_calcium_concentration__J_rel);
    const double d_dt_calcium_concentration__CaNSR = (((var_calcium_concentration__J_up - var_calcium_concentration__J_leak) * var_calcium_concentration__Vmyo) / var_calcium_concentration__VNSR) - ((var_calcium_concentration__J_tr * var_calcium_concentration__VJSR) / var_calcium_concentration__VNSR);
    const double d_dt_calcium_fluxes__P_RyR = ((-0.04) * var_calcium_fluxes__P_RyR) - (((0.1 * var_calcium_fluxes__i_CaL) / var_calcium_fluxes__i_CaL_max) * exp((-pow(var_calcium_fluxes__V - 5.0, 2.0)) / 648.0));
    const double d_dt_calcium_buffering__LTRPN_Ca = (var_calcium_buffering__k_plus_ltrpn * var_calcium_buffering__Cai * (var_calcium_buffering__LTRPN_tot - var_calcium_buffering__LTRPN_Ca)) - (var_calcium_buffering__k_minus_ltrpn * var_calcium_buffering__LTRPN_Ca);
    const double d_dt_calcium_buffering__HTRPN_Ca = (var_calcium_buffering__k_plus_htrpn * var_calcium_buffering__Cai * (var_calcium_buffering__HTRPN_tot - var_calcium_buffering__HTRPN_Ca)) - (var_calcium_buffering__k_minus_htrpn * var_calcium_buffering__HTRPN_Ca);
    const double d_dt_ryanodine_receptors__P_O1 = ((var_ryanodine_receptors__k_plus_a * pow(var_ryanodine_receptors__Cass, var_ryanodine_receptors__n) * var_ryanodine_receptors__P_C1) + (var_ryanodine_receptors__k_minus_b * var_ryanodine_receptors__P_O2) + (var_ryanodine_receptors__k_minus_c * var_ryanodine_receptors__P_C2)) - ((var_ryanodine_receptors__k_minus_a * var_ryanodine_receptors__P_O1) + (var_ryanodine_receptors__k_plus_b * pow(var_ryanodine_receptors__Cass, var_ryanodine_receptors__m) * var_ryanodine_receptors__P_O1) + (var_ryanodine_receptors__k_plus_c * var_ryanodine_receptors__P_O1));
    const double d_dt_ryanodine_receptors__P_O2 = (var_ryanodine_receptors__k_plus_b * pow(var_ryanodine_receptors__Cass, var_ryanodine_receptors__m) * var_ryanodine_receptors__P_O1) - (var_ryanodine_receptors__k_minus_b * var_ryanodine_receptors__P_O2);
    const double d_dt_ryanodine_receptors__P_C2 = (var_ryanodine_receptors__k_plus_c * var_ryanodine_receptors__P_O1) - (var_ryanodine_receptors__k_minus_c * var_ryanodine_receptors__P_C2);
    const double d_dt_L_type_calcium_current__O = ((var_L_type_calcium_current__alpha * var_L_type_calcium_current__C4) + (var_L_type_calcium_current__Kpcb * var_L_type_calcium_current__I1) + (0.001 * ((var_L_type_calcium_current__alpha * var_L_type_calcium_current__I2) - (var_L_type_calcium_current__Kpcf * var_L_type_calcium_current__O)))) - ((4.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__O) + (var_L_type_calcium_current__gamma * var_L_type_calcium_current__O));
    const double d_dt_L_type_calcium_current__C2 = ((4.0 * var_L_type_calcium_current__alpha * var_L_type_calcium_current__C1) + (2.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__C3)) - ((var_L_type_calcium_current__beta * var_L_type_calcium_current__C2) + (3.0 * var_L_type_calcium_current__alpha * var_L_type_calcium_current__C2));
    const double d_dt_L_type_calcium_current__C3 = ((3.0 * var_L_type_calcium_current__alpha * var_L_type_calcium_current__C2) + (3.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__C4)) - ((2.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__C3) + (2.0 * var_L_type_calcium_current__alpha * var_L_type_calcium_current__C3));
    const double d_dt_L_type_calcium_current__C4 = ((2.0 * var_L_type_calcium_current__alpha * var_L_type_calcium_current__C3) + (4.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__O) + (0.01 * ((4.0 * var_L_type_calcium_current__Kpcb * var_L_type_calcium_current__beta * var_L_type_calcium_current__I1) - (var_L_type_calcium_current__alpha * var_L_type_calcium_current__gamma * var_L_type_calcium_current__C4))) + (0.002 * ((4.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__I2) - (var_L_type_calcium_current__Kpcf * var_L_type_calcium_current__C4))) + (4.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__Kpcb * var_L_type_calcium_current__I3)) - ((3.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__C4) + (var_L_type_calcium_current__alpha * var_L_type_calcium_current__C4) + (1.0 * var_L_type_calcium_current__gamma * var_L_type_calcium_current__Kpcf * var_L_type_calcium_current__C4));
    const double d_dt_L_type_calcium_current__I1 = ((var_L_type_calcium_current__gamma * var_L_type_calcium_current__O) + (0.001 * ((var_L_type_calcium_current__alpha * var_L_type_calcium_current__I3) - (var_L_type_calcium_current__Kpcf * var_L_type_calcium_current__I1))) + (0.01 * ((var_L_type_calcium_current__alpha * var_L_type_calcium_current__gamma * var_L_type_calcium_current__C4) - (4.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__Kpcf * var_L_type_calcium_current__I1)))) - (var_L_type_calcium_current__Kpcb * var_L_type_calcium_current__I1);
    const double d_dt_L_type_calcium_current__I2 = ((0.001 * ((var_L_type_calcium_current__Kpcf * var_L_type_calcium_current__O) - (var_L_type_calcium_current__alpha * var_L_type_calcium_current__I2))) + (var_L_type_calcium_current__Kpcb * var_L_type_calcium_current__I3) + (0.002 * ((var_L_type_calcium_current__Kpcf * var_L_type_calcium_current__C4) - (4.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__I2)))) - (var_L_type_calcium_current__gamma * var_L_type_calcium_current__I2);
    const double d_dt_L_type_calcium_current__I3 = ((0.001 * ((var_L_type_calcium_current__Kpcf * var_L_type_calcium_current__I1) - (var_L_type_calcium_current__alpha * var_L_type_calcium_current__I3))) + (var_L_type_calcium_current__gamma * var_L_type_calcium_current__I2) + (1.0 * var_L_type_calcium_current__gamma * var_L_type_calcium_current__Kpcf * var_L_type_calcium_current__C4)) - ((4.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__Kpcb * var_L_type_calcium_current__I3) + (var_L_type_calcium_current__Kpcb * var_L_type_calcium_current__I3));
    const double d_dt_sodium_concentration__Nai = ((-(var_sodium_concentration__i_Na + var_sodium_concentration__i_Nab + (3.0 * var_sodium_concentration__i_NaK) + (3.0 * var_sodium_concentration__i_NaCa))) * var_sodium_concentration__Acap * var_sodium_concentration__Cm) / (var_sodium_concentration__Vmyo * var_sodium_concentration__F);
    const double d_dt_fast_sodium_current__C_Na2 = ((var_fast_sodium_current__alpha_Na11 * var_fast_sodium_current__C_Na3) + (var_fast_sodium_current__beta_Na12 * var_fast_sodium_current__C_Na1) + (var_fast_sodium_current__alpha_Na3 * var_fast_sodium_current__IC_Na2)) - ((var_fast_sodium_current__beta_Na11 * var_fast_sodium_current__C_Na2) + (var_fast_sodium_current__alpha_Na12 * var_fast_sodium_current__C_Na2) + (var_fast_sodium_current__beta_Na3 * var_fast_sodium_current__C_Na2));
    const double d_dt_fast_sodium_current__C_Na1 = ((var_fast_sodium_current__alpha_Na12 * var_fast_sodium_current__C_Na2) + (var_fast_sodium_current__beta_Na13 * var_fast_sodium_current__O_Na) + (var_fast_sodium_current__alpha_Na3 * var_fast_sodium_current__IF_Na)) - ((var_fast_sodium_current__beta_Na12 * var_fast_sodium_current__C_Na1) + (var_fast_sodium_current__alpha_Na13 * var_fast_sodium_current__C_Na1) + (var_fast_sodium_current__beta_Na3 * var_fast_sodium_current__C_Na1));
    const double d_dt_fast_sodium_current__O_Na = ((var_fast_sodium_current__alpha_Na13 * var_fast_sodium_current__C_Na1) + (var_fast_sodium_current__beta_Na2 * var_fast_sodium_current__IF_Na)) - ((var_fast_sodium_current__beta_Na13 * var_fast_sodium_current__O_Na) + (var_fast_sodium_current__alpha_Na2 * var_fast_sodium_current__O_Na));
    const double d_dt_fast_sodium_current__IF_Na = ((var_fast_sodium_current__alpha_Na2 * var_fast_sodium_current__O_Na) + (var_fast_sodium_current__beta_Na3 * var_fast_sodium_current__C_Na1) + (var_fast_sodium_current__beta_Na4 * var_fast_sodium_current__I1_Na) + (var_fast_sodium_current__alpha_Na12 * var_fast_sodium_current__IC_Na2)) - ((var_fast_sodium_current__beta_Na2 * var_fast_sodium_current__IF_Na) + (var_fast_sodium_current__alpha_Na3 * var_fast_sodium_current__IF_Na) + (var_fast_sodium_current__alpha_Na4 * var_fast_sodium_current__IF_Na) + (var_fast_sodium_current__beta_Na12 * var_fast_sodium_current__IF_Na));
    const double d_dt_fast_sodium_current__I1_Na = ((var_fast_sodium_current__alpha_Na4 * var_fast_sodium_current__IF_Na) + (var_fast_sodium_current__beta_Na5 * var_fast_sodium_current__I2_Na)) - ((var_fast_sodium_current__beta_Na4 * var_fast_sodium_current__I1_Na) + (var_fast_sodium_current__alpha_Na5 * var_fast_sodium_current__I1_Na));
    const double d_dt_fast_sodium_current__I2_Na = (var_fast_sodium_current__alpha_Na5 * var_fast_sodium_current__I1_Na) - (var_fast_sodium_current__beta_Na5 * var_fast_sodium_current__I2_Na);
    const double d_dt_fast_sodium_current__IC_Na2 = ((var_fast_sodium_current__alpha_Na11 * var_fast_sodium_current__IC_Na3) + (var_fast_sodium_current__beta_Na12 * var_fast_sodium_current__IF_Na) + (var_fast_sodium_current__beta_Na3 * var_fast_sodium_current__IC_Na2)) - ((var_fast_sodium_current__beta_Na11 * var_fast_sodium_current__IC_Na2) + (var_fast_sodium_current__alpha_Na12 * var_fast_sodium_current__IC_Na2) + (var_fast_sodium_current__alpha_Na3 * var_fast_sodium_current__IC_Na2));
    const double d_dt_fast_sodium_current__IC_Na3 = ((var_fast_sodium_current__beta_Na11 * var_fast_sodium_current__IC_Na2) + (var_fast_sodium_current__beta_Na3 * var_fast_sodium_current__C_Na3)) - ((var_fast_sodium_current__alpha_Na11 * var_fast_sodium_current__IC_Na3) + (var_fast_sodium_current__alpha_Na3 * var_fast_sodium_current__IC_Na3));
    const double d_dt_potassium_concentration__Ki = ((-((var_potassium_concentration__i_Kto_f + var_potassium_concentration__i_Kto_s + var_potassium_concentration__i_K1 + var_potassium_concentration__i_Ks + var_potassium_concentration__i_Kss + var_potassium_concentration__i_Kur + var_potassium_concentration__i_Kr) - (2.0 * var_potassium_concentration__i_NaK))) * var_potassium_concentration__Acap * var_potassium_concentration__Cm) / (var_potassium_concentration__Vmyo * var_potassium_concentration__F);
    const double d_dt_fast_transient_outward_potassium_current__ato_f = (var_fast_transient_outward_potassium_current__alpha_a * (1.0 - var_fast_transient_outward_potassium_current__ato_f)) - (var_fast_transient_outward_potassium_current__beta_a * var_fast_transient_outward_potassium_current__ato_f);
    const double d_dt_fast_transient_outward_potassium_current__ito_f = (var_fast_transient_outward_potassium_current__alpha_i * (1.0 - var_fast_transient_outward_potassium_current__ito_f)) - (var_fast_transient_outward_potassium_current__beta_i * var_fast_transient_outward_potassium_current__ito_f);
    const double d_dt_slow_transient_outward_potassium_current__ato_s = (var_slow_transient_outward_potassium_current__ass - var_slow_transient_outward_potassium_current__ato_s) / var_slow_transient_outward_potassium_current__tau_ta_s;
    const double d_dt_slow_transient_outward_potassium_current__ito_s = (var_slow_transient_outward_potassium_current__iss - var_slow_transient_outward_potassium_current__ito_s) / var_slow_transient_outward_potassium_current__tau_ti_s;
    const double d_dt_slow_delayed_rectifier_potassium_current__nKs = (var_slow_delayed_rectifier_potassium_current__alpha_n * (1.0 - var_slow_delayed_rectifier_potassium_current__nKs)) - (var_slow_delayed_rectifier_potassium_current__beta_n * var_slow_delayed_rectifier_potassium_current__nKs);
    const double d_dt_ultra_rapidly_activating_delayed_rectifier_potassium_current__aur = (var_ultra_rapidly_activating_delayed_rectifier_potassium_current__ass - var_ultra_rapidly_activating_delayed_rectifier_potassium_current__aur) / var_ultra_rapidly_activating_delayed_rectifier_potassium_current__tau_aur;
    const double d_dt_ultra_rapidly_activating_delayed_rectifier_potassium_current__iur = (var_ultra_rapidly_activating_delayed_rectifier_potassium_current__iss - var_ultra_rapidly_activating_delayed_rectifier_potassium_current__iur) / var_ultra_rapidly_activating_delayed_rectifier_potassium_current__tau_iur;
    const double d_dt_non_inactivating_steady_state_potassium_current__aKss = (var_non_inactivating_steady_state_potassium_current__ass - var_non_inactivating_steady_state_potassium_current__aKss) / var_non_inactivating_steady_state_potassium_current__tau_Kss;
    const double d_dt_non_inactivating_steady_state_potassium_current__iKss = 0.0;
    const double d_dt_rapid_delayed_rectifier_potassium_current__C_K2 = ((var_rapid_delayed_rectifier_potassium_current__kf * var_rapid_delayed_rectifier_potassium_current__C_K1) + (var_rapid_delayed_rectifier_potassium_current__beta_a1 * var_rapid_delayed_rectifier_potassium_current__O_K)) - ((var_rapid_delayed_rectifier_potassium_current__kb * var_rapid_delayed_rectifier_potassium_current__C_K2) + (var_rapid_delayed_rectifier_potassium_current__alpha_a1 * var_rapid_delayed_rectifier_potassium_current__C_K2));
    const double d_dt_rapid_delayed_rectifier_potassium_current__C_K1 = ((var_rapid_delayed_rectifier_potassium_current__alpha_a0 * var_rapid_delayed_rectifier_potassium_current__C_K0) + (var_rapid_delayed_rectifier_potassium_current__kb * var_rapid_delayed_rectifier_potassium_current__C_K2)) - ((var_rapid_delayed_rectifier_potassium_current__beta_a0 * var_rapid_delayed_rectifier_potassium_current__C_K1) + (var_rapid_delayed_rectifier_potassium_current__kf * var_rapid_delayed_rectifier_potassium_current__C_K1));
    const double d_dt_rapid_delayed_rectifier_potassium_current__O_K = ((var_rapid_delayed_rectifier_potassium_current__alpha_a1 * var_rapid_delayed_rectifier_potassium_current__C_K2) + (var_rapid_delayed_rectifier_potassium_current__beta_i * var_rapid_delayed_rectifier_potassium_current__I_K)) - ((var_rapid_delayed_rectifier_potassium_current__beta_a1 * var_rapid_delayed_rectifier_potassium_current__O_K) + (var_rapid_delayed_rectifier_potassium_current__alpha_i * var_rapid_delayed_rectifier_potassium_current__O_K));
    const double d_dt_rapid_delayed_rectifier_potassium_current__I_K = (var_rapid_delayed_rectifier_potassium_current__alpha_i * var_rapid_delayed_rectifier_potassium_current__O_K) - (var_rapid_delayed_rectifier_potassium_current__beta_i * var_rapid_delayed_rectifier_potassium_current__I_K);
    
    classe->V_lado_direito_ = d_dt_membrane__V;
    classe->Cai_lado_direito_ = d_dt_calcium_concentration__Cai;
    classe->Cass_lado_direito_ = d_dt_calcium_concentration__Cass;
    classe->CaJSR_lado_direito_ = d_dt_calcium_concentration__CaJSR;
    classe->CaNSR_lado_direito_ = d_dt_calcium_concentration__CaNSR;
    classe->P_RyR_lado_direito_ = d_dt_calcium_fluxes__P_RyR;
    classe->LTRPN_Ca_lado_direito_ = d_dt_calcium_buffering__LTRPN_Ca;
    classe->HTRPN_Ca_lado_direito_ = d_dt_calcium_buffering__HTRPN_Ca;
    classe->P_O1_lado_direito_ = d_dt_ryanodine_receptors__P_O1;
    classe->P_O2_lado_direito_ = d_dt_ryanodine_receptors__P_O2;
    classe->P_C2_lado_direito_ = d_dt_ryanodine_receptors__P_C2;
    classe->O_lado_direito_ = d_dt_L_type_calcium_current__O;
    classe->C2_lado_direito_ = d_dt_L_type_calcium_current__C2;
    classe->C3_lado_direito_ = d_dt_L_type_calcium_current__C3;
    classe->C4_lado_direito_ = d_dt_L_type_calcium_current__C4;
    classe->I1_lado_direito_ = d_dt_L_type_calcium_current__I1;
    classe->I2_lado_direito_ = d_dt_L_type_calcium_current__I2;
    classe->I3_lado_direito_ = d_dt_L_type_calcium_current__I3;
    classe->Nai_lado_direito_ = d_dt_sodium_concentration__Nai;
    classe->O_Na_lado_direito_ = d_dt_fast_sodium_current__O_Na;
    classe->C_Na1_lado_direito_ = d_dt_fast_sodium_current__C_Na1;
    classe->C_Na2_lado_direito_ = d_dt_fast_sodium_current__C_Na2;
    classe->I1_Na_lado_direito_ = d_dt_fast_sodium_current__I1_Na;
    classe->I2_Na_lado_direito_ = d_dt_fast_sodium_current__I2_Na;
    classe->IF_Na_lado_direito_ = d_dt_fast_sodium_current__IF_Na;
    classe->IC_Na2_lado_direito_ = d_dt_fast_sodium_current__IC_Na2;
    classe->IC_Na3_lado_direito_ = d_dt_fast_sodium_current__IC_Na3;
    classe->Ki_lado_direito_ = d_dt_potassium_concentration__Ki;
    classe->ato_f_lado_direito_ = d_dt_fast_transient_outward_potassium_current__ato_f;
    classe->ito_f_lado_direito_ = d_dt_fast_transient_outward_potassium_current__ito_f;
    classe->ato_s_lado_direito_ = d_dt_slow_transient_outward_potassium_current__ato_s;
    classe->ito_s_lado_direito_ = d_dt_slow_transient_outward_potassium_current__ito_s;
    classe->nKs_lado_direito_ = d_dt_slow_delayed_rectifier_potassium_current__nKs;
    classe->aur_lado_direito_ = d_dt_ultra_rapidly_activating_delayed_rectifier_potassium_current__aur;
    classe->iur_lado_direito_ = d_dt_ultra_rapidly_activating_delayed_rectifier_potassium_current__iur;
    classe->aKss_lado_direito_ = d_dt_non_inactivating_steady_state_potassium_current__aKss;
    classe->iKss_lado_direito_ = d_dt_non_inactivating_steady_state_potassium_current__iKss;
    classe->O_K_lado_direito_ = d_dt_rapid_delayed_rectifier_potassium_current__O_K;
    classe->C_K1_lado_direito_ = d_dt_rapid_delayed_rectifier_potassium_current__C_K1;
    classe->C_K2_lado_direito_ = d_dt_rapid_delayed_rectifier_potassium_current__C_K2;
    classe->I_K_lado_direito_ = d_dt_rapid_delayed_rectifier_potassium_current__I_K;
};


#endif
