#ifndef _CML_zhang_SAN_model_2000_all_
#define _CML_zhang_SAN_model_2000_all_

//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: zhang_SAN_model_2000_all
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translate: 1844, pycml: 1844)
//! on Sun Jun 26 21:57:43 2011
//! 
//! <autogenerated>



void __equation__(Solveode *classe)
{
    // Inputs:
    // Time units: second
    double var_environment__time= classe->time_new;
    double var_membrane__V = classe->V_old_; //var_membrane
    // Units: millivolt; Initial value: -39.013558536
    double var_sodium_current_m_gate__m = classe->m_old_; //var_sodium_current_m_gate
    // Units: dimensionless; Initial value: 0.092361701692
    double var_sodium_current_h_gate__h1 = classe->h1_old_; //var_sodium_current_h_gate
    // Units: dimensionless; Initial value: 0.015905380261
    double var_sodium_current_h_gate__h2 = classe->h2_old_; //var_sodium_current_h_gate
    // Units: dimensionless; Initial value: 0.01445216109
    double var_L_type_Ca_channel_d_gate__d_L = classe->d_L_old_; //var_L_type_Ca_channel_d_gate
    // Units: dimensionless; Initial value: 0.04804900895
    double var_L_type_Ca_channel_f_gate__f_L = classe->f_L_old_; //var_L_type_Ca_channel_f_gate
    // Units: dimensionless; Initial value: 0.48779845203
    double var_T_type_Ca_channel_d_gate__d_T = classe->d_T_old_; //var_T_type_Ca_channel_d_gate
    // Units: dimensionless; Initial value: 0.42074047435
    double var_T_type_Ca_channel_f_gate__f_T = classe->f_T_old_; //var_T_type_Ca_channel_f_gate
    // Units: dimensionless; Initial value: 0.038968420558
    double var_four_AP_sensitive_currents_q_gate__q = classe->q_old_; //var_four_AP_sensitive_currents_q_gate
    // Units: dimensionless; Initial value: 0.29760539675
    double var_four_AP_sensitive_currents_r_gate__r = classe->r_old_; //var_four_AP_sensitive_currents_r_gate
    // Units: dimensionless; Initial value: 0.064402950262
    double var_rapid_delayed_rectifying_potassium_current_P_af_gate__P_af = classe->P_af_old_; //var_rapid_delayed_rectifying_potassium_current_P_af_gate
    // Units: dimensionless; Initial value: 0.13034201158
    double var_rapid_delayed_rectifying_potassium_current_P_as_gate__P_as = classe->P_as_old_; //var_rapid_delayed_rectifying_potassium_current_P_as_gate
    // Units: dimensionless; Initial value: 0.46960956028
    double var_rapid_delayed_rectifying_potassium_current_P_i_gate__P_i = classe->P_i_old_; //var_rapid_delayed_rectifying_potassium_current_P_i_gate
    // Units: dimensionless; Initial value: 0.87993375273
    double var_slow_delayed_rectifying_potassium_current_xs_gate__xs = classe->xs_old_; //var_slow_delayed_rectifying_potassium_current_xs_gate
    // Units: dimensionless; Initial value: 0.082293827208
    double var_hyperpolarisation_activated_current_y_gate__y = classe->y_old_; //var_hyperpolarisation_activated_current_y_gate
    // Units: dimensionless; Initial value: 0.03889291759
    
    
    // Mathematics
    const double var_membrane__Version = 1.0;
    const double var_membrane__dCell = 0.0;
    const double var_membrane__FCellConstant = 1.0309347;
    const double var_membrane__FCell = (var_membrane__Version == 0.0) ? ((1.07 * ((3.0 * var_membrane__dCell) - 0.1)) / (3.0 * (1.0 + (0.7745 * exp((-((3.0 * var_membrane__dCell) - 2.05)) / 0.295))))) : (var_membrane__Version == 1.0) ? ((var_membrane__FCellConstant * var_membrane__dCell) / (1.0 + (0.7745 * exp((-((3.0 * var_membrane__dCell) - 2.05)) / 0.295)))) : ((1.07 * 29.0 * var_membrane__dCell) / (30.0 * (1.0 + (0.7745 * exp((-((29.0 * var_membrane__dCell) - 24.5)) / 1.95)))));
    const double var_membrane__R = 8314.0;
    const double var_membrane__T = 310.0;
    const double var_membrane__F = 96845.0;
    const double var_membrane__CmPeriphery = 6.5e-05;
    const double var_membrane__CmCentre = 2e-05;
    const double var_membrane__Cm = var_membrane__CmCentre + (var_membrane__FCell * (var_membrane__CmPeriphery - var_membrane__CmCentre));
    const double var_ionic_concentrations__Na_o = 140.0;
    const double var_sodium_current__Na_o = var_ionic_concentrations__Na_o;
    const double var_reversal_and_equilibrium_potentials__R = var_membrane__R;
    const double var_reversal_and_equilibrium_potentials__Na_o = var_ionic_concentrations__Na_o;
    const double var_reversal_and_equilibrium_potentials__T = var_membrane__T;
    const double var_ionic_concentrations__Na_i = 8.0;
    const double var_reversal_and_equilibrium_potentials__Na_i = var_ionic_concentrations__Na_i;
    const double var_reversal_and_equilibrium_potentials__F = var_membrane__F;
    const double var_reversal_and_equilibrium_potentials__E_Na = ((var_reversal_and_equilibrium_potentials__R * var_reversal_and_equilibrium_potentials__T) / var_reversal_and_equilibrium_potentials__F) * log(var_reversal_and_equilibrium_potentials__Na_o / var_reversal_and_equilibrium_potentials__Na_i);
    const double var_sodium_current__E_Na = var_reversal_and_equilibrium_potentials__E_Na;
    const double var_sodium_current__m = var_sodium_current_m_gate__m;
    const double var_sodium_current__V = var_membrane__V;
    const double var_sodium_current_h_gate__V = var_sodium_current__V;
    const double var_sodium_current__Version = var_membrane__Version;
    const double var_sodium_current_h_gate__Version = var_sodium_current__Version;
    const double var_sodium_current_h_gate__F_Na = (var_sodium_current_h_gate__Version == 0.0) ? (((0.0952 * exp((-0.063) * (var_sodium_current_h_gate__V + 34.4))) / (1.0 + (1.66 * exp((-0.225) * (var_sodium_current_h_gate__V + 63.7))))) + 0.0869) : (((0.09518 * exp((-0.06306) * (var_sodium_current_h_gate__V + 34.4))) / (1.0 + (1.662 * exp((-0.2251) * (var_sodium_current_h_gate__V + 63.7))))) + 0.08693);
    const double var_sodium_current_h_gate__h = ((1.0 - var_sodium_current_h_gate__F_Na) * var_sodium_current_h_gate__h1) + (var_sodium_current_h_gate__F_Na * var_sodium_current_h_gate__h2);
    const double var_sodium_current__h = var_sodium_current_h_gate__h;
    const double var_sodium_current__F = var_membrane__F;
    const double var_sodium_current__g_Na_Centre_1DCapable = 0.0;
    const double var_sodium_current__g_Na_Centre_Published = 0.0;
    const double var_sodium_current__FCell = var_membrane__FCell;
    const double var_sodium_current__g_Na_Periphery_1DCapable = 3.7e-07;
    const double var_sodium_current__g_Na_Periphery_Published = 1.2e-06;
    const double var_sodium_current__g_Na_Centre_0DCapable = 0.0;
    const double var_sodium_current__g_Na_Periphery_0DCapable = 1.204e-06;
    const double var_sodium_current__g_Na = (var_sodium_current__Version == 0.0) ? (var_sodium_current__g_Na_Centre_Published + (var_sodium_current__FCell * (var_sodium_current__g_Na_Periphery_Published - var_sodium_current__g_Na_Centre_Published))) : (var_sodium_current__Version == 1.0) ? (var_sodium_current__g_Na_Centre_0DCapable + (var_sodium_current__FCell * (var_sodium_current__g_Na_Periphery_0DCapable - var_sodium_current__g_Na_Centre_0DCapable))) : (var_sodium_current__g_Na_Centre_1DCapable + (var_sodium_current__FCell * (var_sodium_current__g_Na_Periphery_1DCapable - var_sodium_current__g_Na_Centre_1DCapable)));
    const double var_sodium_current__T = var_membrane__T;
    const double var_sodium_current__R = var_membrane__R;
    const double var_sodium_current__i_Na = ((((var_sodium_current__g_Na * pow(var_sodium_current__m, 3.0) * var_sodium_current__h * var_sodium_current__Na_o * pow(var_sodium_current__F, 2.0)) / (var_sodium_current__R * var_sodium_current__T)) * (exp(((var_sodium_current__V - var_sodium_current__E_Na) * var_sodium_current__F) / (var_sodium_current__R * var_sodium_current__T)) - 1.0)) / (exp((var_sodium_current__V * var_sodium_current__F) / (var_sodium_current__R * var_sodium_current__T)) - 1.0)) * var_sodium_current__V;
    const double var_membrane__i_Na = var_sodium_current__i_Na;
    const double var_L_type_Ca_channel__E_Ca_L = 46.4;
    const double var_L_type_Ca_channel__g_Ca_L_Periphery_Published = 0.0659;
    const double var_L_type_Ca_channel__Version = var_membrane__Version;
    const double var_L_type_Ca_channel__FCell = var_membrane__FCell;
    const double var_L_type_Ca_channel__g_Ca_L_Centre_Published = 0.0058;
    const double var_L_type_Ca_channel__g_Ca_L_Centre_1DCapable = 0.0082;
    const double var_L_type_Ca_channel__g_Ca_L_Periphery_0DCapable = 0.06588648;
    const double var_L_type_Ca_channel__g_Ca_L_Periphery_1DCapable = 0.0659;
    const double var_L_type_Ca_channel__g_Ca_L_Centre_0DCapable = 0.0057938;
    const double var_L_type_Ca_channel__g_Ca_L = (var_L_type_Ca_channel__Version == 0.0) ? (var_L_type_Ca_channel__g_Ca_L_Centre_Published + (var_L_type_Ca_channel__FCell * (var_L_type_Ca_channel__g_Ca_L_Periphery_Published - var_L_type_Ca_channel__g_Ca_L_Centre_Published))) : (var_L_type_Ca_channel__Version == 1.0) ? (var_L_type_Ca_channel__g_Ca_L_Centre_0DCapable + (var_L_type_Ca_channel__FCell * (var_L_type_Ca_channel__g_Ca_L_Periphery_0DCapable - var_L_type_Ca_channel__g_Ca_L_Centre_0DCapable))) : (var_L_type_Ca_channel__g_Ca_L_Centre_1DCapable + (var_L_type_Ca_channel__FCell * (var_L_type_Ca_channel__g_Ca_L_Periphery_1DCapable - var_L_type_Ca_channel__g_Ca_L_Centre_1DCapable)));
    const double var_L_type_Ca_channel__d_L = var_L_type_Ca_channel_d_gate__d_L;
    const double var_L_type_Ca_channel__f_L = var_L_type_Ca_channel_f_gate__f_L;
    const double var_L_type_Ca_channel__V = var_membrane__V;
    const double var_L_type_Ca_channel__i_Ca_L = var_L_type_Ca_channel__g_Ca_L * ((var_L_type_Ca_channel__f_L * var_L_type_Ca_channel__d_L) + (0.006 / (1.0 + exp((-(var_L_type_Ca_channel__V + 14.1)) / 6.0)))) * (var_L_type_Ca_channel__V - var_L_type_Ca_channel__E_Ca_L);
    const double var_membrane__i_Ca_L = var_L_type_Ca_channel__i_Ca_L;
    const double var_T_type_Ca_channel__E_Ca_T = 45.0;
    const double var_T_type_Ca_channel__g_Ca_T_Periphery_Published = 0.0139;
    const double var_T_type_Ca_channel__g_Ca_T_Centre_Published = 0.0043;
    const double var_T_type_Ca_channel__g_Ca_T_Centre_1DCapable = 0.0021;
    const double var_T_type_Ca_channel__FCell = var_membrane__FCell;
    const double var_T_type_Ca_channel__g_Ca_T_Periphery_0DCapable = 0.0138823;
    const double var_T_type_Ca_channel__g_Ca_T_Periphery_1DCapable = 0.00694;
    const double var_T_type_Ca_channel__g_Ca_T_Centre_0DCapable = 0.00427806;
    const double var_T_type_Ca_channel__Version = var_membrane__Version;
    const double var_T_type_Ca_channel__g_Ca_T = (var_T_type_Ca_channel__Version == 0.0) ? (var_T_type_Ca_channel__g_Ca_T_Centre_Published + (var_T_type_Ca_channel__FCell * (var_T_type_Ca_channel__g_Ca_T_Periphery_Published - var_T_type_Ca_channel__g_Ca_T_Centre_Published))) : (var_T_type_Ca_channel__Version == 1.0) ? (var_T_type_Ca_channel__g_Ca_T_Centre_0DCapable + (var_T_type_Ca_channel__FCell * (var_T_type_Ca_channel__g_Ca_T_Periphery_0DCapable - var_T_type_Ca_channel__g_Ca_T_Centre_0DCapable))) : (var_T_type_Ca_channel__g_Ca_T_Centre_1DCapable + (var_T_type_Ca_channel__FCell * (var_T_type_Ca_channel__g_Ca_T_Periphery_1DCapable - var_T_type_Ca_channel__g_Ca_T_Centre_1DCapable)));
    const double var_T_type_Ca_channel__d_T = var_T_type_Ca_channel_d_gate__d_T;
    const double var_T_type_Ca_channel__V = var_membrane__V;
    const double var_T_type_Ca_channel__f_T = var_T_type_Ca_channel_f_gate__f_T;
    const double var_T_type_Ca_channel__i_Ca_T = var_T_type_Ca_channel__g_Ca_T * var_T_type_Ca_channel__d_T * var_T_type_Ca_channel__f_T * (var_T_type_Ca_channel__V - var_T_type_Ca_channel__E_Ca_T);
    const double var_membrane__i_Ca_T = var_T_type_Ca_channel__i_Ca_T;
    const double var_four_AP_sensitive_currents__g_to_Periphery_Published = 0.03649;
    const double var_four_AP_sensitive_currents__g_to_Centre_1DCapable = 0.004905;
    const double var_four_AP_sensitive_currents__g_to_Periphery_0DCapable = 0.036495;
    const double var_four_AP_sensitive_currents__FCell = var_membrane__FCell;
    const double var_four_AP_sensitive_currents__g_to_Centre_Published = 0.00491;
    const double var_four_AP_sensitive_currents__g_to_Periphery_1DCapable = 0.0365;
    const double var_four_AP_sensitive_currents__g_to_Centre_0DCapable = 0.004905;
    const double var_four_AP_sensitive_currents__Version = var_membrane__Version;
    const double var_four_AP_sensitive_currents__g_to = (var_four_AP_sensitive_currents__Version == 0.0) ? (var_four_AP_sensitive_currents__g_to_Centre_Published + (var_four_AP_sensitive_currents__FCell * (var_four_AP_sensitive_currents__g_to_Periphery_Published - var_four_AP_sensitive_currents__g_to_Centre_Published))) : (var_four_AP_sensitive_currents__Version == 1.0) ? (var_four_AP_sensitive_currents__g_to_Centre_0DCapable + (var_four_AP_sensitive_currents__FCell * (var_four_AP_sensitive_currents__g_to_Periphery_0DCapable - var_four_AP_sensitive_currents__g_to_Centre_0DCapable))) : (var_four_AP_sensitive_currents__g_to_Centre_1DCapable + (var_four_AP_sensitive_currents__FCell * (var_four_AP_sensitive_currents__g_to_Periphery_1DCapable - var_four_AP_sensitive_currents__g_to_Centre_1DCapable)));
    const double var_four_AP_sensitive_currents__V = var_membrane__V;
    const double var_four_AP_sensitive_currents__q = var_four_AP_sensitive_currents_q_gate__q;
    const double var_ionic_concentrations__K_o = 5.4;
    const double var_reversal_and_equilibrium_potentials__K_o = var_ionic_concentrations__K_o;
    const double var_ionic_concentrations__K_i = 140.0;
    const double var_reversal_and_equilibrium_potentials__K_i = var_ionic_concentrations__K_i;
    const double var_reversal_and_equilibrium_potentials__E_K = ((var_reversal_and_equilibrium_potentials__R * var_reversal_and_equilibrium_potentials__T) / var_reversal_and_equilibrium_potentials__F) * log(var_reversal_and_equilibrium_potentials__K_o / var_reversal_and_equilibrium_potentials__K_i);
    const double var_four_AP_sensitive_currents__E_K = var_reversal_and_equilibrium_potentials__E_K;
    const double var_four_AP_sensitive_currents__r = var_four_AP_sensitive_currents_r_gate__r;
    const double var_four_AP_sensitive_currents__i_to = var_four_AP_sensitive_currents__g_to * var_four_AP_sensitive_currents__q * var_four_AP_sensitive_currents__r * (var_four_AP_sensitive_currents__V - var_four_AP_sensitive_currents__E_K);
    const double var_membrane__i_to = var_four_AP_sensitive_currents__i_to;
    const double var_four_AP_sensitive_currents__g_sus_Periphery_1DCapable = 0.0114;
    const double var_four_AP_sensitive_currents__g_sus_Centre_1DCapable = 0.000266;
    const double var_four_AP_sensitive_currents__g_sus_Centre_Published = 6.65e-05;
    const double var_four_AP_sensitive_currents__g_sus_Centre_0DCapable = 6.645504e-05;
    const double var_four_AP_sensitive_currents__g_sus_Periphery_0DCapable = 0.01138376;
    const double var_four_AP_sensitive_currents__g_sus_Periphery_Published = 0.0114;
    const double var_four_AP_sensitive_currents__g_sus = (var_four_AP_sensitive_currents__Version == 0.0) ? (var_four_AP_sensitive_currents__g_sus_Centre_Published + (var_four_AP_sensitive_currents__FCell * (var_four_AP_sensitive_currents__g_sus_Periphery_Published - var_four_AP_sensitive_currents__g_sus_Centre_Published))) : (var_four_AP_sensitive_currents__Version == 1.0) ? (var_four_AP_sensitive_currents__g_sus_Centre_0DCapable + (var_four_AP_sensitive_currents__FCell * (var_four_AP_sensitive_currents__g_sus_Periphery_0DCapable - var_four_AP_sensitive_currents__g_sus_Centre_0DCapable))) : (var_four_AP_sensitive_currents__g_sus_Centre_1DCapable + (var_four_AP_sensitive_currents__FCell * (var_four_AP_sensitive_currents__g_sus_Periphery_1DCapable - var_four_AP_sensitive_currents__g_sus_Centre_1DCapable)));
    const double var_four_AP_sensitive_currents__i_sus = var_four_AP_sensitive_currents__g_sus * var_four_AP_sensitive_currents__r * (var_four_AP_sensitive_currents__V - var_four_AP_sensitive_currents__E_K);
    const double var_membrane__i_sus = var_four_AP_sensitive_currents__i_sus;
    const double var_rapid_delayed_rectifying_potassium_current__P_as = var_rapid_delayed_rectifying_potassium_current_P_as_gate__P_as;
    const double var_rapid_delayed_rectifying_potassium_current__P_af = var_rapid_delayed_rectifying_potassium_current_P_af_gate__P_af;
    const double var_rapid_delayed_rectifying_potassium_current__P_a = (0.6 * var_rapid_delayed_rectifying_potassium_current__P_af) + (0.4 * var_rapid_delayed_rectifying_potassium_current__P_as);
    const double var_rapid_delayed_rectifying_potassium_current__P_i = var_rapid_delayed_rectifying_potassium_current_P_i_gate__P_i;
    const double var_rapid_delayed_rectifying_potassium_current__V = var_membrane__V;
    const double var_rapid_delayed_rectifying_potassium_current__E_K = var_reversal_and_equilibrium_potentials__E_K;
    const double var_rapid_delayed_rectifying_potassium_current__g_K_r_Periphery_1DCapable = 0.0208;
    const double var_rapid_delayed_rectifying_potassium_current__FCell = var_membrane__FCell;
    const double var_rapid_delayed_rectifying_potassium_current__g_K_r_Centre_1DCapable = 0.000738;
    const double var_rapid_delayed_rectifying_potassium_current__g_K_r_Centre_0DCapable = 0.00079704;
    const double var_rapid_delayed_rectifying_potassium_current__Version = var_membrane__Version;
    const double var_rapid_delayed_rectifying_potassium_current__g_K_r_Periphery_Published = 0.016;
    const double var_rapid_delayed_rectifying_potassium_current__g_K_r_Periphery_0DCapable = 0.016;
    const double var_rapid_delayed_rectifying_potassium_current__g_K_r_Centre_Published = 0.000797;
    const double var_rapid_delayed_rectifying_potassium_current__g_K_r = (var_rapid_delayed_rectifying_potassium_current__Version == 0.0) ? (var_rapid_delayed_rectifying_potassium_current__g_K_r_Centre_Published + (var_rapid_delayed_rectifying_potassium_current__FCell * (var_rapid_delayed_rectifying_potassium_current__g_K_r_Periphery_Published - var_rapid_delayed_rectifying_potassium_current__g_K_r_Centre_Published))) : (var_rapid_delayed_rectifying_potassium_current__Version == 1.0) ? (var_rapid_delayed_rectifying_potassium_current__g_K_r_Centre_0DCapable + (var_rapid_delayed_rectifying_potassium_current__FCell * (var_rapid_delayed_rectifying_potassium_current__g_K_r_Periphery_0DCapable - var_rapid_delayed_rectifying_potassium_current__g_K_r_Centre_0DCapable))) : (var_rapid_delayed_rectifying_potassium_current__g_K_r_Centre_1DCapable + (var_rapid_delayed_rectifying_potassium_current__FCell * (var_rapid_delayed_rectifying_potassium_current__g_K_r_Periphery_1DCapable - var_rapid_delayed_rectifying_potassium_current__g_K_r_Centre_1DCapable)));
    const double var_rapid_delayed_rectifying_potassium_current__i_K_r = var_rapid_delayed_rectifying_potassium_current__g_K_r * var_rapid_delayed_rectifying_potassium_current__P_a * var_rapid_delayed_rectifying_potassium_current__P_i * (var_rapid_delayed_rectifying_potassium_current__V - var_rapid_delayed_rectifying_potassium_current__E_K);
    const double var_membrane__i_K_r = var_rapid_delayed_rectifying_potassium_current__i_K_r;
    const double var_slow_delayed_rectifying_potassium_current__xs = var_slow_delayed_rectifying_potassium_current_xs_gate__xs;
    const double var_slow_delayed_rectifying_potassium_current__g_K_s_Periphery_0DCapable = 0.0104;
    const double var_slow_delayed_rectifying_potassium_current__g_K_s_Centre_Published = 0.000518;
    const double var_slow_delayed_rectifying_potassium_current__Version = var_membrane__Version;
    const double var_slow_delayed_rectifying_potassium_current__FCell = var_membrane__FCell;
    const double var_slow_delayed_rectifying_potassium_current__g_K_s_Centre_0DCapable = 0.0003445;
    const double var_slow_delayed_rectifying_potassium_current__g_K_s_Centre_1DCapable = 0.000345;
    const double var_slow_delayed_rectifying_potassium_current__g_K_s_Periphery_Published = 0.0104;
    const double var_slow_delayed_rectifying_potassium_current__g_K_s_Periphery_1DCapable = 0.0104;
    const double var_slow_delayed_rectifying_potassium_current__g_K_s = (var_slow_delayed_rectifying_potassium_current__Version == 0.0) ? (var_slow_delayed_rectifying_potassium_current__g_K_s_Centre_Published + (var_slow_delayed_rectifying_potassium_current__FCell * (var_slow_delayed_rectifying_potassium_current__g_K_s_Periphery_Published - var_slow_delayed_rectifying_potassium_current__g_K_s_Centre_Published))) : (var_slow_delayed_rectifying_potassium_current__Version == 1.0) ? (var_slow_delayed_rectifying_potassium_current__g_K_s_Centre_0DCapable + (var_slow_delayed_rectifying_potassium_current__FCell * (var_slow_delayed_rectifying_potassium_current__g_K_s_Periphery_0DCapable - var_slow_delayed_rectifying_potassium_current__g_K_s_Centre_0DCapable))) : (var_slow_delayed_rectifying_potassium_current__g_K_s_Centre_1DCapable + (var_slow_delayed_rectifying_potassium_current__FCell * (var_slow_delayed_rectifying_potassium_current__g_K_s_Periphery_1DCapable - var_slow_delayed_rectifying_potassium_current__g_K_s_Centre_1DCapable)));
    const double var_slow_delayed_rectifying_potassium_current__V = var_membrane__V;
    const double var_reversal_and_equilibrium_potentials__Version = var_membrane__Version;
    const double var_reversal_and_equilibrium_potentials__E_K_s = (var_reversal_and_equilibrium_potentials__Version == 0.0) ? (((var_reversal_and_equilibrium_potentials__R * var_reversal_and_equilibrium_potentials__T) / var_reversal_and_equilibrium_potentials__F) * log((var_reversal_and_equilibrium_potentials__K_o + (0.12 * var_reversal_and_equilibrium_potentials__Na_o)) / (var_reversal_and_equilibrium_potentials__K_i + (0.12 * var_reversal_and_equilibrium_potentials__Na_i)))) : (((var_reversal_and_equilibrium_potentials__R * var_reversal_and_equilibrium_potentials__T) / var_reversal_and_equilibrium_potentials__F) * log((var_reversal_and_equilibrium_potentials__K_o + (0.03 * var_reversal_and_equilibrium_potentials__Na_o)) / (var_reversal_and_equilibrium_potentials__K_i + (0.03 * var_reversal_and_equilibrium_potentials__Na_i))));
    const double var_slow_delayed_rectifying_potassium_current__E_K_s = var_reversal_and_equilibrium_potentials__E_K_s;
    const double var_slow_delayed_rectifying_potassium_current__i_K_s = var_slow_delayed_rectifying_potassium_current__g_K_s * pow(var_slow_delayed_rectifying_potassium_current__xs, 2.0) * (var_slow_delayed_rectifying_potassium_current__V - var_slow_delayed_rectifying_potassium_current__E_K_s);
    const double var_membrane__i_K_s = var_slow_delayed_rectifying_potassium_current__i_K_s;
    const double var_hyperpolarisation_activated_current__g_f_Na_Centre_1DCapable = 0.000437;
    const double var_hyperpolarisation_activated_current__g_f_Na_Centre_Published = 0.000548;
    const double var_hyperpolarisation_activated_current__Version = var_membrane__Version;
    const double var_hyperpolarisation_activated_current__g_f_Na_Periphery_0DCapable = 0.006875;
    const double var_hyperpolarisation_activated_current__g_f_Na_Periphery_Published = 0.0069;
    const double var_hyperpolarisation_activated_current__g_f_Na_Centre_0DCapable = 0.0005465;
    const double var_hyperpolarisation_activated_current__g_f_Na_Periphery_1DCapable = 0.0055;
    const double var_hyperpolarisation_activated_current__FCell = var_membrane__FCell;
    const double var_hyperpolarisation_activated_current__g_f_Na = (var_hyperpolarisation_activated_current__Version == 0.0) ? (var_hyperpolarisation_activated_current__g_f_Na_Centre_Published + (var_hyperpolarisation_activated_current__FCell * (var_hyperpolarisation_activated_current__g_f_Na_Periphery_Published - var_hyperpolarisation_activated_current__g_f_Na_Centre_Published))) : (var_hyperpolarisation_activated_current__Version == 1.0) ? (var_hyperpolarisation_activated_current__g_f_Na_Centre_0DCapable + (var_hyperpolarisation_activated_current__FCell * (var_hyperpolarisation_activated_current__g_f_Na_Periphery_0DCapable - var_hyperpolarisation_activated_current__g_f_Na_Centre_0DCapable))) : (var_hyperpolarisation_activated_current__g_f_Na_Centre_1DCapable + (var_hyperpolarisation_activated_current__FCell * (var_hyperpolarisation_activated_current__g_f_Na_Periphery_1DCapable - var_hyperpolarisation_activated_current__g_f_Na_Centre_1DCapable)));
    const double var_hyperpolarisation_activated_current__E_Na = var_reversal_and_equilibrium_potentials__E_Na;
    const double var_hyperpolarisation_activated_current__y = var_hyperpolarisation_activated_current_y_gate__y;
    const double var_hyperpolarisation_activated_current__V = var_membrane__V;
    const double var_hyperpolarisation_activated_current__i_f_Na = (var_hyperpolarisation_activated_current__Version != 2.0) ? (var_hyperpolarisation_activated_current__g_f_Na * var_hyperpolarisation_activated_current__y * (var_hyperpolarisation_activated_current__V - var_hyperpolarisation_activated_current__E_Na)) : (var_hyperpolarisation_activated_current__g_f_Na * var_hyperpolarisation_activated_current__y * (var_hyperpolarisation_activated_current__V - 77.6));
    const double var_membrane__i_f_Na = var_hyperpolarisation_activated_current__i_f_Na;
    const double var_hyperpolarisation_activated_current__E_K = var_reversal_and_equilibrium_potentials__E_K;
    const double var_hyperpolarisation_activated_current__g_f_K_Centre_Published = 0.000548;
    const double var_hyperpolarisation_activated_current__g_f_K_Centre_1DCapable = 0.000437;
    const double var_hyperpolarisation_activated_current__g_f_K_Centre_0DCapable = 0.0005465;
    const double var_hyperpolarisation_activated_current__g_f_K_Periphery_Published = 0.0069;
    const double var_hyperpolarisation_activated_current__g_f_K_Periphery_1DCapable = 0.0055;
    const double var_hyperpolarisation_activated_current__g_f_K_Periphery_0DCapable = 0.006875;
    const double var_hyperpolarisation_activated_current__g_f_K = (var_hyperpolarisation_activated_current__Version == 0.0) ? (var_hyperpolarisation_activated_current__g_f_K_Centre_Published + (var_hyperpolarisation_activated_current__FCell * (var_hyperpolarisation_activated_current__g_f_K_Periphery_Published - var_hyperpolarisation_activated_current__g_f_K_Centre_Published))) : (var_hyperpolarisation_activated_current__Version == 1.0) ? (var_hyperpolarisation_activated_current__g_f_K_Centre_0DCapable + (var_hyperpolarisation_activated_current__FCell * (var_hyperpolarisation_activated_current__g_f_K_Periphery_0DCapable - var_hyperpolarisation_activated_current__g_f_K_Centre_0DCapable))) : (var_hyperpolarisation_activated_current__g_f_K_Centre_1DCapable + (var_hyperpolarisation_activated_current__FCell * (var_hyperpolarisation_activated_current__g_f_K_Periphery_1DCapable - var_hyperpolarisation_activated_current__g_f_K_Centre_1DCapable)));
    const double var_hyperpolarisation_activated_current__i_f_K = (var_hyperpolarisation_activated_current__Version != 2.0) ? (var_hyperpolarisation_activated_current__g_f_K * var_hyperpolarisation_activated_current__y * (var_hyperpolarisation_activated_current__V - var_hyperpolarisation_activated_current__E_K)) : (var_hyperpolarisation_activated_current__g_f_K * var_hyperpolarisation_activated_current__y * (var_hyperpolarisation_activated_current__V + 102.0));
    const double var_membrane__i_f_K = var_hyperpolarisation_activated_current__i_f_K;
    const double var_sodium_background_current__V = var_membrane__V;
    const double var_sodium_background_current__E_Na = var_reversal_and_equilibrium_potentials__E_Na;
    const double var_sodium_background_current__g_b_Na_Periphery_1DCapable = 0.000189;
    const double var_sodium_background_current__g_b_Na_Centre_1DCapable = 5.8e-05;
    const double var_sodium_background_current__g_b_Na_Centre_0DCapable = 5.81818e-05;
    const double var_sodium_background_current__g_b_Na_Periphery_Published = 0.000189;
    const double var_sodium_background_current__g_b_Na_Periphery_0DCapable = 0.0001888;
    const double var_sodium_background_current__Version = var_membrane__Version;
    const double var_sodium_background_current__FCell = var_membrane__FCell;
    const double var_sodium_background_current__g_b_Na_Centre_Published = 5.8e-05;
    const double var_sodium_background_current__g_b_Na = (var_sodium_background_current__Version == 0.0) ? (var_sodium_background_current__g_b_Na_Centre_Published + (var_sodium_background_current__FCell * (var_sodium_background_current__g_b_Na_Periphery_Published - var_sodium_background_current__g_b_Na_Centre_Published))) : (var_sodium_background_current__Version == 1.0) ? (var_sodium_background_current__g_b_Na_Centre_0DCapable + (var_sodium_background_current__FCell * (var_sodium_background_current__g_b_Na_Periphery_0DCapable - var_sodium_background_current__g_b_Na_Centre_0DCapable))) : (var_sodium_background_current__g_b_Na_Centre_1DCapable + (var_sodium_background_current__FCell * (var_sodium_background_current__g_b_Na_Periphery_1DCapable - var_sodium_background_current__g_b_Na_Centre_1DCapable)));
    const double var_sodium_background_current__i_b_Na = var_sodium_background_current__g_b_Na * (var_sodium_background_current__V - var_sodium_background_current__E_Na);
    const double var_membrane__i_b_Na = var_sodium_background_current__i_b_Na;
    const double var_ionic_concentrations__Ca_i = 0.0001;
    const double var_reversal_and_equilibrium_potentials__Ca_i = var_ionic_concentrations__Ca_i;
    const double var_ionic_concentrations__Ca_o = 2.0;
    const double var_reversal_and_equilibrium_potentials__Ca_o = var_ionic_concentrations__Ca_o;
    const double var_reversal_and_equilibrium_potentials__E_Ca = ((var_reversal_and_equilibrium_potentials__R * var_reversal_and_equilibrium_potentials__T) / (2.0 * var_reversal_and_equilibrium_potentials__F)) * log(var_reversal_and_equilibrium_potentials__Ca_o / var_reversal_and_equilibrium_potentials__Ca_i);
    const double var_calcium_background_current__E_Ca = var_reversal_and_equilibrium_potentials__E_Ca;
    const double var_calcium_background_current__Version = var_membrane__Version;
    const double var_calcium_background_current__g_b_Ca_Periphery_Published = 4.3e-05;
    const double var_calcium_background_current__g_b_Ca_Centre_Published = 1.32e-05;
    const double var_calcium_background_current__g_b_Ca_Centre_0DCapable = 1.3236e-05;
    const double var_calcium_background_current__g_b_Ca_Periphery_0DCapable = 4.2952e-05;
    const double var_calcium_background_current__g_b_Ca_Periphery_1DCapable = 4.29e-05;
    const double var_calcium_background_current__g_b_Ca_Centre_1DCapable = 1.323e-05;
    const double var_calcium_background_current__FCell = var_membrane__FCell;
    const double var_calcium_background_current__g_b_Ca = (var_calcium_background_current__Version == 0.0) ? (var_calcium_background_current__g_b_Ca_Centre_Published + (var_calcium_background_current__FCell * (var_calcium_background_current__g_b_Ca_Periphery_Published - var_calcium_background_current__g_b_Ca_Centre_Published))) : (var_calcium_background_current__Version == 1.0) ? (var_calcium_background_current__g_b_Ca_Centre_0DCapable + (var_calcium_background_current__FCell * (var_calcium_background_current__g_b_Ca_Periphery_0DCapable - var_calcium_background_current__g_b_Ca_Centre_0DCapable))) : (var_calcium_background_current__g_b_Ca_Centre_1DCapable + (var_calcium_background_current__FCell * (var_calcium_background_current__g_b_Ca_Periphery_1DCapable - var_calcium_background_current__g_b_Ca_Centre_1DCapable)));
    const double var_calcium_background_current__V = var_membrane__V;
    const double var_calcium_background_current__i_b_Ca = var_calcium_background_current__g_b_Ca * (var_calcium_background_current__V - var_calcium_background_current__E_Ca);
    const double var_membrane__i_b_Ca = var_calcium_background_current__i_b_Ca;
    const double var_potassium_background_current__E_K = var_reversal_and_equilibrium_potentials__E_K;
    const double var_potassium_background_current__Version = var_membrane__Version;
    const double var_potassium_background_current__g_b_K_Periphery_1DCapable = 8.19e-05;
    const double var_potassium_background_current__g_b_K_Periphery_Published = 8.19e-05;
    const double var_potassium_background_current__g_b_K_Centre_1DCapable = 2.52e-05;
    const double var_potassium_background_current__g_b_K_Centre_0DCapable = 2.523636e-05;
    const double var_potassium_background_current__g_b_K_Periphery_0DCapable = 8.1892e-05;
    const double var_potassium_background_current__g_b_K_Centre_Published = 2.52e-05;
    const double var_potassium_background_current__FCell = var_membrane__FCell;
    const double var_potassium_background_current__g_b_K = (var_potassium_background_current__Version == 0.0) ? (var_potassium_background_current__g_b_K_Centre_Published + (var_potassium_background_current__FCell * (var_potassium_background_current__g_b_K_Periphery_Published - var_potassium_background_current__g_b_K_Centre_Published))) : (var_potassium_background_current__Version == 1.0) ? (var_potassium_background_current__g_b_K_Centre_0DCapable + (var_potassium_background_current__FCell * (var_potassium_background_current__g_b_K_Periphery_0DCapable - var_potassium_background_current__g_b_K_Centre_0DCapable))) : (var_potassium_background_current__g_b_K_Centre_1DCapable + (var_potassium_background_current__FCell * (var_potassium_background_current__g_b_K_Periphery_1DCapable - var_potassium_background_current__g_b_K_Centre_1DCapable)));
    const double var_potassium_background_current__V = var_membrane__V;
    const double var_potassium_background_current__i_b_K = var_potassium_background_current__g_b_K * (var_potassium_background_current__V - var_potassium_background_current__E_K);
    const double var_membrane__i_b_K = var_potassium_background_current__i_b_K;
    const double var_sodium_calcium_exchanger__gamma_NaCa = 0.5;
    const double var_sodium_calcium_exchanger__d_NaCa = 0.0001;
    const double var_sodium_calcium_exchanger__Na_i = var_ionic_concentrations__Na_i;
    const double var_sodium_calcium_exchanger__Version = var_membrane__Version;
    const double var_sodium_calcium_exchanger__Ca_i = var_ionic_concentrations__Ca_i;
    const double var_sodium_calcium_exchanger__V = var_membrane__V;
    const double var_sodium_calcium_exchanger__Na_o = var_ionic_concentrations__Na_o;
    const double var_sodium_calcium_exchanger__Ca_o = var_ionic_concentrations__Ca_o;
    const double var_sodium_calcium_exchanger__k_NaCa_Centre_1DCapable = 2.8e-06;
    const double var_sodium_calcium_exchanger__k_NaCa_Centre_0DCapable = 2.7229e-06;
    const double var_sodium_calcium_exchanger__k_NaCa_Periphery_0DCapable = 8.83584e-06;
    const double var_sodium_calcium_exchanger__k_NaCa_Centre_Published = 2.7e-06;
    const double var_sodium_calcium_exchanger__k_NaCa_Periphery_1DCapable = 8.8e-06;
    const double var_sodium_calcium_exchanger__FCell = var_membrane__FCell;
    const double var_sodium_calcium_exchanger__k_NaCa_Periphery_Published = 8.8e-06;
    const double var_sodium_calcium_exchanger__k_NaCa = (var_sodium_calcium_exchanger__Version == 0.0) ? (var_sodium_calcium_exchanger__k_NaCa_Centre_Published + (var_sodium_calcium_exchanger__FCell * (var_sodium_calcium_exchanger__k_NaCa_Periphery_Published - var_sodium_calcium_exchanger__k_NaCa_Centre_Published))) : (var_sodium_calcium_exchanger__Version == 1.0) ? (var_sodium_calcium_exchanger__k_NaCa_Centre_0DCapable + (var_sodium_calcium_exchanger__FCell * (var_sodium_calcium_exchanger__k_NaCa_Periphery_0DCapable - var_sodium_calcium_exchanger__k_NaCa_Centre_0DCapable))) : (var_sodium_calcium_exchanger__k_NaCa_Centre_1DCapable + (var_sodium_calcium_exchanger__FCell * (var_sodium_calcium_exchanger__k_NaCa_Periphery_1DCapable - var_sodium_calcium_exchanger__k_NaCa_Centre_1DCapable)));
    const double var_sodium_calcium_exchanger__i_NaCa = (var_sodium_calcium_exchanger__Version == 0.0) ? ((var_sodium_calcium_exchanger__k_NaCa * ((pow(var_sodium_calcium_exchanger__Na_i, 3.0) * var_sodium_calcium_exchanger__Ca_o * exp(0.03743 * var_sodium_calcium_exchanger__V * var_sodium_calcium_exchanger__gamma_NaCa)) - (pow(var_sodium_calcium_exchanger__Na_o, 3.0) * var_sodium_calcium_exchanger__Ca_i * exp(0.0374 * var_sodium_calcium_exchanger__V * (var_sodium_calcium_exchanger__gamma_NaCa - 1.0))))) / (1.0 + (var_sodium_calcium_exchanger__d_NaCa * ((var_sodium_calcium_exchanger__Ca_i * pow(var_sodium_calcium_exchanger__Na_o, 3.0)) + (var_sodium_calcium_exchanger__Ca_o * pow(var_sodium_calcium_exchanger__Na_i, 3.0)))))) : ((var_sodium_calcium_exchanger__k_NaCa * ((pow(var_sodium_calcium_exchanger__Na_i, 3.0) * var_sodium_calcium_exchanger__Ca_o * exp(0.03743 * var_sodium_calcium_exchanger__V * var_sodium_calcium_exchanger__gamma_NaCa)) - (pow(var_sodium_calcium_exchanger__Na_o, 3.0) * var_sodium_calcium_exchanger__Ca_i * exp(0.03743 * var_sodium_calcium_exchanger__V * (var_sodium_calcium_exchanger__gamma_NaCa - 1.0))))) / (1.0 + (var_sodium_calcium_exchanger__d_NaCa * ((var_sodium_calcium_exchanger__Ca_i * pow(var_sodium_calcium_exchanger__Na_o, 3.0)) + (var_sodium_calcium_exchanger__Ca_o * pow(var_sodium_calcium_exchanger__Na_i, 3.0))))));
    const double var_membrane__i_NaCa = var_sodium_calcium_exchanger__i_NaCa;
    const double var_sodium_potassium_pump__K_m_Na = 5.64;
    const double var_sodium_potassium_pump__K_m_K = 0.621;
    const double var_sodium_potassium_pump__V = var_membrane__V;
    const double var_sodium_potassium_pump__Version = var_membrane__Version;
    const double var_sodium_potassium_pump__i_p_max_Centre_1DCapable = 0.0478;
    const double var_sodium_potassium_pump__FCell = var_membrane__FCell;
    const double var_sodium_potassium_pump__i_p_max_Periphery_1DCapable = 0.16;
    const double var_sodium_potassium_pump__i_p_max_Periphery_Published = 0.16;
    const double var_sodium_potassium_pump__i_p_max_Centre_0DCapable = 0.04782545;
    const double var_sodium_potassium_pump__i_p_max_Centre_Published = 0.0478;
    const double var_sodium_potassium_pump__i_p_max_Periphery_0DCapable = 0.1551936;
    const double var_sodium_potassium_pump__i_p_max = (var_sodium_potassium_pump__Version == 0.0) ? (var_sodium_potassium_pump__i_p_max_Centre_Published + (var_sodium_potassium_pump__FCell * (var_sodium_potassium_pump__i_p_max_Periphery_Published - var_sodium_potassium_pump__i_p_max_Centre_Published))) : (var_sodium_potassium_pump__Version == 1.0) ? (var_sodium_potassium_pump__i_p_max_Centre_0DCapable + (var_sodium_potassium_pump__FCell * (var_sodium_potassium_pump__i_p_max_Periphery_0DCapable - var_sodium_potassium_pump__i_p_max_Centre_0DCapable))) : (var_sodium_potassium_pump__i_p_max_Centre_1DCapable + (var_sodium_potassium_pump__FCell * (var_sodium_potassium_pump__i_p_max_Periphery_1DCapable - var_sodium_potassium_pump__i_p_max_Centre_1DCapable)));
    const double var_sodium_potassium_pump__K_o = var_ionic_concentrations__K_o;
    const double var_sodium_potassium_pump__Na_i = var_ionic_concentrations__Na_i;
    const double var_sodium_potassium_pump__i_p = (var_sodium_potassium_pump__i_p_max * pow(var_sodium_potassium_pump__Na_i / (var_sodium_potassium_pump__K_m_Na + var_sodium_potassium_pump__Na_i), 3.0) * pow(var_sodium_potassium_pump__K_o / (var_sodium_potassium_pump__K_m_K + var_sodium_potassium_pump__K_o), 2.0) * 1.6) / (1.5 + exp((-(var_sodium_potassium_pump__V + 60.0)) / 40.0));
    const double var_membrane__i_p = var_sodium_potassium_pump__i_p;
    const double var_persistent_calcium_current__Ca_i = var_ionic_concentrations__Ca_i;
    const double var_persistent_calcium_current__Version = var_membrane__Version;
    const double var_persistent_calcium_current__i_Ca_p_max_Centre_1DCapable = 0.0042;
    const double var_persistent_calcium_current__i_Ca_p_max_Periphery_Published = 0.0;
    const double var_persistent_calcium_current__i_Ca_p_max_Centre_Published = 0.0;
    const double var_persistent_calcium_current__i_Ca_p_max_Periphery_1DCapable = 0.03339;
    const double var_persistent_calcium_current__FCell = var_membrane__FCell;
    const double var_persistent_calcium_current__i_Ca_p_max_Centre_0DCapable = 0.0;
    const double var_persistent_calcium_current__i_Ca_p_max_Periphery_0DCapable = 0.0;
    const double var_persistent_calcium_current__i_Ca_p_max = (var_persistent_calcium_current__Version == 0.0) ? (var_persistent_calcium_current__i_Ca_p_max_Centre_Published + (var_persistent_calcium_current__FCell * (var_persistent_calcium_current__i_Ca_p_max_Periphery_Published - var_persistent_calcium_current__i_Ca_p_max_Centre_Published))) : (var_persistent_calcium_current__Version == 1.0) ? (var_persistent_calcium_current__i_Ca_p_max_Centre_0DCapable + (var_persistent_calcium_current__FCell * (var_persistent_calcium_current__i_Ca_p_max_Periphery_0DCapable - var_persistent_calcium_current__i_Ca_p_max_Centre_0DCapable))) : (var_persistent_calcium_current__i_Ca_p_max_Centre_1DCapable + (var_persistent_calcium_current__FCell * (var_persistent_calcium_current__i_Ca_p_max_Periphery_1DCapable - var_persistent_calcium_current__i_Ca_p_max_Centre_1DCapable)));
    const double var_persistent_calcium_current__i_Ca_p = (var_persistent_calcium_current__i_Ca_p_max * var_persistent_calcium_current__Ca_i) / (var_persistent_calcium_current__Ca_i + 0.0004);
    const double var_membrane__i_Ca_p = var_persistent_calcium_current__i_Ca_p;
    const double var_sodium_current_m_gate__Version = var_sodium_current__Version;
    const double var_sodium_current_m_gate__V = var_sodium_current__V;
    const double var_sodium_current_m_gate__m_infinity = (var_sodium_current_m_gate__Version == 0.0) ? pow(1.0 / (1.0 + exp((-var_sodium_current_m_gate__V) / 5.46)), 1.0 / 3.0) : pow(1.0 / (1.0 + exp((-(var_sodium_current_m_gate__V + 30.32)) / 5.46)), 1.0 / 3.0);
    const double var_sodium_current_m_gate__tau_m = (var_sodium_current_m_gate__Version == 0.0) ? ((0.0006247 / ((0.832 * exp((-0.335) * (var_sodium_current_m_gate__V + 56.7))) + (0.627 * exp(0.082 * (var_sodium_current_m_gate__V + 65.01))))) + 4e-05) : ((0.0006247 / ((0.8322166 * exp((-0.33566) * (var_sodium_current_m_gate__V + 56.7062))) + (0.6274 * exp(0.0823 * (var_sodium_current_m_gate__V + 65.0131))))) + 4.569e-05);
    const double var_sodium_current_h_gate__h1_infinity = 1.0 / (1.0 + exp((var_sodium_current_h_gate__V + 66.1) / 6.4));
    const double var_sodium_current_h_gate__h2_infinity = var_sodium_current_h_gate__h1_infinity;
    const double var_sodium_current_h_gate__tau_h1 = ((3.717e-06 * exp((-0.2815) * (var_sodium_current_h_gate__V + 17.11))) / (1.0 + (0.003732 * exp((-0.3426) * (var_sodium_current_h_gate__V + 37.76))))) + 0.0005977;
    const double var_sodium_current_h_gate__tau_h2 = ((3.186e-08 * exp((-0.6219) * (var_sodium_current_h_gate__V + 18.8))) / (1.0 + (7.189e-05 * exp((-0.6683) * (var_sodium_current_h_gate__V + 34.07))))) + 0.003556;
    const double var_L_type_Ca_channel_d_gate__Version = var_L_type_Ca_channel__Version;
    const double var_L_type_Ca_channel_d_gate__FCell = var_L_type_Ca_channel__FCell;
    const double var_L_type_Ca_channel_d_gate__V = var_L_type_Ca_channel__V;
    const double var_L_type_Ca_channel_d_gate__alpha_d_L = (var_L_type_Ca_channel_d_gate__Version == 0.0) ? ((((-28.38) * (var_L_type_Ca_channel_d_gate__V + 35.0)) / (exp((-(var_L_type_Ca_channel_d_gate__V + 35.0)) / 2.5) - 1.0)) - ((84.9 * var_L_type_Ca_channel_d_gate__V) / (exp((-0.208) * var_L_type_Ca_channel_d_gate__V) - 1.0))) : (var_L_type_Ca_channel_d_gate__Version == 1.0) ? ((((-28.39) * (var_L_type_Ca_channel_d_gate__V + 35.0)) / (exp((-(var_L_type_Ca_channel_d_gate__V + 35.0)) / 2.5) - 1.0)) - ((84.9 * var_L_type_Ca_channel_d_gate__V) / (exp((-0.208) * var_L_type_Ca_channel_d_gate__V) - 1.0))) : ((((-28.4) * (var_L_type_Ca_channel_d_gate__V + 35.0)) / (exp((-(var_L_type_Ca_channel_d_gate__V + 35.0)) / 2.5) - 1.0)) - ((84.9 * var_L_type_Ca_channel_d_gate__V) / (exp((-0.208) * var_L_type_Ca_channel_d_gate__V) - 1.0)));
    const double var_L_type_Ca_channel_d_gate__beta_d_L = (var_L_type_Ca_channel_d_gate__Version == 1.0) ? ((11.43 * (var_L_type_Ca_channel_d_gate__V - 5.0)) / (exp(0.4 * (var_L_type_Ca_channel_d_gate__V - 5.0)) - 1.0)) : ((11.42 * (var_L_type_Ca_channel_d_gate__V - 5.0)) / (exp(0.4 * (var_L_type_Ca_channel_d_gate__V - 5.0)) - 1.0));
    const double var_L_type_Ca_channel_d_gate__d_L_infinity = (var_L_type_Ca_channel_d_gate__Version == 0.0) ? (1.0 / (1.0 + exp((-(var_L_type_Ca_channel_d_gate__V + 23.1)) / 6.0))) : (var_L_type_Ca_channel_d_gate__Version == 1.0) ? (1.0 / (1.0 + exp((-(var_L_type_Ca_channel_d_gate__V + 22.3 + (0.8 * var_L_type_Ca_channel_d_gate__FCell))) / 6.0))) : (1.0 / (1.0 + exp((-(var_L_type_Ca_channel_d_gate__V + 22.2)) / 6.0)));
    const double var_L_type_Ca_channel_d_gate__tau_d_L = 2.0 / (var_L_type_Ca_channel_d_gate__alpha_d_L + var_L_type_Ca_channel_d_gate__beta_d_L);
    const double var_L_type_Ca_channel_f_gate__Version = var_L_type_Ca_channel__Version;
    const double var_L_type_Ca_channel_f_gate__FCell = var_L_type_Ca_channel__FCell;
    const double var_L_type_Ca_channel_f_gate__V = var_L_type_Ca_channel__V;
    const double var_L_type_Ca_channel_f_gate__alpha_f_L = (var_L_type_Ca_channel_f_gate__Version == 1.0) ? ((3.75 * (var_L_type_Ca_channel_f_gate__V + 28.0)) / (exp((var_L_type_Ca_channel_f_gate__V + 28.0) / 4.0) - 1.0)) : ((3.12 * (var_L_type_Ca_channel_f_gate__V + 28.0)) / (exp((var_L_type_Ca_channel_f_gate__V + 28.0) / 4.0) - 1.0));
    const double var_L_type_Ca_channel_f_gate__beta_f_L = (var_L_type_Ca_channel_f_gate__Version == 1.0) ? (30.0 / (1.0 + exp((-(var_L_type_Ca_channel_f_gate__V + 28.0)) / 4.0))) : (25.0 / (1.0 + exp((-(var_L_type_Ca_channel_f_gate__V + 28.0)) / 4.0)));
    const double var_L_type_Ca_channel_f_gate__f_L_infinity = 1.0 / (1.0 + exp((var_L_type_Ca_channel_f_gate__V + 45.0) / 5.0));
    const double var_L_type_Ca_channel_f_gate__tau_f_L = (var_L_type_Ca_channel_f_gate__Version == 1.0) ? ((1.2 - (0.2 * var_L_type_Ca_channel_f_gate__FCell)) / (var_L_type_Ca_channel_f_gate__alpha_f_L + var_L_type_Ca_channel_f_gate__beta_f_L)) : (1.0 / (var_L_type_Ca_channel_f_gate__alpha_f_L + var_L_type_Ca_channel_f_gate__beta_f_L));
    const double var_T_type_Ca_channel_d_gate__V = var_T_type_Ca_channel__V;
    const double var_T_type_Ca_channel_d_gate__alpha_d_T = 1068.0 * exp((var_T_type_Ca_channel_d_gate__V + 26.3) / 30.0);
    const double var_T_type_Ca_channel_d_gate__beta_d_T = 1068.0 * exp((-(var_T_type_Ca_channel_d_gate__V + 26.3)) / 30.0);
    const double var_T_type_Ca_channel_d_gate__d_T_infinity = 1.0 / (1.0 + exp((-(var_T_type_Ca_channel_d_gate__V + 37.0)) / 6.8));
    const double var_T_type_Ca_channel_d_gate__tau_d_T = 1.0 / (var_T_type_Ca_channel_d_gate__alpha_d_T + var_T_type_Ca_channel_d_gate__beta_d_T);
    const double var_T_type_Ca_channel_f_gate__Version = var_T_type_Ca_channel__Version;
    const double var_T_type_Ca_channel_f_gate__FCell = var_T_type_Ca_channel__FCell;
    const double var_T_type_Ca_channel_f_gate__V = var_T_type_Ca_channel__V;
    const double var_T_type_Ca_channel_f_gate__alpha_f_T = (var_T_type_Ca_channel_f_gate__Version == 1.0) ? (15.3 * exp((-(var_T_type_Ca_channel_f_gate__V + 71.0 + (0.7 * var_T_type_Ca_channel_f_gate__FCell))) / 83.3)) : (15.3 * exp((-(var_T_type_Ca_channel_f_gate__V + 71.7)) / 83.3));
    const double var_T_type_Ca_channel_f_gate__beta_f_T = (var_T_type_Ca_channel_f_gate__Version == 1.0) ? (15.0 * exp((var_T_type_Ca_channel_f_gate__V + 71.0) / 15.38)) : (15.0 * exp((var_T_type_Ca_channel_f_gate__V + 71.7) / 15.38));
    const double var_T_type_Ca_channel_f_gate__f_T_infinity = 1.0 / (1.0 + exp((var_T_type_Ca_channel_f_gate__V + 71.0) / 9.0));
    const double var_T_type_Ca_channel_f_gate__tau_f_T = 1.0 / (var_T_type_Ca_channel_f_gate__alpha_f_T + var_T_type_Ca_channel_f_gate__beta_f_T);
    const double var_four_AP_sensitive_currents_q_gate__Version = var_four_AP_sensitive_currents__Version;
    const double var_four_AP_sensitive_currents_q_gate__FCell = var_four_AP_sensitive_currents__FCell;
    const double var_four_AP_sensitive_currents_q_gate__V = var_four_AP_sensitive_currents__V;
    const double var_four_AP_sensitive_currents_q_gate__q_infinity = 1.0 / (1.0 + exp((var_four_AP_sensitive_currents_q_gate__V + 59.37) / 13.1));
    const double var_four_AP_sensitive_currents_q_gate__tau_q = (var_four_AP_sensitive_currents_q_gate__Version == 0.0) ? (0.0101 + (0.06517 / (0.57 * exp((-0.08) * (var_four_AP_sensitive_currents_q_gate__V + 49.0)))) + (2.4e-05 * exp(0.1 * (var_four_AP_sensitive_currents_q_gate__V + 50.93)))) : (var_four_AP_sensitive_currents_q_gate__Version == 1.0) ? ((0.001 / 3.0) * (30.31 + (195.5 / ((0.5686 * exp((-0.08161) * (var_four_AP_sensitive_currents_q_gate__V + 39.0 + (10.0 * var_four_AP_sensitive_currents_q_gate__FCell)))) + (0.7174 * exp((0.2719 - (0.1719 * var_four_AP_sensitive_currents_q_gate__FCell)) * 1.0 * (var_four_AP_sensitive_currents_q_gate__V + 40.93 + (10.0 * var_four_AP_sensitive_currents_q_gate__FCell)))))))) : (0.0101 + (0.06517 / ((0.5686 * exp((-0.08161) * (var_four_AP_sensitive_currents_q_gate__V + 39.0))) + (0.7174 * exp(0.2719 * (var_four_AP_sensitive_currents_q_gate__V + 40.93))))));
    const double var_four_AP_sensitive_currents_r_gate__Version = var_four_AP_sensitive_currents__Version;
    const double var_four_AP_sensitive_currents_r_gate__V = var_four_AP_sensitive_currents__V;
    const double var_four_AP_sensitive_currents_r_gate__r_infinity = 1.0 / (1.0 + exp((-(var_four_AP_sensitive_currents_r_gate__V - 10.93)) / 19.7));
    const double var_four_AP_sensitive_currents_r_gate__tau_r = (var_four_AP_sensitive_currents_r_gate__Version == 0.0) ? (0.001 * (2.98 + (15.59 / ((1.037 * exp(0.09 * (var_four_AP_sensitive_currents_r_gate__V + 30.61))) + (0.369 * exp((-0.12) * (var_four_AP_sensitive_currents_r_gate__V + 23.84))))))) : (var_four_AP_sensitive_currents_r_gate__Version == 1.0) ? (0.0025 * (1.191 + (7.838 / ((1.037 * exp(0.09012 * (var_four_AP_sensitive_currents_r_gate__V + 30.61))) + (0.369 * exp((-0.119) * (var_four_AP_sensitive_currents_r_gate__V + 23.84))))))) : (0.001 * (2.98 + (19.59 / ((1.037 * exp(0.09012 * (var_four_AP_sensitive_currents_r_gate__V + 30.61))) + (0.369 * exp((-0.119) * (var_four_AP_sensitive_currents_r_gate__V + 23.84)))))));
    const double var_rapid_delayed_rectifying_potassium_current_P_af_gate__Version = var_rapid_delayed_rectifying_potassium_current__Version;
    const double var_rapid_delayed_rectifying_potassium_current_P_af_gate__V = var_rapid_delayed_rectifying_potassium_current__V;
    const double var_rapid_delayed_rectifying_potassium_current_P_af_gate__P_af_infinity = (var_rapid_delayed_rectifying_potassium_current_P_af_gate__Version != 2.0) ? (1.0 / (1.0 + exp((-(var_rapid_delayed_rectifying_potassium_current_P_af_gate__V + 14.2)) / 10.6))) : (1.0 / (1.0 + exp((-(var_rapid_delayed_rectifying_potassium_current_P_af_gate__V + 13.2)) / 10.6)));
    const double var_rapid_delayed_rectifying_potassium_current_P_af_gate__tau_P_af = (var_rapid_delayed_rectifying_potassium_current_P_af_gate__Version != 2.0) ? (1.0 / ((37.2 * exp((var_rapid_delayed_rectifying_potassium_current_P_af_gate__V - 9.0) / 15.9)) + (0.96 * exp((-(var_rapid_delayed_rectifying_potassium_current_P_af_gate__V - 9.0)) / 22.5)))) : (1.0 / ((37.2 * exp((var_rapid_delayed_rectifying_potassium_current_P_af_gate__V - 10.0) / 15.9)) + (0.96 * exp((-(var_rapid_delayed_rectifying_potassium_current_P_af_gate__V - 10.0)) / 22.5))));
    const double var_rapid_delayed_rectifying_potassium_current_P_as_gate__Version = var_rapid_delayed_rectifying_potassium_current__Version;
    const double var_rapid_delayed_rectifying_potassium_current_P_as_gate__P_af_infinity = var_rapid_delayed_rectifying_potassium_current_P_af_gate__P_af_infinity;
    const double var_rapid_delayed_rectifying_potassium_current_P_as_gate__P_as_infinity = var_rapid_delayed_rectifying_potassium_current_P_as_gate__P_af_infinity;
    const double var_rapid_delayed_rectifying_potassium_current_P_as_gate__V = var_rapid_delayed_rectifying_potassium_current__V;
    const double var_rapid_delayed_rectifying_potassium_current_P_as_gate__tau_P_as = (var_rapid_delayed_rectifying_potassium_current_P_as_gate__Version != 2.0) ? (1.0 / ((4.2 * exp((var_rapid_delayed_rectifying_potassium_current_P_as_gate__V - 9.0) / 17.0)) + (0.15 * exp((-(var_rapid_delayed_rectifying_potassium_current_P_as_gate__V - 9.0)) / 21.6)))) : (1.0 / ((4.2 * exp((var_rapid_delayed_rectifying_potassium_current_P_as_gate__V - 10.0) / 17.0)) + (0.15 * exp((-(var_rapid_delayed_rectifying_potassium_current_P_as_gate__V - 10.0)) / 21.6))));
    const double var_rapid_delayed_rectifying_potassium_current_P_i_gate__Version = var_rapid_delayed_rectifying_potassium_current__Version;
    const double var_rapid_delayed_rectifying_potassium_current_P_i_gate__V = var_rapid_delayed_rectifying_potassium_current__V;
    const double var_rapid_delayed_rectifying_potassium_current_P_i_gate__P_i_infinity = 1.0 / (1.0 + exp((var_rapid_delayed_rectifying_potassium_current_P_i_gate__V + 18.6) / 10.1));
    const double var_rapid_delayed_rectifying_potassium_current_P_i_gate__tau_P_i = (var_rapid_delayed_rectifying_potassium_current_P_i_gate__Version == 0.0) ? 0.002 : (var_rapid_delayed_rectifying_potassium_current_P_i_gate__Version == 1.0) ? 0.002 : 0.006;
    const double var_slow_delayed_rectifying_potassium_current_xs_gate__V = var_slow_delayed_rectifying_potassium_current__V;
    const double var_slow_delayed_rectifying_potassium_current_xs_gate__alpha_xs = 14.0 / (1.0 + exp((-(var_slow_delayed_rectifying_potassium_current_xs_gate__V - 40.0)) / 9.0));
    const double var_slow_delayed_rectifying_potassium_current_xs_gate__beta_xs = 1.0 * exp((-var_slow_delayed_rectifying_potassium_current_xs_gate__V) / 45.0);
    const double var_hyperpolarisation_activated_current_y_gate__Version = var_hyperpolarisation_activated_current__Version;
    const double var_hyperpolarisation_activated_current_y_gate__V = var_hyperpolarisation_activated_current__V;
    const double var_hyperpolarisation_activated_current_y_gate__alpha_y = (var_hyperpolarisation_activated_current_y_gate__Version == 0.0) ? (1.0 * exp((-(var_hyperpolarisation_activated_current_y_gate__V + 78.91)) / 26.62)) : (1.0 * exp((-(var_hyperpolarisation_activated_current_y_gate__V + 78.91)) / 26.63));
    const double var_hyperpolarisation_activated_current_y_gate__beta_y = 1.0 * exp((var_hyperpolarisation_activated_current_y_gate__V + 75.13) / 21.25);
    
    const double d_dt_membrane__V = ((-1.0) / var_membrane__Cm) * (var_membrane__i_Na + var_membrane__i_Ca_L + var_membrane__i_Ca_T + var_membrane__i_to + var_membrane__i_sus + var_membrane__i_K_r + var_membrane__i_K_s + var_membrane__i_f_Na + var_membrane__i_f_K + var_membrane__i_b_Na + var_membrane__i_b_Ca + var_membrane__i_b_K + var_membrane__i_NaCa + var_membrane__i_p + var_membrane__i_Ca_p);
    const double d_dt_sodium_current_m_gate__m = (var_sodium_current_m_gate__m_infinity - var_sodium_current_m_gate__m) / var_sodium_current_m_gate__tau_m;
    const double d_dt_sodium_current_h_gate__h1 = (var_sodium_current_h_gate__h1_infinity - var_sodium_current_h_gate__h1) / var_sodium_current_h_gate__tau_h1;
    const double d_dt_sodium_current_h_gate__h2 = (var_sodium_current_h_gate__h2_infinity - var_sodium_current_h_gate__h2) / var_sodium_current_h_gate__tau_h2;
    const double d_dt_L_type_Ca_channel_d_gate__d_L = (var_L_type_Ca_channel_d_gate__d_L_infinity - var_L_type_Ca_channel_d_gate__d_L) / var_L_type_Ca_channel_d_gate__tau_d_L;
    const double d_dt_L_type_Ca_channel_f_gate__f_L = (var_L_type_Ca_channel_f_gate__f_L_infinity - var_L_type_Ca_channel_f_gate__f_L) / var_L_type_Ca_channel_f_gate__tau_f_L;
    const double d_dt_T_type_Ca_channel_d_gate__d_T = (var_T_type_Ca_channel_d_gate__d_T_infinity - var_T_type_Ca_channel_d_gate__d_T) / var_T_type_Ca_channel_d_gate__tau_d_T;
    const double d_dt_T_type_Ca_channel_f_gate__f_T = (var_T_type_Ca_channel_f_gate__f_T_infinity - var_T_type_Ca_channel_f_gate__f_T) / var_T_type_Ca_channel_f_gate__tau_f_T;
    const double d_dt_four_AP_sensitive_currents_q_gate__q = (var_four_AP_sensitive_currents_q_gate__q_infinity - var_four_AP_sensitive_currents_q_gate__q) / var_four_AP_sensitive_currents_q_gate__tau_q;
    const double d_dt_four_AP_sensitive_currents_r_gate__r = (var_four_AP_sensitive_currents_r_gate__r_infinity - var_four_AP_sensitive_currents_r_gate__r) / var_four_AP_sensitive_currents_r_gate__tau_r;
    const double d_dt_rapid_delayed_rectifying_potassium_current_P_af_gate__P_af = (var_rapid_delayed_rectifying_potassium_current_P_af_gate__P_af_infinity - var_rapid_delayed_rectifying_potassium_current_P_af_gate__P_af) / var_rapid_delayed_rectifying_potassium_current_P_af_gate__tau_P_af;
    const double d_dt_rapid_delayed_rectifying_potassium_current_P_as_gate__P_as = (var_rapid_delayed_rectifying_potassium_current_P_as_gate__P_as_infinity - var_rapid_delayed_rectifying_potassium_current_P_as_gate__P_as) / var_rapid_delayed_rectifying_potassium_current_P_as_gate__tau_P_as;
    const double d_dt_rapid_delayed_rectifying_potassium_current_P_i_gate__P_i = (var_rapid_delayed_rectifying_potassium_current_P_i_gate__P_i_infinity - var_rapid_delayed_rectifying_potassium_current_P_i_gate__P_i) / var_rapid_delayed_rectifying_potassium_current_P_i_gate__tau_P_i;
    const double d_dt_slow_delayed_rectifying_potassium_current_xs_gate__xs = (var_slow_delayed_rectifying_potassium_current_xs_gate__alpha_xs * (1.0 - var_slow_delayed_rectifying_potassium_current_xs_gate__xs)) - (var_slow_delayed_rectifying_potassium_current_xs_gate__beta_xs * var_slow_delayed_rectifying_potassium_current_xs_gate__xs);
    const double d_dt_hyperpolarisation_activated_current_y_gate__y = (var_hyperpolarisation_activated_current_y_gate__alpha_y * (1.0 - var_hyperpolarisation_activated_current_y_gate__y)) - (var_hyperpolarisation_activated_current_y_gate__beta_y * var_hyperpolarisation_activated_current_y_gate__y);
    
    classe->V_lado_direito_ = d_dt_membrane__V;
    classe->m_lado_direito_ = d_dt_sodium_current_m_gate__m;
    classe->h1_lado_direito_ = d_dt_sodium_current_h_gate__h1;
    classe->h2_lado_direito_ = d_dt_sodium_current_h_gate__h2;
    classe->d_L_lado_direito_ = d_dt_L_type_Ca_channel_d_gate__d_L;
    classe->f_L_lado_direito_ = d_dt_L_type_Ca_channel_f_gate__f_L;
    classe->d_T_lado_direito_ = d_dt_T_type_Ca_channel_d_gate__d_T;
    classe->f_T_lado_direito_ = d_dt_T_type_Ca_channel_f_gate__f_T;
    classe->q_lado_direito_ = d_dt_four_AP_sensitive_currents_q_gate__q;
    classe->r_lado_direito_ = d_dt_four_AP_sensitive_currents_r_gate__r;
    classe->P_af_lado_direito_ = d_dt_rapid_delayed_rectifying_potassium_current_P_af_gate__P_af;
    classe->P_as_lado_direito_ = d_dt_rapid_delayed_rectifying_potassium_current_P_as_gate__P_as;
    classe->P_i_lado_direito_ = d_dt_rapid_delayed_rectifying_potassium_current_P_i_gate__P_i;
    classe->xs_lado_direito_ = d_dt_slow_delayed_rectifying_potassium_current_xs_gate__xs;
    classe->y_lado_direito_ = d_dt_hyperpolarisation_activated_current_y_gate__y;
};


#endif
